export default {
  // ─── Access Control ───────────────────────────────────────
  accessForbiddenTitle: 'Accès non autorisé',
  accessForbiddenBody:
    "Votre rôle ne vous donne pas accès à cette page. Contactez un administrateur si vous pensez qu'il s'agit d'une erreur.",
  accessForbiddenRoles: 'Rôles actuels',
  backToDashboard: 'Retour au tableau de bord',

  // Levels
  accessLevel: "Niveau d'accès",
  accessLevelNone: 'Aucun',
  accessLevelRead: 'Lecture',
  accessLevelUser: 'Utilisateur',
  accessLevelManager: 'Responsable',
  accessLevelCustom: 'Personnalisé',
  accessLevelNoneHelp: 'Le module est masqué et toutes ses actions sont refusées',
  accessLevelReadHelp: 'Consultation seule',
  accessLevelUserHelp: 'Consultation, création et modification',
  accessLevelManagerHelp: 'Contrôle total, y compris la suppression',

  // Role editor
  roleAccessMatrix: "Matrice d'accès",
  roleAdvancedActions: 'Actions détaillées',
  roleImplied: 'Rôles hérités',
  roleImpliedHelp: "Ce rôle accorde également tout ce qu'accordent les rôles sélectionnés.",
  roleSystemBadge: 'Rôle système',
  roleSystemLocked:
    'Rôle système : le nom ne peut pas être modifié et le rôle ne peut pas être supprimé.',
  roleSuperAdminHelp:
    'Contourne toutes les vérifications de permissions. À réserver aux administrateurs.',
  roleEffectivePermissions: 'Permissions effectives',
  roleInheritedFrom: 'Hérité de {role}',
  roleNoModulesGranted: 'Aucun module accordé',
  roleModulesGranted: '{count} module(s) accordé(s)',
  roleSyncCatalogue: 'Synchroniser le catalogue',
  roleSyncCatalogueDone: 'Catalogue des permissions synchronisé',
  roleCycleError: 'Cette dépendance créerait un cycle dans la hiérarchie des rôles',

  // User ↔ roles
  userRoles: 'Rôles',
  userRolesHelp: "Un utilisateur peut cumuler plusieurs rôles ; ses droits sont l'union de tous.",
  userNoRoles: 'Aucun rôle attribué',
  userRolesAssigned: '{count} rôle(s)',
  userSelfLockout: 'Vous ne pouvez pas retirer votre propre rôle administrateur',

  // Categories
  accessCategory_general: 'Général',
  accessCategory_sales: 'Ventes',
  accessCategory_purchases: 'Achats',
  accessCategory_accounting: 'Comptabilité',
  accessCategory_catalog: 'Catalogue',
  accessCategory_contacts: 'Contacts',
  accessCategory_inventory: 'Stock',
  accessCategory_delivery: 'Livraison',
  accessCategory_reporting: 'Rapports',
  accessCategory_tools: 'Outils',
  accessCategory_settings: 'Administration',

  // Modules
  accessModule_dashboard: 'Tableau de bord',
  accessModule_orders: 'Commandes',
  accessModule_quotes: 'Devis',
  accessModule_pos: 'Point de vente',
  accessModule_caisse: 'Caisse',
  accessModule_invoices: 'Factures clients',
  accessModule_payments: 'Paiements',
  accessModule_products: 'Produits',
  accessModule_categories: 'Catégories',
  accessModule_brands: 'Marques',
  accessModule_partners: 'Clients & Fournisseurs',
  accessModule_stock: 'Stock',
  accessModule_warehouses: 'Entrepôts',
  accessModule_uom: 'Unités de mesure',
  accessModule_delivery: 'Livraison',
  accessModule_drive: 'Drive',
  accessModule_images: 'Images',
  accessModule_documents: 'Génération de documents',
  accessModule_bulk: 'Opérations en masse',
  accessModule_notifications: 'Notifications',
  accessModule_configurations: 'Paramètres',
  accessModule_sequences: 'Séquences de documents',
  accessModule_printers: 'Imprimantes',
  accessModule_users: 'Utilisateurs',
  accessModule_roles: 'Rôles & Permissions',
  accessModule_reports_sales: 'Rapports de ventes',
  accessModule_reports_purchases: "Rapports d'achats",
  accessModule_reports_invoices: 'Rapports de facturation',
  accessModule_reports_payments: 'Rapports de paiements',
  accessModule_reports_clients: 'Rapports clients',
  accessModule_reports_suppliers: 'Rapports fournisseurs',
  accessModule_reports_products: 'Rapports produits',
  accessModule_reports_stock: 'Rapports de stock',

  // Actions
  accessAction_view: 'Consulter',
  accessAction_create: 'Créer',
  accessAction_edit: 'Modifier',
  accessAction_delete: 'Supprimer',
  accessAction_export: 'Exporter',
  accessAction_import: 'Importer',
  accessAction_validate: 'Valider',
  accessAction_cancel: 'Annuler',
  accessAction_convert: 'Convertir',
  accessAction_adjust: 'Ajuster',
  accessAction_transfer: 'Transférer',
  accessAction_assign: 'Affecter',
  accessAction_upload: 'Téléverser',
  accessAction_share: 'Partager',
  accessAction_send: 'Envoyer',
  accessAction_manage: 'Administrer',
  accessAction_use: 'Utiliser',
  accessAction_discount: 'Accorder des remises',
  accessAction_refund: 'Rembourser',
  accessAction_generate: 'Générer',
  accessAction_print: 'Imprimer',
  accessAction_open: 'Ouvrir une session',
  accessAction_close: 'Clôturer une session',

  // Preset role names
  accessRole_administrator: 'Administrateur',
  accessRole_sales_read: 'Ventes — Lecture',
  accessRole_sales_user: 'Ventes — Utilisateur',
  accessRole_sales_manager: 'Ventes — Responsable',
  accessRole_purchase_user: 'Achats — Utilisateur',
  accessRole_purchase_manager: 'Achats — Responsable',
  accessRole_accounting_user: 'Comptabilité — Utilisateur',
  accessRole_accounting_manager: 'Comptabilité — Responsable',
  accessRole_inventory_user: 'Stock — Utilisateur',
  accessRole_inventory_manager: 'Stock — Responsable',
  accessRole_pos_operator: 'Opérateur de caisse',
  accessRole_delivery_manager: 'Responsable livraison',
  accessRole_readonly: 'Lecture seule',

  // ─── Roles page ───────────────────────────────────────────
  rolesDescription: 'Définissez les rôles et ce que chacun peut faire dans chaque module',
  permissionsCount: 'Permissions',
  cannotDeleteSuperAdmin: 'Le rôle administrateur ne peut pas être supprimé',
  rolesCountLabel: 'rôles',
  roleCountLabel: 'rôle',
  noRolesFound: 'Aucun rôle trouvé',
  rolePermissionsShort: '{count} perm.',
  confirmDeleteRolesPlural: 'Supprimer {count} rôles ?',
  permissionsMatrix: "Matrice d'accès",
  module: 'Module',

  // ─── Module descriptions ──────────────────────────────────
  accessModuleDesc_dashboard: "Tableau de bord d'accueil et statistiques clés",
  accessModuleDesc_orders: 'Commandes clients et leurs lignes de paiement',
  accessModuleDesc_quotes: "Devis de vente et demandes de prix d'achat",
  accessModuleDesc_pos: 'Terminal de point de vente',
  accessModuleDesc_caisse: 'Sessions de caisse et rapprochement',
  accessModuleDesc_invoices: 'Factures de vente et avoirs',
  accessModuleDesc_payments: 'Paiements clients et fournisseurs',
  accessModuleDesc_products: 'Catalogue produits, tarifs et variantes',
  accessModuleDesc_categories: 'Catégories de produits',
  accessModuleDesc_brands: 'Marques de produits',
  accessModuleDesc_partners: 'Fiches partenaires, adresses et contacts',
  accessModuleDesc_stock: 'Niveaux de stock, mouvements et ajustements',
  accessModuleDesc_warehouses: 'Entrepôts et emplacements de stockage',
  accessModuleDesc_uom: 'Unités de mesure et conversions',
  accessModuleDesc_delivery: 'Livreurs, tournées et bons de livraison',
  accessModuleDesc_drive: 'Stockage documentaire partagé',
  accessModuleDesc_images: 'Bibliothèque d’images des produits et documents',
  accessModuleDesc_documents: 'Génération PDF des devis, commandes et factures',
  accessModuleDesc_bulk: 'Import et export en masse entre modules',
  accessModuleDesc_notifications: "Notifications dans l'application et modèles",
  accessModuleDesc_configurations: 'Paramètres société, taxes, devises et conditions de paiement',
  accessModuleDesc_sequences: 'Séquences de numérotation de chaque type de document',
  accessModuleDesc_printers: "Imprimantes et travaux d'impression",
  accessModuleDesc_users: 'Comptes utilisateurs backoffice et portail',
  accessModuleDesc_roles: "Groupes d'accès, permissions et attribution des rôles",
  accessModuleDesc_reports_sales: 'Journaux de ventes et analyse du chiffre d’affaires',
  accessModuleDesc_reports_purchases: 'Journaux d’achats et dépenses fournisseurs',
  accessModuleDesc_reports_invoices: 'Balance âgée, encours et TVA',
  accessModuleDesc_reports_payments: 'Trésorerie, flux et modes de paiement',
  accessModuleDesc_reports_clients: 'Relevés clients, balance âgée et meilleurs clients',
  accessModuleDesc_reports_suppliers: 'Relevés fournisseurs et balance âgée',
  accessModuleDesc_reports_products: 'Analyse des marges et performance produits',
  accessModuleDesc_reports_stock: 'Valorisation du stock et historique des mouvements',

  // ─── Preset role descriptions ─────────────────────────────
  accessRoleDesc_administrator:
    'Accès complet à tous les modules — contourne toutes les vérifications',
  accessRoleDesc_sales_read: 'Consultation seule du pipeline commercial',
  accessRoleDesc_sales_user: 'Créer et gérer ses propres documents de vente',
  accessRoleDesc_sales_manager: 'Contrôle total des ventes, y compris suppression et rapports',
  accessRoleDesc_purchase_user: 'Émettre et suivre les commandes fournisseurs',
  accessRoleDesc_purchase_manager: 'Contrôle total des achats et des rapports fournisseurs',
  accessRoleDesc_accounting_user: 'Saisir les factures et les paiements',
  accessRoleDesc_accounting_manager:
    'Valider et annuler les documents comptables, gérer la numérotation et les paramètres',
  accessRoleDesc_inventory_user: 'Gérer les mouvements de stock quotidiens',
  accessRoleDesc_inventory_manager: 'Contrôle total du stock, du catalogue et des entrepôts',
  accessRoleDesc_pos_operator: 'Utiliser le point de vente et la caisse',
  accessRoleDesc_delivery_manager: 'Planifier les tournées et affecter les livraisons',
  accessRoleDesc_readonly: 'Consultation seule de tous les modules',
};
