export default {
  // App & Branding
  appName: 'Morocom',
  adminBackoffice: 'Backoffice Admin',

  // Navigation
  dashboard: 'Tableau de bord',
  welcomeBack: 'Bon retour',
  welcome: 'Bienvenue',
  goodMorning: 'Bonjour',
  goodAfternoon: 'Bon après-midi',
  goodEvening: 'Bonsoir',

  // Common Actions
  create: 'Créer',
  update: 'Mettre à jour',
  edit: 'Modifier',
  delete: 'Supprimer',
  save: 'Enregistrer',
  cancel: 'Annuler',
  close: 'Fermer',
  back: 'Retour',
  confirm: 'Confirmer',
  add: 'Ajouter',

  // Common Fields
  name: 'Nom',
  code: 'Code',
  email: 'Email',
  phone: 'Téléphone',
  phoneNumber: 'Numéro de téléphone',
  address: 'Adresse',
  status: 'Statut',
  actions: 'Actions',
  date: 'Date',
  note: 'Note',
  description: 'Description',
  details: 'Détails',
  customer: 'Client',
  channel: 'Canal',

  // Status
  active: 'Actif',
  inactive: 'Inactif',
  enabled: 'Activé',
  disabled: 'Désactivé',

  // Common Validation
  required: 'Requis',
  nameRequired: 'Le nom est requis',

  // Search & Filter
  search: 'Rechercher',

  // Pagination
  showing: 'Affichage',
  to: 'à',
  of: 'sur',
  results: 'résultats',
  perPage: 'Par page',
  first: 'Premier',
  previous: 'Précédent',
  next: 'Suivant',
  last: 'Dernier',
  pageReportTemplate: '{first} - {last} sur {totalRecords}',

  // Loading & States
  loading: 'Chargement...',
  saving: 'Enregistrement',
  deleting: 'Suppression',
  creating: 'Création',
  generating: 'Génération...',
  downloading: 'Téléchargement',
  downloaded: 'Téléchargé',
  failedToGenerate: 'Échec de génération',
  'common.loading': 'Chargement...',
  'common.saving': 'Enregistrement...',
  'common.close': 'Fermer',
  'common.cancel': 'Annuler',

  // Selection
  selected: 'sélectionné(s)',
  selectAll: 'Tout sélectionner',
  deselectAll: 'Tout désélectionner',

  // General
  items: 'articles',
  item: 'article',
  all: 'Tout',
  total: 'Total',
  reportNoDataAvailable: 'Aucune donnée disponible',

  // Currency
  currency: 'DH',
  currencyCode: 'MAD',

  // Date Filters
  today: "Aujourd'hui",
  yesterday: 'Hier',
  thisWeek: 'Cette semaine',
  thisMonth: 'Ce mois',
  thisYear: 'Cette année',
  lastWeek: 'Semaine dernière',
  lastMonth: 'Mois dernier',
  lastYear: 'Année dernière',
  selectDate: 'Sélectionner une date',
  period: 'Période',
  selectDates: 'Sélectionner les dates',
  start: 'Début',
  end: 'Fin',
  predefinedPeriod: 'Période prédéfinie',
  ok: 'OK',

  // Confirmation
  areYouSure: 'Êtes-vous sûr ?',
  actionCannotBeUndone: 'Cette action ne peut pas être annulée',

  // Dashboard
  quickAccess: 'Accès rapide',
  week: 'semaine',
  month: 'mois',
  year: 'année',
  custom: 'personnalisé',
  vsPeriod: 'vs période précédente',

  // Language Toggle
  switchToFrench: 'Changer en français',
  switchToArabic: 'التبديل للعربية',
  currentLanguageName: 'Français',

  // Error Messages
  error: 'Une erreur est survenue',
  errorPrefix: 'Erreur',
  failedToCreate: 'Échec de création',
  failedToUpdate: 'Échec de mise à jour',
  failedToDelete: 'Échec de suppression',
  useAuthError: 'useAuth doit être utilisé dans un AuthProvider',
  useLanguageError: 'useLanguage doit être utilisé dans un LanguageProvider',

  // Menu Items
  sales: 'Ventes',
  purchases: 'Achats',
  quote: 'Devis',
  deliveryNote: 'Bon de Livraison',
  salesInvoice: 'Facture de Vente',
  payments: 'Paiements',
  clients: 'Clients',
  priceRequest: 'Demande de prix',
  purchaseOrder: "Bon d'Achat",
  purchaseInvoice: "Facture d'Achat",
  suppliers: 'Fournisseurs',
  stockMovements: 'Mouvements de stock',
  inventoryAdjustments: "Ajustements d'inventaire",
  warehouses: 'Entrepôts',

  // Document Statuses
  paid: 'Payée',
  partial: 'Partielle',
  pending: 'En attente',
  overdue: 'En retard',
  unpaid: 'Impayée',
  open: 'Ouvert',
  signed: 'Signée (à facturer)',
  closed: 'Non signée (fermée)',
  invoiced: 'Facturée',
  validated: 'Validée',
  inProgress: 'En cours',
  delivered: 'Livrée',
  cancelled: 'Annulée',
  draft: 'Brouillon',
  confirmed: 'Confirmé',
  assigned: 'Assigné',
  done: 'Effectué',
  allTypes: 'Tous les types',
  allStatuses: 'Tous les statuts',

  // Image Upload
  invalidFileType: 'Type de fichier invalide. Autorisés: JPEG, PNG, WebP',
  fileSizeExceeds: 'La taille du fichier dépasse la limite de',
  uploadFailed: 'Échec du téléchargement',
  pleaseTryAgain: 'Veuillez réessayer',
  imageUploadedSuccessfully: 'Image téléchargée avec succès',
  failedToConstructImageUrl: "Impossible de construire l'URL de l'image",
  failedToRemoveImage: "Impossible de supprimer l'image",
  productPreview: 'Aperçu du produit',
  removeImage: "Supprimer l'image",

  // Dashboard
  dashboardOverview: "Vue d'ensemble de votre activité",
  revenueTrend: 'Tendance des revenus',
  last7Days: '7 derniers jours',
  ordersDistribution: 'Répartition des commandes',
  byStatus: 'Par statut',
  salesComparison: 'Comparaison des ventes',
  currentVsPrevious: 'Période actuelle vs précédente',
  currentPeriod: 'Période actuelle',
  previousPeriod: 'Période précédente',
  performanceMetrics: 'Indicateurs de performance',
  keyIndicators: 'Indicateurs clés',
  avgOrderValue: 'Valeur moyenne commande',
  customerGrowth: 'Croissance clients',
  conversionRate: 'Taux de conversion',
  recentActivity: 'Activité récente',
  latestUpdates: 'Dernières mises à jour',
  live: 'En direct',
  viewAll: 'Voir tout',
  newOrderReceived: 'Nouvelle commande reçue',
  newCustomer: 'Nouveau client',
  lowStock: 'Stock faible',
  dailyGoal: 'Objectif quotidien',
  quickActions: 'Actions rapides',
  getStartedQuickly: 'Commencez rapidement',
  newOrder: 'Nouvelle commande',
  viewOrders: 'Voir les commandes',
  ordersAwaitingProcessing: 'Commandes en attente',
  ordersInTransit: 'Commandes en transit',
  successfulDeliveries: 'Livraisons réussies',
  currentlyActive: 'Actuellement actif',
  revenue: 'Revenu',

  // Status Labels
  upToDate: 'À jour',
  pendingPayments: 'Paiements en attente',
  allPaymentsUpToDate: 'Tous les paiements sont à jour',
  invoicesIssuedPerMonth: 'Factures émises par mois',

  totalCustomers: 'Total clients',
  topProducts: 'Top produits',
  bestSellers: 'Meilleures ventes',
  ordersTimeline: 'Chronologie des commandes',
  dailyOrdersFlow: 'Flux quotidien des commandes',
  newOrders: 'Nouvelles commandes',
  secondsAgo: 'secondes',
  minutesAgo: 'min',
  hoursAgo: 'heures',
  daysAgo: 'jours',
  noRecentActivity: 'Aucune activité récente',

  // Common Actions
  validate: 'Valider',
  devalidate: 'Dévalider',
  view: 'Voir',
  deleteTitle: 'Supprimer',
  validating: 'En cours...',
  modify: 'Modifier',
  remove: 'Supprimer',
  validateDocument: 'Valider le document',
  devalidateDocument: 'Dévalider le document',

  // Months (short)
  monthJan: 'Jan',
  monthFeb: 'Fév',
  monthMar: 'Mar',
  monthApr: 'Avr',
  monthMay: 'Mai',
  monthJun: 'Jun',
  monthJul: 'Jul',
  monthAug: 'Aoû',
  monthSep: 'Sep',
  monthOct: 'Oct',
  monthNov: 'Nov',
  monthDec: 'Déc',
  monthJanuary: 'Janvier',
  monthFebruary: 'Février',
  monthMarch: 'Mars',
  monthApril: 'Avril',
  monthMayFull: 'Mai',
  monthJune: 'Juin',
  monthJuly: 'Juillet',
  monthAugust: 'Août',
  monthSeptember: 'Septembre',
  monthOctober: 'Octobre',
  monthNovember: 'Novembre',
  monthDecember: 'Décembre',

  // Preview/Download
  previewPDF: 'Aperçu PDF',
  downloadPDF: 'Télécharger PDF',
  download: 'Télécharger',
  generateLink: 'Générer le lien',

  // Confirmations
  confirmCancelMovement: 'Êtes-vous sûr de vouloir annuler ce mouvement ?',
  confirmRejectQuote: 'Voulez-vous vraiment refuser ce devis ? Il sera marqué comme fermé.',
  searchByNumberOrName: 'Rechercher par numéro ou nom...',
  manageCompanyInformation: 'Gérer les informations de votre entreprise',
  newPasswordOptional: 'Nouveau mot de passe (optionnel)',
  minCharacters: 'Min 6 caractères',
  informationSavedSuccess: 'Informations enregistrées avec succès',
  errorSaving: "Erreur lors de l'enregistrement",
  errorGeneratingPDF: 'Erreur lors de la génération du PDF',
  pdfDownloaded: 'téléchargé avec succès',
  pdfDownloadedShort: 'téléchargé',
  confirmDeletePayment:
    'Êtes-vous sûr de vouloir supprimer ce paiement ? Cette action est irréversible.',
  errorDeletingPayment: 'Erreur lors de la suppression du paiement',
  previewReceipt: 'Aperçu Reçu',
  previewDeliveryNote: 'Aperçu Bon',
  iosInstallHint:
    'Pour installer sur iOS, appuyez sur Partager et choisissez "Ajouter à l\'écran d\'accueil".',
  deleteError: 'Erreur de suppression',
  exportSuccess: 'Export réussi',
  exportError: "Erreur lors de l'exportation",
  templateDownloaded: 'Modèle téléchargé avec succès',
  templateDownloadError: 'Erreur lors du téléchargement du modèle',
  importInProgress: 'Import en cours...',
  importSuccess: 'Import réussi: {{created}} créés, {{updated}} mis à jour',
  importPartial:
    'Import terminé avec des erreurs: {{created}} créés, {{updated}} mis à jour, {{failed}} échoués',
  importError: "Erreur lors de l'import",
  confirmBulkDelete:
    'Êtes-vous sûr de vouloir supprimer {{count}} élément(s) sélectionné(s) ? Cette action est irréversible.',
  deleteProducts: 'Supprimer les produits',
  unsupportedDocumentType: 'Type de document non pris en charge',
  confirmDeleteCategory: 'Êtes-vous sûr de vouloir supprimer "{{name}}" ?',
  enterYourName: 'Veuillez entrer votre nom',
  errorSigningQuote: 'Erreur lors de la signature du devis',
  confirmRejectQuoteMessage: 'Voulez-vous vraiment refuser ce devis ? Il sera marqué comme fermé.',
  rejectLabel: 'Refuser',
  errorRejectingQuote: 'Erreur lors du refus du devis',
  failedToGenerateCode: 'Échec de génération du code produit unique',
  newCodeGenerated: 'Nouveau code produit unique généré',
  failedToGenerateCodeRetry: 'Échec de génération du code unique. Veuillez réessayer.',
  productCreatedSuccess: 'Produit créé avec succès',
  failedToCreateProduct: 'Échec de création du produit',
  failedToUpdateProduct: 'Échec de mise à jour du produit',
  failedToCorrectStock: 'Échec de correction du stock',
  failedToTransferStock: 'Échec de transfert du stock',
  errorCreating: 'Erreur lors de la création',
  failedToCreateWarehouse: "Échec de création de l'entrepôt",
  failedToUpdateWarehouse: "Échec de mise à jour de l'entrepôt",
  failedToDeleteWarehouse: "Échec de suppression de l'entrepôt",
  deleteWarehouseTitle: "Supprimer l'entrepôt",
  confirmDeleteWarehouse:
    'Êtes-vous sûr de vouloir supprimer cet entrepôt ? Cette action est irréversible.',
  noWarehousesFound: 'Aucun entrepôt trouvé',
  noAddress: 'Aucune adresse',
  createFirstWarehouse: 'Créez votre premier entrepôt pour commencer',
  tryDifferentSearch: 'Essayez une recherche différente',
  errorCreatingDocument: 'Erreur lors de la création du document',
  errorUpdatingDocument: 'Erreur lors de la mise à jour du document',
  loadingQuote: 'Chargement du devis...',
  errorLoadingQuote: 'Erreur lors du chargement du devis',
  quoteNotFound: 'Devis introuvable',
  no: 'Non',

  // Document action bar
  moreActions: "Plus d'actions",
  confirmDeleteDocument:
    'Êtes-vous sûr de vouloir supprimer ce document ? Cette action est irréversible.',
  documentDeleted: 'Document supprimé avec succès',

  // Accessibility
  refresh: 'Actualiser',
  moreOptions: "Plus d'options",
  settings: 'Paramètres',
  // General
  noItems: 'Aucun élément',
  completed: 'Terminé',
  type: 'Type',

  // Search & empty states
  noResults: 'Aucun résultat trouvé',
  resetFilters: 'Réinitialiser les filtres',

  // Common fields (extended)
  reference: 'Référence',
  city: 'Ville',
  zipCode: 'Code postal',
  select: 'Sélectionner',
  qty: 'Qté',
  totalWithTax: 'Total TTC',

  // Common actions (extended)
  import: 'Importer',
  export: 'Exporter',
  print: 'Imprimer',
  share: 'Partager',
  copy: 'Copier',
  copied: 'Copié !',
  copyUrl: "Copier l'URL",
  new: 'Nouveau',

  // Upload
  imageLoadError: "Erreur de chargement de l'image",
  clickToChange: "Cliquer pour changer l'image",
  clickOrDrag: 'Cliquer ou glisser-déposer',

  // Share
  shareLinkGenerated: 'Lien de partage généré',
  shareLinkError: 'Erreur lors de la génération du lien',
  linkRevoked: 'Lien révoqué avec succès',
  linkRevocationError: 'Erreur lors de la révocation du lien',

  // Paginator
  paginatorReport: '{first}-{last} sur {totalRecords}',

  // Navigation (mobile + sidebar)
  navBoard: 'Board',
  navInventory: 'Inventaire',
  navMore: 'Plus',
  navExpand: 'Développer',
  navCollapse: 'Réduire',
  navTeam: 'Équipe',
  navPos: 'Point de vente',
  analytics: 'Analytiques & Rapports',
  analyticsPageTitle: 'Analytiques & Rapports',
  analyticsPageSubtitle: 'Vue d’ensemble de tous les rapports disponibles',
  analyticsLoading: 'Chargement du rapport…',
  analyticsErrorTitle: 'Erreur lors du chargement',
  analyticsSectionChart: 'Graphique',
  analyticsSectionTable: 'Données détaillées',
  analyticsExportExcel: 'Excel',
  analyticsExportPdf: 'PDF',
  analyticsPdfGenerating: 'Génération…',
  analyticsPdfError: 'Échec du PDF',
  analyticsPdfFooterNote: 'Document confidentiel — usage interne.',
  analyticsPdfPeriod: 'Période',
  analyticsPdfEmpty: 'Aucune donnée pour les critères sélectionnés.',
  analyticsFilterPeriod: 'Période',
  analyticsFilterChoosePeriod: 'Choisir une période',
  analyticsPresetToday: "Aujourd'hui",
  analyticsPresetThisWeek: 'Cette semaine',
  analyticsPresetThisMonth: 'Ce mois',
  analyticsPresetLastMonth: 'Mois dernier',
  analyticsPresetThisQuarter: 'Ce trimestre',
  analyticsPresetThisYear: 'Cette année',
  analyticsPresetCustom: 'Personnalisé',
  analyticsDomainSales: 'Ventes',
  analyticsDomainPurchases: 'Achats',
  analyticsDomainInvoices: 'Factures',
  analyticsDomainPayments: 'Paiements',
  analyticsDomainClients: 'Clients',
  analyticsDomainSuppliers: 'Fournisseurs',
  analyticsDomainStock: 'Stock',
  analyticsOutstandingInvoicesInvoiceNumber: 'N° Facture',
  analyticsOutstandingInvoicesPartner: 'Client / Fournisseur',
  analyticsOutstandingInvoicesType: 'Type',
  analyticsOutstandingInvoicesDueDate: 'Échéance',
  analyticsOutstandingInvoicesAmountDue: 'Montant dû (MAD)',
  analyticsOutstandingInvoicesDaysOverdue: 'Jours de retard',
  analyticsOutstandingInvoicesTotalDue: 'Total impayé',
  analyticsOutstandingInvoicesInvoiceCount: 'Nb factures',
  analyticsInOutFlowPeriod: 'Période',
  analyticsInOutFlowInflow: 'Entrées (MAD)',
  analyticsInOutFlowOutflow: 'Sorties (MAD)',
  analyticsInOutFlowNet: 'Solde net (MAD)',
  analyticsInOutFlowTotalInflow: 'Total entrées',
  analyticsInOutFlowTotalOutflow: 'Total sorties',
  analyticsInOutFlowNetBalance: 'Solde net',
  analyticsProductPerformanceProduct: 'Produit',
  analyticsProductPerformanceQuantitySold: 'Qté vendue',
  analyticsProductPerformanceRevenue: 'CA (MAD)',
  analyticsProductPerformanceOrderCount: 'Nb commandes',
  analyticsProductPerformanceSoldProducts: 'Produits vendus',
  analyticsProductPerformanceTotalRevenue: 'CA total produits',
  analyticsSalesRevenueOrdersCount: 'Nb commandes',
  analyticsSalesRevenueAverageBasket: 'Panier moyen',
  analyticsSalesTopProductsProduct: 'Produit',
  analyticsSalesTopProductsQuantitySold: 'Qté vendue',
  analyticsSalesTopProductsRevenue: 'CA (MAD)',
  analyticsSalesTopProductsUniqueProducts: 'Produits uniques vendus',
  analyticsSalesTopProductsTotalQuantity: 'Quantité totale',
  analyticsDomainProducts: 'Produits',
  analyticsReportCountSingular: '{count} rapport',
  analyticsReportCountPlural: '{count} rapports',
  analyticsSalesRevenueTitle: 'Chiffre d’affaires',
  analyticsSalesRevenueSubtitle: 'Évolution du revenu par période',
  analyticsSalesRevenueDescription: 'Revenu par période avec évolution',
  analyticsTopProductsTitle: 'Top produits vendus',
  analyticsTopProductsSubtitle: 'Classement des produits les plus performants',
  analyticsTopProductsDescription: 'Classement des produits les plus performants',
  analyticsSalesByCustomerTitle: 'Ventes par client',
  analyticsSalesByCustomerSubtitle: 'Montant total commandé par client',
  analyticsSalesByCustomerDescription: 'Montant total commandé par client',
  analyticsSalesByCategoryTitle: 'Ventes par catégorie',
  analyticsSalesByCategorySubtitle: 'Répartition du chiffre d’affaires par catégorie',
  analyticsSalesByCategoryDescription: 'Répartition du chiffre d’affaires par catégorie',
  analyticsSalesByPosTitle: 'Ventes par caisse',
  analyticsSalesByPosSubtitle: 'Performance par point de vente',
  analyticsSalesByPosDescription: 'Performance par point de vente',
  analyticsPurchasesByPeriodTitle: 'Achats par période',
  analyticsPurchasesByPeriodSubtitle: 'Évolution des dépenses fournisseurs',
  analyticsPurchasesByPeriodDescription: 'Évolution des dépenses fournisseurs',
  analyticsTopSuppliersTitle: 'Top fournisseurs',
  analyticsTopSuppliersSubtitle: 'Fournisseurs avec le plus de commandes',
  analyticsTopSuppliersDescription: 'Fournisseurs avec le plus de commandes',
  analyticsPurchasesByProductTitle: 'Achats par produit',
  analyticsPurchasesByProductSubtitle: 'Produits les plus achetés',
  analyticsPurchasesByProductDescription: 'Produits les plus achetés',
  analyticsInvoicesJournalVenteTitle: 'Journal de vente',
  analyticsInvoicesJournalVenteSubtitle: 'Toutes les factures clients',
  analyticsInvoicesJournalVenteDescription: 'Toutes les factures clients',
  analyticsInvoicesJournalAchatTitle: 'Journal d’achat',
  analyticsInvoicesJournalAchatSubtitle: 'Toutes les factures fournisseurs',
  analyticsInvoicesJournalAchatDescription: 'Toutes les factures fournisseurs',
  analyticsTvaSummaryTitle: 'Bilan TVA',
  analyticsTvaSummarySubtitle: 'Déclaration TVA par taux — TVA collectée vs déductible',
  analyticsTvaSummaryDescription: 'Déclaration TVA par taux — TVA collectée vs déductible',
  analyticsOutstandingInvoicesTitle: 'Factures impayées',
  analyticsOutstandingInvoicesSubtitle: 'Factures en attente de règlement',
  analyticsOutstandingInvoicesDescription: 'Factures en attente de règlement',
  analyticsInvoiceAgingTitle: 'Balance âgée',
  analyticsInvoiceAgingSubtitle: 'Retards de paiement par tranche d’ancienneté',
  analyticsInvoiceAgingDescription: 'Retards de paiement par tranche d’ancienneté',
  analyticsCashflowTitle: 'Flux de trésorerie',
  analyticsCashflowSubtitle: 'Entrées et sorties cumulées par période',
  analyticsCashflowDescription: 'Entrées et sorties cumulées par période',
  analyticsPaymentsByMethodTitle: 'Paiements par mode',
  analyticsPaymentsByMethodSubtitle: 'Répartition espèces / virement / chèque',
  analyticsPaymentsByMethodDescription: 'Répartition espèces / virement / chèque',
  analyticsInOutFlowTitle: 'Entrées vs Sorties',
  analyticsInOutFlowSubtitle: 'Comparaison encaissements et décaissements',
  analyticsInOutFlowDescription: 'Comparaison encaissements et décaissements',
  analyticsTopClientsTitle: 'Top clients',
  analyticsTopClientsSubtitle: 'Meilleurs clients par chiffre d’affaires',
  analyticsTopClientsDescription: 'Meilleurs clients par chiffre d’affaires',
  analyticsClientAgingTitle: 'Balance âgée clients',
  analyticsClientAgingSubtitle: 'Créances clients par ancienneté',
  analyticsClientAgingDescription: 'Créances clients par ancienneté',
  analyticsInactiveClientsTitle: 'Clients inactifs',
  analyticsInactiveClientsSubtitle: 'Clients sans commande depuis plus de 90 jours',
  analyticsInactiveClientsDescription: 'Clients sans commande depuis plus de 90 jours',
  analyticsClientStatementTitle: 'Relevé de compte client',
  analyticsClientStatementSubtitle: 'Historique complet — commandes, factures et paiements',
  analyticsClientStatementDescription: 'Historique complet — commandes, factures et paiements',
  analyticsSupplierAgingTitle: 'Balance âgée fournisseurs',
  analyticsSupplierAgingSubtitle: 'Dettes fournisseurs par ancienneté',
  analyticsSupplierAgingDescription: 'Dettes fournisseurs par ancienneté',
  analyticsSupplierStatementTitle: 'Relevé de compte fournisseur',
  analyticsSupplierStatementSubtitle: 'Historique complet — commandes, factures et paiements',
  analyticsSupplierStatementDescription: 'Historique complet — commandes, factures et paiements',
  analyticsStockValuationTitle: 'Valorisation du stock',
  analyticsStockValuationSubtitle: 'Valeur totale du stock par produit',
  analyticsStockValuationDescription: 'Valeur totale du stock par produit',
  analyticsLowStockTitle: 'Stock faible',
  analyticsLowStockSubtitle: 'Produits sous le seuil d’alerte — réapprovisionner en urgence',
  analyticsLowStockDescription: 'Produits sous le seuil d’alerte — réapprovisionner en urgence',
  analyticsStockMovementsTitle: 'Journal des mouvements',
  analyticsStockMovementsSubtitle: 'Historique entrées / sorties / transferts de stock',
  analyticsStockMovementsDescription: 'Historique entrées / sorties / transferts de stock',
  analyticsSlowDeadStockTitle: 'Stock dormant',
  analyticsSlowDeadStockSubtitle: 'Produits sans mouvement depuis plus de 90 jours',
  analyticsSlowDeadStockDescription: 'Produits sans mouvement depuis plus de 90 jours',
  analyticsStockByWarehouseTitle: 'Stock par entrepôt',
  analyticsStockByWarehouseSubtitle: 'Répartition du stock par dépôt',
  analyticsStockByWarehouseDescription: 'Répartition du stock par dépôt',
  analyticsProductPerformanceTitle: 'Performance produits',
  analyticsProductPerformanceSubtitle: 'Quantités vendues et CA par produit',
  analyticsProductPerformanceDescription: 'Quantités vendues et CA par produit',
  analyticsMarginAnalysisTitle: 'Analyse des marges',
  analyticsMarginAnalysisSubtitle: 'Marge brute par produit — CA vs coût d’achat',
  analyticsMarginAnalysisDescription: 'Marge brute par produit — CA vs coût d’achat',
  analyticsNeverSoldProductsTitle: 'Produits jamais vendus',
  analyticsNeverSoldProductsSubtitle: 'Articles actifs sans aucune vente enregistrée',
  analyticsNeverSoldProductsDescription: 'Articles actifs sans aucune vente enregistrée',
  rolesPermissions: 'Rôles & Permissions',

  // Stock / inventory
  negativeStock: 'Stock négatif',
  zeroStock: 'Stock nul',
  positiveStock: 'Stock positif',
  inStock: 'En stock',

  // Documents
  shareLink: 'Lien de partage',
  preview: 'Aperçu',
  linkExpires: 'Ce lien expire le',
  shareQuote: 'Partager le devis',
  shareInvoice: 'Partager la facture',
  shareBL: 'Partager le bon',
  sendWhatsApp: 'Envoyer par WhatsApp',
  revokeLink: 'Révoquer le lien',
  backToPOS: 'Retour au point de vente',
  orderSummary: 'Récapitulatif de commande',
  lines: 'Lignes',

  // ── User Profile Menu ──
  myProfile: 'Mon Profil',
  userSettings: 'Paramètres',
  profileAndAccount: 'Profil & Compte',
  editProfile: 'Modifier le profil',
  profileUpdatedSuccess: 'Profil mis à jour avec succès',
  profileUpdateError: 'Erreur lors de la mise à jour du profil',
  administrator: 'Administrateur',
  fullName: 'Nom complet',
  currentPassword: 'Mot de passe actuel',
  newPassword: 'Nouveau mot de passe',
  confirmPassword: 'Confirmer le mot de passe',
  passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
  leaveBlankToKeep: 'Laisser vide pour ne pas changer',
  accountInfo: 'Informations du compte',
  securitySection: 'Sécurité',
  changePassword: 'Changer le mot de passe',

  // ── User Settings Modal ──
  languageAndRegion: 'Langue & Région',
  selectLanguage: 'Sélectionner la langue',
  french: 'Français',
  arabic: 'Arabe',
  languageChanged: 'Langue modifiée avec succès',
  notificationPreferences: 'Préférences de notifications',
  notifAll: 'Toutes les notifications',
  notifOrders: 'Nouvelles commandes',
  notifPayments: 'Paiements & encaissements',
  notifStock: 'Alertes de stock',
  notifSystem: 'Notifications système',
  notifDelivery: 'Mises à jour de livraison',
  notifMarketing: 'Offres & actualités',
  professionalSettings: 'Paramètres professionnels',
  compactMode: 'Mode compact',
  compactModeDesc: "Réduire l'espacement pour afficher plus de contenu",
  autoSave: 'Sauvegarde automatique',
  autoSaveDesc: 'Sauvegarder automatiquement les brouillons',
  showTutorials: 'Afficher les tutoriels',
  showTutorialsDesc: 'Afficher les guides et astuces interactifs',
  defaultCurrency: 'Devise par défaut',
  dateFormat: 'Format de date',
  settingsSaved: 'Paramètres enregistrés',
  install: 'Installer',

  // Order payments
  paidAmount: 'Montant payé',
  remainingAmount: 'Reste à payer',
  addPayment: 'Ajouter un paiement',
  pay: 'Payer',
  paymentType: 'Mode de paiement',
  paymentDate: 'Date de paiement',
  paymentHistory: 'Historique des paiements',
  deletePayment: 'Supprimer le paiement',
  optional: 'Optionnel',
  notes: 'Notes',

  // Dates
  createdAt: 'Créé le',
  updatedAt: 'Mis à jour le',

  // ── Deletion guard error codes (returned by API) ─────────────────────────
  deletionBlocked: 'Suppression impossible',
  PRODUCT_IN_INVOICES: 'Ce produit est utilisé dans des factures et ne peut pas être supprimé.',
  PRODUCT_IN_ORDERS: 'Ce produit est utilisé dans des commandes et ne peut pas être supprimé.',
  PRODUCT_IN_QUOTES: 'Ce produit est utilisé dans des devis et ne peut pas être supprimé.',
  ORDER_VALIDATED: 'Cette commande est validée. Veuillez la dévalider avant de la supprimer.',
  ORDER_HAS_PAYMENTS: 'Cette commande a des paiements associés et ne peut pas être supprimée.',
  INVOICE_VALIDATED: 'Cette facture est validée. Veuillez la dévalider avant de la supprimer.',
  INVOICE_HAS_PAYMENTS: 'Cette facture a des paiements associés et ne peut pas être supprimée.',
  QUOTE_VALIDATED: 'Ce devis est validé. Veuillez le dévalider avant de le supprimer.',
  QUOTE_CONVERTED_TO_INVOICE: 'Ce devis a été converti en facture et ne peut pas être supprimé.',
  PARTNER_HAS_DOCUMENTS:
    'Ce partenaire est associé à des commandes, factures ou devis et ne peut pas être supprimé.',
  DELIVERY_PERSON_HAS_ORDERS:
    'Ce livreur est assigné à des commandes actives et ne peut pas être supprimé.',
  CATEGORY_HAS_CHILDREN:
    'Cette catégorie contient des sous-catégories et ne peut pas être supprimée.',
  CATEGORY_HAS_PRODUCTS:
    'Cette catégorie est assignée à des produits et ne peut pas être supprimée.',
  WAREHOUSE_HAS_PRODUCTS: 'Cet entrepôt est assigné à des produits et ne peut pas être supprimé.',
  BRAND_HAS_PRODUCTS: 'Cette marque est assignée à des produits et ne peut pas être supprimée.',
  BRAND_NAME_EXISTS: 'Une marque portant ce nom existe déjà.',
  // --- Analytics & reports: generic ledger labels ---
  debit: 'Débit',
  credit: 'Crédit',
  balance: 'Solde',
  lastOrderDate: 'Dernière commande',

  // --- Analytics & reports: aging buckets ---
  analyticsAgingCurrent: 'Non échu',
  analyticsAging1To30: '1-30 j',
  analyticsAging31To60: '31-60 j',
  analyticsAging61To90: '61-90 j',
  analyticsAgingOver90: '+ 90 j',
  analyticsInvoiceAgingPartner: 'Client / Fournisseur',

  // --- Analytics & reports: invoice journals ---
  analyticsJournalInvoiceNumber: 'N° Facture',
  analyticsJournalHt: 'HT',
  analyticsJournalTva: 'TVA',
  analyticsJournalTtc: 'TTC',

  // --- Analytics & reports: TVA summary ---
  analyticsTvaRate: 'Taux TVA (%)',
  analyticsBaseHt: 'Base HT',
  analyticsCollectedTva: 'TVA collectée',
  analyticsDeductibleTva: 'TVA déductible',
  analyticsNetDueTva: 'TVA nette due',

  // --- Analytics & reports: payments ---
  analyticsCashflowInflow: 'Entrées',
  analyticsCashflowOutflow: 'Sorties',
  analyticsCashflowNet: 'Solde net',
  analyticsPaymentMethod: 'Mode de paiement',
  analyticsPaymentTransactionsCount: 'Nb transactions',

  // --- Analytics & reports: clients ---
  analyticsInactiveClientsInactiveDays: 'Jours d’inactivité',
  analyticsInactiveClientsTotalOrders: 'Total commandes',
  analyticsTopClientsOrderCount: 'Nb commandes',
  analyticsTopClientsRevenue: 'CA',
  analyticsTopClientsLastOrderDate: 'Dernière commande',

  // --- Analytics & reports: suppliers ---
  analyticsTopSuppliersOrderCount: 'Nb commandes',
  analyticsTopSuppliersTotalAmount: 'Montant total',

  // --- Analytics & reports: purchases ---
  analyticsPurchasesAmount: 'Montant',
  analyticsPurchasesOrderCount: 'Nb commandes',
  analyticsPurchasesProduct: 'Produit',
  analyticsPurchasesQuantityBought: 'Qté achetée',

  // --- Analytics & reports: sales ---
  analyticsSalesByPosChannel: 'Canal',
  analyticsSalesOrderCount: 'Nb commandes',
  analyticsSalesQuantitySold: 'Qté vendue',
  analyticsSalesRevenueAmount: 'CA',

  // --- Analytics & reports: products ---
  analyticsMarginQuantitySold: 'Qté vendue',
  analyticsMarginRevenue: 'CA',
  analyticsMarginCost: 'Coût',
  analyticsMarginGrossMargin: 'Marge brute',
  analyticsMarginPercent: 'Marge (%)',
  analyticsNeverSoldPrice: 'Prix',

  // --- Analytics & reports: stock ---
  analyticsSku: 'SKU',
  analyticsStockProduct: 'Produit',
  analyticsStockQuantity: 'Quantité',
  analyticsStockCurrentQuantity: 'Stock actuel',
  analyticsStockQuantityInStock: 'Qté en stock',
  analyticsStockAlertThreshold: 'Seuil d’alerte',
  analyticsStockWarehouse: 'Entrepôt',
  analyticsStockSource: 'Source',
  analyticsStockDestination: 'Destination',
  analyticsStockUnitCost: 'Coût unitaire',
  analyticsStockTotalValue: 'Valeur totale',
  analyticsStockImmobilizedValue: 'Valeur immobilisée',
  analyticsStockReferenceCount: 'Nb références',
  analyticsStockTotalQuantity: 'Qté totale',
  analyticsStockAvailableQuantity: 'Qté disponible',
  analyticsStockValuationTotalValue: 'Valeur totale du stock',
  analyticsStockValuationReferenceCount: 'Nb références',

  // --- Analytics & reports: export ---
  analyticsDownloadError: 'Erreur lors du téléchargement',

  // ─── Blocked / tenant status screens ──────────────────────
  blockedSuspendedTitle: 'Compte suspendu',
  blockedSuspendedHeading: 'Votre compte a été suspendu',
  blockedSuspendedBody:
    "L'accès à cet espace de travail a été temporairement suspendu par l'administrateur de la plateforme. Toutes vos données sont conservées en sécurité.",
  blockedDisabledTitle: 'Compte désactivé',
  blockedDisabledHeading: 'Votre compte a été désactivé',
  blockedExpiredTitle: 'Abonnement expiré',
  blockedExpiredHeading: 'Votre abonnement a expiré',
  blockedTrialTitle: "Période d'essai terminée",
  blockedTrialHeading: "Votre période d'essai est terminée",
  blockedTrialBody:
    "Votre période d'essai est arrivée à son terme. Passez à une offre payante pour continuer à utiliser Morocom sans interruption.",
  trialEndsToday:
    "Votre essai se termine aujourd'hui ! Contactez-nous pour activer votre abonnement.",

  // ─── Empty states & search ────────────────────────────────
  noResultsFound: 'Aucun résultat trouvé',
  noResultsHintFilters: 'Essayez de modifier votre recherche ou vos filtres.',
  clearSearch: 'Effacer la recherche',

  // ─── AI assistant ─────────────────────────────────────────
  aiAssistant: 'Assistant IA',
  aiCloseEsc: 'Fermer (ÉCHAP)',
  aiCancelEsc: 'Annuler (ÉCHAP)',
  aiErrorOccurred: "Une erreur s'est produite",
  aiAskAnything: 'Posez-moi une question...',
  aiWaitingResponse: 'En attente de la réponse...',

  // ─── Virtual keyboard ─────────────────────────────────────
  keyboardShow: 'Afficher le clavier',
  keyboardHide: 'Masquer le clavier',
  keyboardClose: 'Fermer le clavier',
  keyboardVirtual: 'Clavier virtuel',
  keyboardAccented: 'Caractères accentués',
  keyboardLightMode: 'Passer en mode clair',
  keyboardDarkMode: 'Passer en mode sombre',
  mobileNavigation: 'Navigation mobile',
  blockedDisabledBody:
    "Cet espace de travail a été désactivé par l'administrateur de la plateforme. Contactez-le pour le réactiver.",
  blockedExpiredBody:
    "Votre offre a expiré et l'accès a été suspendu. Renouvelez votre abonnement pour rétablir l'accès complet de votre équipe.",
  records: 'enregistrements',
  searchPlaceholderDefault: 'Rechercher…',
};
