export default {
  // App & Branding
  appName: 'Orderium',
  adminBackoffice: 'Backoffice Admin',
  
  // Navigation
  dashboard: 'Tableau de bord',
  welcomeBack: 'Bon retour',
  welcome: 'Bienvenue',
  
  // Common Actions
  create: 'Créer',
  update: 'Mettre à jour',
  edit: 'Modifier',
  delete: 'Supprimer',
  save: 'Enregistrer',
  cancel: 'Annuler',
  close: 'Fermer',
  back: 'Retour',
  confirm: 'Confirmer',
  add: 'Ajouter',
  
  // Common Fields
  name: 'Nom',
  email: 'Email',
  phone: 'Téléphone',
  phoneNumber: 'Numéro de téléphone',
  address: 'Adresse',
  status: 'Statut',
  actions: 'Actions',
  date: 'Date',
  note: 'Note',
  description: 'Description',
  details: 'Détails',
  customer: 'Client',
  
  // Status
  active: 'Actif',
  inactive: 'Inactif',
  enabled: 'Activé',
  disabled: 'Désactivé',
  
  // Common Validation
  required: 'Requis',
  nameRequired: 'Le nom est requis',
  
  // Search & Filter
  search: 'Rechercher',
  
  // Pagination
  showing: 'Affichage',
  to: 'à',
  of: 'sur',
  results: 'résultats',
  perPage: 'Par page',
  first: 'Premier',
  previous: 'Précédent',
  next: 'Suivant',
  last: 'Dernier',
  
  // Loading & States
  loading: 'Chargement...',
  saving: 'Enregistrement',
  deleting: 'Suppression',
  creating: 'Création',
  generating: 'Génération...',
  downloading: 'Téléchargement',
  downloaded: 'Téléchargé',
  failedToGenerate: 'Échec de génération',
  'common.loading': 'Chargement...',
  'common.saving': 'Enregistrement...',
  'common.close': 'Fermer',
  'common.cancel': 'Annuler',
  
  // Selection
  selected: 'sélectionné(s)',
  selectAll: 'Tout sélectionner',
  deselectAll: 'Tout désélectionner',
  
  // General
  items: 'articles',
  item: 'article',
  all: 'Tout',
  total: 'Total',
  
  // Currency
  currency: 'DH',
  currencyCode: 'MAD',
  
  // Date Filters
  today: 'Aujourd\'hui',
  yesterday: 'Hier',
  thisWeek: 'Cette semaine',
  thisMonth: 'Ce mois',
  thisYear: 'Cette année',
  lastWeek: 'Semaine dernière',
  lastMonth: 'Mois dernier',
  lastYear: 'Année dernière',
  selectDate: 'Sélectionner une date',
  period: 'Période',
  selectDates: 'Sélectionner les dates',
  start: 'Début',
  end: 'Fin',
  predefinedPeriod: 'Période prédéfinie',
  ok: 'OK',
  
  // Confirmation
  areYouSure: 'Êtes-vous sûr ?',
  actionCannotBeUndone: 'Cette action ne peut pas être annulée',
  
  // Dashboard
  quickAccess: 'Accès rapide',
  week: 'semaine',
  month: 'mois',
  year: 'année',
  custom: 'personnalisé',
  
  // Language Toggle
  switchToFrench: 'Changer en français',
  switchToArabic: 'التبديل للعربية',
  
  // Error Messages
  error: 'Une erreur est survenue',
  errorPrefix: 'Erreur',
  failedToCreate: 'Échec de création',
  failedToUpdate: 'Échec de mise à jour',
  failedToDelete: 'Échec de suppression',
  useAuthError: 'useAuth doit être utilisé dans un AuthProvider',
  useLanguageError: 'useLanguage doit être utilisé dans un LanguageProvider',
  
  // Menu Items
  sales: 'Ventes',
  purchases: 'Achats',
  quote: 'Devis',
  deliveryNote: 'Bon de Livraison',
  salesInvoice: 'Facture de Vente',
  payments: 'Paiements',
  clients: 'Clients',
  priceRequest: 'Demande de prix',
  purchaseOrder: "Bon d'Achat",
  purchaseInvoice: "Facture d'Achat",
  suppliers: 'Fournisseurs',
  stockMovements: 'Mouvements de stock',
  inventoryAdjustments: 'Ajustements d\'inventaire',
  warehouses: 'Entrepôts',
  
  // Document Statuses
  paid: 'Payée',
  partial: 'Partielle',
  pending: 'En attente',
  overdue: 'En retard',
  unpaid: 'Impayée',
  open: 'Ouvert',
  signed: 'Signée (à facturer)',
  closed: 'Non signée (fermée)',
  invoiced: 'Facturée',
  validated: 'Validée',
  inProgress: 'En cours',
  delivered: 'Livrée',
  cancelled: 'Annulée',
  draft: 'Brouillon',
  confirmed: 'Confirmé',
  assigned: 'Assigné',
  done: 'Effectué',
  allTypes: 'Tous les types',
  allStatuses: 'Tous les statuts',
  
  // Image Upload
  invalidFileType: 'Type de fichier invalide. Autorisés: JPEG, PNG, WebP',
  fileSizeExceeds: 'La taille du fichier dépasse la limite de',
  uploadFailed: 'Échec du téléchargement',
  pleaseTryAgain: 'Veuillez réessayer',
  imageUploadedSuccessfully: 'Image téléchargée avec succès',
  failedToConstructImageUrl: 'Impossible de construire l\'URL de l\'image',
  failedToRemoveImage: 'Impossible de supprimer l\'image',
  productPreview: 'Aperçu du produit',
  removeImage: 'Supprimer l\'image',
  
  // Dashboard
  dashboardOverview: 'Vue d\'ensemble de votre activité',
  revenueTrend: 'Tendance des revenus',
  last7Days: '7 derniers jours',
  ordersDistribution: 'Répartition des commandes',
  byStatus: 'Par statut',
  salesComparison: 'Comparaison des ventes',
  currentVsPrevious: 'Période actuelle vs précédente',
  currentPeriod: 'Période actuelle',
  previousPeriod: 'Période précédente',
  performanceMetrics: 'Indicateurs de performance',
  keyIndicators: 'Indicateurs clés',
  avgOrderValue: 'Valeur moyenne commande',
  customerGrowth: 'Croissance clients',
  conversionRate: 'Taux de conversion',
  recentActivity: 'Activité récente',
  latestUpdates: 'Dernières mises à jour',
  viewAll: 'Voir tout',
  newOrderReceived: 'Nouvelle commande reçue',
  newCustomer: 'Nouveau client',
  lowStock: 'Stock faible',
  dailyGoal: 'Objectif quotidien',
  quickActions: 'Actions rapides',
  getStartedQuickly: 'Commencez rapidement',
  newOrder: 'Nouvelle commande',
  viewOrders: 'Voir les commandes',
  ordersAwaitingProcessing: 'Commandes en attente',
  ordersInTransit: 'Commandes en transit',
  successfulDeliveries: 'Livraisons réussies',
  currentlyActive: 'Actuellement actif',
  revenue: 'Revenu',
  totalCustomers: 'Total clients',
  topProducts: 'Top produits',
  bestSellers: 'Meilleures ventes',
  ordersTimeline: 'Chronologie des commandes',
  dailyOrdersFlow: 'Flux quotidien des commandes',
  newOrders: 'Nouvelles commandes',
  secondsAgo: 'secondes',
  minutesAgo: 'min',
  hoursAgo: 'heures',
  daysAgo: 'jours',
  noRecentActivity: 'Aucune activité récente',
  
  // Common Actions
  validate: 'Valider',
  devalidate: 'Dévalider',
  view: 'Voir',
  deleteTitle: 'Supprimer',
  validating: 'En cours...',
  modify: 'Modifier',
  remove: 'Supprimer',
  validateDocument: 'Valider le document',
  devalidateDocument: 'Dévalider le document',
  
  // Months (short)
  monthJan: 'Jan',
  monthFeb: 'Fév',
  monthMar: 'Mar',
  monthApr: 'Avr',
  monthMay: 'Mai',
  monthJun: 'Jun',
  monthJul: 'Jul',
  monthAug: 'Aoû',
  monthSep: 'Sep',
  monthOct: 'Oct',
  monthNov: 'Nov',
  monthDec: 'Déc',
  monthJanuary: 'Janvier',
  monthFebruary: 'Février',
  monthMarch: 'Mars',
  monthApril: 'Avril',
  monthMayFull: 'Mai',
  monthJune: 'Juin',
  monthJuly: 'Juillet',
  monthAugust: 'Août',
  monthSeptember: 'Septembre',
  monthOctober: 'Octobre',
  monthNovember: 'Novembre',
  monthDecember: 'Décembre',
  
  // Preview/Download
  previewPDF: 'Aperçu PDF',
  downloadPDF: 'Télécharger PDF',
  download: 'Télécharger',
  generateLink: 'Générer le lien',
  
  // Confirmations
  confirmCancelMovement: 'Êtes-vous sûr de vouloir annuler ce mouvement ?',
  confirmRejectQuote: 'Voulez-vous vraiment refuser ce devis ? Il sera marqué comme fermé.',
  searchByNumberOrName: 'Rechercher par numéro ou nom...',
  manageCompanyInformation: 'Gérer les informations de votre entreprise',
  newPasswordOptional: 'Nouveau mot de passe (optionnel)',
  minCharacters: 'Min 6 caractères',
  informationSavedSuccess: 'Informations enregistrées avec succès',
  errorGeneratingPDF: 'Erreur lors de la génération du PDF',
  confirmDeletePayment: 'Êtes-vous sûr de vouloir supprimer ce paiement ? Cette action est irréversible.',
  previewReceipt: 'Aperçu Reçu',
  previewDeliveryNote: 'Aperçu Bon',
};
