export default {
  // Configurations Main Page
  configurations: 'Configurations',
  manageSystemConfigurations: 'Gérer les configurations système',
  backToDashboard: 'Retour au tableau de bord',
  
  // Configuration Modules
  taxes: 'Taxes',
  currencies: 'Devises',
  paymentTerms: 'Conditions de paiement',
  
  // Module Descriptions
  manageTaxRatesDescription: 'Gérer les taux de taxe et paramètres par défaut',
  manageCurrenciesDescription: 'Configurer les devises supportées et devise par défaut',
  managePaymentTermsDescription: 'Configurer les conditions de paiement et échéances',
  
  // Tax Rates
  taxRates: 'Taux de taxes',
  manageTaxRatesAndSettings: 'Gérer les taux de taxes et paramètres par défaut',
  searchTaxRates: 'Rechercher des taux de taxes...',
  addTaxRate: 'Ajouter un taux de taxe',
  editTaxRate: 'Modifier le taux de taxe',
  
  // Currencies
  manageSupportedCurrencies: 'Gérer les devises supportées',
  searchCurrencies: 'Rechercher des devises...',
  addCurrency: 'Ajouter une devise',
  editCurrency: 'Modifier la devise',
  
  // Payment Terms
  configurePaymentTermsAndDueDates: 'Configurer les conditions de paiement et échéances',
  searchPaymentTerms: 'Rechercher des conditions de paiement...',
  addPaymentTerm: 'Ajouter une condition de paiement',
  editPaymentTerm: 'Modifier la condition de paiement',
  
  // Common Fields
  rate: 'Taux',
  symbol: 'Symbole',
  code: 'Code',
  label: 'Libellé',
  days: 'Jours',
  key: 'Clé',
  default: 'Par défaut',
  
  // Common Actions
  retour: 'Retour',
  
  // Form Labels
  taxRateName: 'Nom du taux',
  taxRateValue: 'Taux (%)',
  setAsDefault: 'Définir par défaut',
  currencyCode: 'Code devise',
  currencyName: 'Nom de la devise',
  currencySymbol: 'Symbole',
  termKey: 'Clé du terme',
  termLabel: 'Libellé du terme',
  termDays: 'Nombre de jours',
  
  // Validation Messages
  nameRequired: 'Le nom est requis',
  rateRequired: 'Le taux est requis',
  codeRequired: 'Le code est requis',
  symbolRequired: 'Le symbole est requis',
  labelRequired: 'Le libellé est requis',
  keyRequired: 'La clé est requise',
  daysRequired: 'Le nombre de jours est requis',
  
  // Success Messages
  taxRateCreated: 'Taux de taxe créé avec succès',
  taxRateUpdated: 'Taux de taxe mis à jour avec succès',
  taxRateDeleted: 'Taux de taxe supprimé avec succès',
  currencyCreated: 'Devise créée avec succès',
  currencyUpdated: 'Devise mise à jour avec succès',
  currencyDeleted: 'Devise supprimée avec succès',
  paymentTermCreated: 'Condition de paiement créée avec succès',
  paymentTermUpdated: 'Condition de paiement mise à jour avec succès',
  paymentTermDeleted: 'Condition de paiement supprimée avec succès',
  
  // Table Headers
  name: 'Nom',
  status: 'Statut',
  actions: 'Actions',
  
  // Empty States
  noTaxRatesConfigured: 'Aucun taux de taxe configuré. Cliquez sur "Ajouter un taux de taxe" pour en créer un.',
  noCurrenciesConfigured: 'Aucune devise configurée. Cliquez sur "Ajouter une devise" pour en créer une.',
  noPaymentTermsConfigured: 'Aucune condition de paiement configurée. Cliquez sur "Ajouter une condition de paiement" pour en créer une.',
  
  // Form Labels and Placeholders
  ratePercentage: 'Taux (%)',
  currencyCodePlaceholder: 'USD',
  currencyNamePlaceholder: 'Dollar américain',
  currencySymbolPlaceholder: '$',
  paymentTermLabelPlaceholder: 'Net 30',
  paymentTermKeyPlaceholder: 'net_30',
  setAsDefaultTaxRate: 'Définir comme taux de taxe par défaut',
  setAsDefaultCurrency: 'Définir comme devise par défaut',
  setAsDefaultPaymentTerm: 'Définir comme condition de paiement par défaut',
  
  // Form Help Text
  lowercaseWithUnderscores: 'Minuscules avec underscores (ex: net_30)',
  autoGeneratedFromLabel: 'Généré automatiquement à partir du libellé',
  numberOfDaysUntilDue: 'Nombre de jours avant échéance du paiement',
  
  // Button States
  cancel: 'Annuler',
  save: 'Enregistrer',
  saving: 'Enregistrement...',
  
  // Status Labels
  default: 'Par défaut',
  daysLabel: 'jours',
  
  // Confirmation Messages
  confirmDeleteTaxRate: 'Êtes-vous sûr de vouloir supprimer ce taux de taxe ?',
  confirmDeleteCurrency: 'Êtes-vous sûr de vouloir supprimer cette devise ?',
  confirmDeletePaymentTerm: 'Êtes-vous sûr de vouloir supprimer cette condition de paiement ?',
};