export default {
  // Configurations Main Page
  configurations: 'Configurations',
  manageSystemConfigurations: 'Gérer les configurations système',
  backToDashboard: 'Retour au tableau de bord',

  // Configuration Modules
  taxes: 'Taxes',
  currencies: 'Devises',
  paymentTerms: 'Conditions de paiement',
  sequences: 'Séquences',

  // Module Descriptions
  manageTaxRatesDescription: 'Gérer les taux de taxe et paramètres par défaut',
  manageCurrenciesDescription: 'Configurer les devises supportées et devise par défaut',
  managePaymentTermsDescription: 'Configurer les conditions de paiement et échéances',
  manageSequencesDescription: 'Gérer les séquences de numérotation des documents',

  // Tax Rates
  taxRates: 'Taux de taxes',
  manageTaxRatesAndSettings: 'Gérer les taux de taxes et paramètres par défaut',
  searchTaxRates: 'Rechercher des taux de taxes...',
  addTaxRate: 'Ajouter un taux de taxe',
  editTaxRate: 'Modifier le taux de taxe',

  // Currencies
  manageSupportedCurrencies: 'Gérer les devises supportées',
  searchCurrencies: 'Rechercher des devises...',
  addCurrency: 'Ajouter une devise',
  editCurrency: 'Modifier la devise',

  // Payment Terms
  configurePaymentTermsAndDueDates: 'Configurer les conditions de paiement et échéances',
  searchPaymentTerms: 'Rechercher des conditions de paiement...',
  addPaymentTerm: 'Ajouter une condition de paiement',
  editPaymentTerm: 'Modifier la condition de paiement',

  // Common Fields
  rate: 'Taux',
  symbol: 'Symbole',
  code: 'Code',
  label: 'Libellé',
  days: 'Jours',
  key: 'Clé',
  default: 'Par défaut',

  // Common Actions
  retour: 'Retour',

  // Form Labels
  taxRateName: 'Nom du taux',
  taxRateValue: 'Taux (%)',
  setAsDefault: 'Définir par défaut',
  currencyCode: 'Code devise',
  currencyName: 'Nom de la devise',
  currencySymbol: 'Symbole',
  termKey: 'Clé du terme',
  termLabel: 'Libellé du terme',
  termDays: 'Nombre de jours',

  // Validation Messages
  nameRequired: 'Le nom est requis',
  rateRequired: 'Le taux est requis',
  codeRequired: 'Le code est requis',
  symbolRequired: 'Le symbole est requis',
  labelRequired: 'Le libellé est requis',
  keyRequired: 'La clé est requise',
  daysRequired: 'Le nombre de jours est requis',

  // Success Messages
  taxRateCreated: 'Taux de taxe créé avec succès',
  taxRateUpdated: 'Taux de taxe mis à jour avec succès',
  taxRateDeleted: 'Taux de taxe supprimé avec succès',
  currencyCreated: 'Devise créée avec succès',
  currencyUpdated: 'Devise mise à jour avec succès',
  currencyDeleted: 'Devise supprimée avec succès',
  paymentTermCreated: 'Condition de paiement créée avec succès',
  paymentTermUpdated: 'Condition de paiement mise à jour avec succès',
  paymentTermDeleted: 'Condition de paiement supprimée avec succès',

  // Table Headers
  name: 'Nom',
  status: 'Statut',
  actions: 'Actions',

  // Empty States
  noTaxRatesConfigured:
    'Aucun taux de taxe configuré. Cliquez sur "Ajouter un taux de taxe" pour en créer un.',
  noCurrenciesConfigured:
    'Aucune devise configurée. Cliquez sur "Ajouter une devise" pour en créer une.',
  noPaymentTermsConfigured:
    'Aucune condition de paiement configurée. Cliquez sur "Ajouter une condition de paiement" pour en créer une.',

  // Form Labels and Placeholders
  ratePercentage: 'Taux (%)',
  currencyCodePlaceholder: 'USD',
  currencyNamePlaceholder: 'Dollar américain',
  currencySymbolPlaceholder: '$',
  paymentTermLabelPlaceholder: 'Net 30',
  paymentTermKeyPlaceholder: 'net_30',
  setAsDefaultTaxRate: 'Définir comme taux de taxe par défaut',
  setAsDefaultCurrency: 'Définir comme devise par défaut',
  setAsDefaultPaymentTerm: 'Définir comme condition de paiement par défaut',

  // Form Help Text
  lowercaseWithUnderscores: 'Minuscules avec underscores (ex: net_30)',
  autoGeneratedFromLabel: 'Généré automatiquement à partir du libellé',
  nextNumberAutoManaged: 'Géré automatiquement par le système',
  numberOfDaysUntilDue: 'Nombre de jours avant échéance du paiement',

  // Button States
  cancel: 'Annuler',
  save: 'Enregistrer',
  saving: 'Enregistrement...',

  // Status Labels
  daysLabel: 'jours',

  // Confirmation Messages
  confirmDeleteTaxRate: 'Êtes-vous sûr de vouloir supprimer ce taux de taxe ?',
  confirmDeleteCurrency: 'Êtes-vous sûr de vouloir supprimer cette devise ?',
  confirmDeletePaymentTerm: 'Êtes-vous sûr de vouloir supprimer cette condition de paiement ?',

  // Sequences
  manageDocumentSequences: 'Gérer les séquences de numérotation des documents',
  searchSequences: 'Rechercher des séquences...',
  addSequence: 'Ajouter une séquence',
  editSequence: 'Modifier la séquence',
  entityType: 'Type de document',
  format: 'Format',
  nextDocumentNumber: 'Prochain numéro de document',
  nextNumber: 'Prochain numéro',
  numberLength: 'Longueur du numéro',
  resetPeriod: 'Période de remise à zéro',
  dateFormat: 'Format de date',
  prefix: 'Préfixe',
  suffix: 'Suffixe',
  includeYearInPrefix: "Inclure l'année dans le préfixe",
  includeMonthInPrefix: 'Inclure le mois dans le préfixe',
  includeDayInPrefix: 'Inclure le jour dans le préfixe',
  includeTrimesterInPrefix: 'Inclure le trimestre dans le préfixe',
  isActive: 'Actif',
  active: 'Actif',
  inactive: 'Inactif',
  preview: 'Aperçu',
  resetSequence: 'Remettre à zéro',

  // Entity Types
  invoiceSale: 'Facture de vente',
  invoicePurchase: "Facture d'achat",
  quote: 'Devis',
  deliveryNote: 'Bon de livraison',
  priceRequest: 'Demande de prix',
  purchaseOrder: "Bon d'achat",
  payment: 'Paiement',
  creditNote: 'Avoir',
  receipt: 'Reçu',
  posOrder: 'Commande POS',

  // Reset Periods
  never: 'Jamais',
  yearly: 'Annuellement',
  monthly: 'Mensuellement',
  daily: 'Quotidiennement',
  resetNever: 'Jamais',
  resetYearly: 'Annuellement',
  resetMonthly: 'Mensuellement',
  resetDaily: 'Quotidiennement',

  // Sequence Modal Sections
  identity: 'Identité',
  numbering: 'Numérotation',
  dateComponents: 'Composantes de date',
  year: 'Année',
  trimester: 'Trimestre',
  month: 'Mois',
  day: 'Jour',
  sequenceActiveDescription: 'La séquence est utilisée pour générer les numéros de documents',
  digitCount: 'chiffres',
  sequenceCountLabel: 'séquences',

  // Date Formats
  none: 'Aucun',

  // Placeholders
  sequenceNamePlaceholder: 'Nom de la séquence',

  // Empty States
  noSequencesConfigured:
    'Aucune séquence configurée. Cliquez sur "Ajouter une séquence" pour en créer une.',

  // Confirmation Messages
  confirmDeleteSequence: 'Êtes-vous sûr de vouloir supprimer cette séquence ?',
  confirmResetSequence: 'Êtes-vous sûr de vouloir remettre à zéro cette séquence ?',

  // Database Integration
  exampleOnly: 'Exemple seulement',
  actualNextNumber: 'Prochain numéro réel',
  basedOnDatabaseRecords: 'Basé sur les enregistrements de base de données',

  // ISequence Protection
  cannotEditUsedSequence:
    'Cette séquence ne peut pas être modifiée car des factures ont déjà été créées avec',
  sequenceInUseWarning:
    'Cette séquence est utilisée et ne peut pas être modifiée. Veuillez créer une nouvelle séquence si vous avez besoin de modifications.',
  sequenceInUseReadonly:
    'Cette séquence est déjà utilisée par des factures et ne peut pas être modifiée. Les champs sont en lecture seule.',
  edit: 'Modifier',

  // Warehouses
  warehouses: 'Entrepôts',
  warehouse: 'Entrepôt',
  manageWarehouses: 'Gérer les entrepôts',
  addWarehouse: 'Ajouter un entrepôt',
  editWarehouse: "Modifier l'entrepôt",
  deleteWarehouse: "Supprimer l'entrepôt",
  mainWarehouse: 'Entrepôt principal',
  warehouseCreated: 'Entrepôt créé avec succès',
  warehouseUpdated: 'Entrepôt mis à jour avec succès',
  warehouseDeleted: 'Entrepôt supprimé avec succès',

  // Stock Movements
  stockMovements: 'Mouvements de Stock',
  movementValidated: 'Mouvement validé avec succès',
  movementCancelled: 'Mouvement annulé',
  'movementTypes.receipt': 'Réception',
  'movementTypes.delivery': 'Livraison',
  'movementTypes.internal': 'Transfert',
  'movementTypes.adjustment': 'Ajustement',
  'movementTypes.productionIn': 'Production (entrée)',
  'movementTypes.productionOut': 'Production (sortie)',
  'movementTypes.scrap': 'Mise au rebut',
  'movementTypes.returnIn': 'Retour client',
  'movementTypes.returnOut': 'Retour fournisseur',
  searchByReferenceOrProduct: 'Rechercher par référence ou produit...',
  stockMovementsSubtitle: 'Suivre et gérer tous les mouvements de stock',
  noMovementsFound: 'Aucun mouvement trouvé',
  validateMovement: 'Valider',
  cancelMovement: 'Annuler',
  movementDetails: 'Détails',

  // Warehouses - English Labels
  manageWarehousesSubtitle: 'Gérez vos entrepôts et installations de stockage',
  searchWarehouses: 'Rechercher des entrepôts...',
  deleteWarehouseTitle: "Supprimer l'entrepôt",
  warehouseCode: 'WH-001',
  warehouseNamePlaceholder: 'Entrepôt principal',
  locationPlaceholder: 'Casablanca',

  // Inventory Adjustments
  inventoryAdjustments: "Ajustements d'Inventaire",
  manageInventoryAdjustments: 'Gérer les comptages et ajustements de stock',
  searchByReference: 'Rechercher par référence ou nom...',
  countingStartedSuccess: 'Comptage démarré avec succès',
  adjustmentValidatedSuccess: 'Ajustement validé avec succès',
  adjustmentCancelled: 'Ajustement annulé',
  adjustmentDeleted: 'Ajustement supprimé',
  confirmDeleteAdjustment: 'Êtes-vous sûr de vouloir supprimer cet ajustement ?',
  newAdjustment: 'Nouvel Ajustement',
  noAdjustmentsFound: 'Aucun ajustement trouvé',
  createFirstAdjustment: "Créez votre premier ajustement d'inventaire",
  draft: 'Brouillon',
  inProgress: 'En cours',
  validated: 'Validé',
  cancelled: 'Annulé',

  // Units of Measure
  unitsOfMeasure: 'Unités de mesure',
  manageUomDescription: "Gérer les unités de mesure pour l'inventaire",
  addUom: 'Ajouter une UdM',
  editUom: "Modifier l'unité de mesure",
  searchUom: 'Rechercher par nom ou code...',
  noUomFound: 'Aucune unité de mesure trouvée',
  confirmDeleteUom: 'Êtes-vous sûr de vouloir supprimer cette unité de mesure ?',
  baseUnit: 'Unité de base',
  isBaseUnit: 'Ceci est une unité de base',
  selectBaseUnit: 'Sélectionner une unité de base',
  derived: 'Dérivée',
  ratio: 'Ratio',
  ratioHelp: '1 cette unité = X unités de base',
  rounding: 'Arrondi',
  roundingPrecision: "Précision d'arrondi",
  allCategories: 'Toutes les catégories',

  // Inventory Settings
  inventorySettings: "Paramètres d'inventaire",
  inventorySettingsSubtitle: 'Configurer les mouvements de stock automatiques',
  incrementStock: 'Incrémenter le stock',
  decrementStock: 'Décrémenter le stock',
  noAutomaticMovement: 'Aucun mouvement automatique',
  defaultWarehouse: 'Entrepôt par défaut',
  selectDefaultWarehouse: 'Sélectionner un entrepôt par défaut',
  stockMovementAutomation: 'Automatisation des mouvements de stock',
  incrementOnInvoiceAchat: "Incrémenter le stock lors de la validation d'une facture d'achat",
  decrementOnInvoiceVente: "Décrémenter le stock lors de la validation d'une facture de vente",
  incrementOnOrderAchat: "Incrémenter le stock lors de la validation d'un bon d'achat",
  decrementOnOrderVente: "Décrémenter le stock lors de la validation d'un bon de livraison",
  inventorySettingsSaved: "Paramètres d'inventaire sauvegardés",
  noWarehouseConfigured:
    'Aucun entrepôt par défaut configuré. Les mouvements de stock ne seront pas créés.',

  originDestination: 'Origine → Destination',

  // Module tab labels
  tabOverview: 'Aperçu',
  tabTeam: 'Équipe',
  tabInventoryConfig: 'Inventaire',
  tabCompany: 'Société',
  units: 'Unités',
  roles: 'Rôles',

  // Printers
  printers: 'Imprimantes',
  printersDescription: "Gérer les imprimantes et historique d'impression",
  addPrinter: 'Ajouter une imprimante',
  editPrinter: "Modifier l'imprimante",
  printerName: "Nom de l'imprimante",
  printerBrand: 'Marque',
  connectionType: 'Type de connexion',
  paperWidth: 'Largeur du papier',
  documentTypes: 'Types de documents',
  isDefaultPrinter: 'Imprimante par défaut',
  ipAddress: 'Adresse IP',
  printerPort: 'Port',
  printerModel: 'Modèle',
  testPrint: "Test d'impression",
  printHistory: "Historique d'impression",
  printStatus: 'Statut',
  printMethod: 'Méthode',
  printDuration: 'Durée',
  printedAt: 'Imprimé le',
  noprinters: 'Aucune imprimante configurée',
  noPrintJobs: "Aucun historique d'impression",
  printerCreated: 'Imprimante créée avec succès',
  printerUpdated: 'Imprimante mise à jour avec succès',
  printerDeleted: 'Imprimante supprimée avec succès',
  deletePrinterConfirm: 'Êtes-vous sûr de vouloir supprimer cette imprimante ?',
  platformDetection: 'Détection de la plateforme',
  recommendedSetup: 'Configuration recommandée',
  setupGuides: 'Guides de configuration',
  // Printer network discovery
  scanNetwork: 'Scan réseau',
  networkSubnet: 'Sous-réseau (ex : 192.168.1)',
  startScan: 'Lancer le scan',
  scanning: 'Scan en cours...',
  scanningNetwork: 'Recherche en cours…',
  noDiscoveredPrinters: 'Aucune imprimante trouvée. Lancez le scan.',
  connectPrinter: 'Connecter',
  qztrayDiscoveryNote: '(si installé) : liste tous les pilotes USB/réseau du système.',
  httpProbeNote:
    ': détecte les imprimantes Epson ePOS (port 8008) et Star WebPRNT (port 80) sur le sous-réseau.',
  // Printer card
  printerDefault: 'Par défaut',
  printerLastSeen: 'Vu',
  // Delete
  deletePrinter: 'Supprimer',
};
