export default {
  // Invoices Main
  'invoice.title': 'Factures',
  'invoice.subtitle': 'Gestion des factures et paiements',
  'invoice.create': 'Créer une facture',
  'invoice.number': 'N° facture',
  'invoice.customer': 'Client',
  'invoice.date': 'Date',
  'invoice.dueDate': 'Date d\'échéance',
  'invoice.amount': 'Montant',
  'invoice.paid': 'Payé',
  'invoice.status': 'Statut',
  'invoice.payment': 'Paiement',
  'invoice.actions': 'Actions',
  'invoice.noInvoices': 'Aucune facture trouvée',
  
  // Search & Filters
  'invoice.searchPlaceholder': 'Rechercher par n° facture ou client...',
  'invoice.filterStatus': 'Filtrer par statut',
  'invoice.filterPayment': 'Filtrer par paiement',
  'invoice.allStatuses': 'Tous les statuts',
  'invoice.allPayments': 'Tous les paiements',
  'invoice.clearFilters': 'Effacer les filtres',
  
  // Selection
  'invoice.selectedCount': '{count} sélectionné(s)',
  'invoice.deleteSelected': 'Supprimer la sélection',
  'invoice.clearSelection': 'Effacer la sélection',
  
  // Items
  'invoice.items': 'Articles',
  'invoice.product': 'Produit',
  'invoice.quantity': 'Quantité',
  'invoice.unitPrice': 'Prix unitaire',
  'invoice.discount': 'Remise',
  'invoice.tax': 'Taxe',
  'invoice.total': 'Total',
  'invoice.subtotal': 'Sous-total',
  'invoice.remaining': 'Restant',
  'invoice.note': 'Note',
  'invoice.terms': 'Conditions',
  
  // Details
  'invoice.viewDetails': 'Voir les détails de la facture',
  'invoice.customerInfo': 'Informations client',
  'invoice.invoiceInfo': 'Informations facture',
  'invoice.download': 'Télécharger',
  
  // Payment
  'invoice.recordPayment': 'Enregistrer un paiement',
  'invoice.paymentAmount': 'Montant du paiement',
  'invoice.paymentRecorded': 'Paiement enregistré avec succès',
  'invoice.paymentError': 'Échec de l\'enregistrement du paiement',
  'invoice.invalidAmount': 'Montant invalide',
  'invoice.quickAmounts': 'Montants rapides',
  'invoice.payInFull': 'Payer en entier',
  'invoice.recording': 'Enregistrement en cours',
  'invoice.amountMustBePositive': 'Le montant doit être supérieur à zéro',
  'invoice.paymentExceedsRemaining': 'Le montant dépasse le solde restant',
  'invoice.paymentHistory': 'Historique des paiements',
  'invoice.payments': 'Paiements',
  'invoice.noPayments': 'Aucun paiement',
  'invoice.noMethod': 'Aucune méthode',
  
  // Delete
  'invoice.deleteSuccess': 'Facture supprimée avec succès',
  'invoice.deleteError': 'Échec de suppression de la facture',
  'invoice.confirmBulkDelete': 'Êtes-vous sûr de vouloir supprimer {count} factures ?',
  'invoice.deleteConfirm': 'Confirmer la suppression',
  'invoice.deleteConfirmMessage': 'Êtes-vous sûr de vouloir supprimer cette facture ? Cette action ne peut pas être annulée.',
  
  // Status Updates
  'invoice.statusUpdated': 'Statut mis à jour avec succès',
  'invoice.statusError': 'Échec de mise à jour du statut',
  'invoice.markAsSent': 'Marquer comme envoyée',
  'invoice.markAsPaid': 'Marquer comme payée',
  'invoice.cancel': 'Annuler',
  
  // Status Values
  'invoice.status.draft': 'Brouillon',
  'invoice.status.sent': 'Envoyée',
  'invoice.status.paid': 'Payée',
  'invoice.status.overdue': 'En retard',
  'invoice.status.cancelled': 'Annulée',
  
  // Payment Status Values
  'invoice.paymentStatus.unpaid': 'Non payée',
  'invoice.paymentStatus.partial': 'Partiellement payée',
  'invoice.paymentStatus.paid': 'Payée',
  
  // Statistics
  'invoice.stats.total': 'Total factures',
  'invoice.stats.totalAmount': 'Montant total',
  'invoice.stats.paid': 'Payé',
  'invoice.stats.unpaid': 'Non payé',
  'invoice.stats.overdue': 'En retard',
  'invoice.overdue': 'En retard',
  
  // Additional Fields
  'invoice.createdAt': 'Date de création',
  'invoice.issueDate': 'Date d\'émission',
  'invoice.taxRate': 'Taux de taxe',
  'invoice.notes': 'Notes',
  'invoice.information': 'Informations facture',
  'invoice.noCustomer': 'Aucun client',
  'invoice.noItems': 'Aucun article',
  
  // Create/Edit Invoice
  'invoice.customerRequired': 'Le client est requis',
  'invoice.validItemsRequired': 'Des articles valides sont requis',
  'invoice.createSubtitle': 'Créer une nouvelle facture pour le client',
  'invoice.selectCustomer': 'Sélectionner le client',
  'invoice.addItem': 'Ajouter un article',
  'invoice.productName': 'Nom du produit',
  'invoice.itemDescription': 'Description de l\'article',
  'invoice.notesPlaceholder': 'Notes ou instructions spéciales...',
  'invoice.createSuccess': 'Facture créée avec succès',
  'invoice.createError': 'Échec de la création de la facture',
  'invoice.noMatchingInvoices': 'Aucune facture correspondant aux filtres sélectionnés',
  'invoice.getStarted': 'Commencez par créer votre première facture',
  'invoice.basicInfo': 'Informations de base',
  'invoice.searchProduct': 'Rechercher un produit...',
  'invoice.openCatalog': 'Ouvrir le catalogue',
  'invoice.productCatalog': 'Catalogue de produits',
  'invoice.saveDraft': 'Enregistrer comme brouillon',
  'invoice.createAndSend': 'Créer et envoyer',
  'invoice.edit': 'Modifier la facture',
  'invoice.editSubtitle': 'Modifier les détails de la facture',
  'invoice.totalHT': 'Total HT',
  
  // Customer Info
  'customer.information': 'Informations client',
  
  // Form Labels
  'invoice.partnerNamePlaceholder': 'Nom du {partner}',
  'invoice.phoneLabel': 'Tél:',
  'invoice.addressLabel': 'Adresse:',
  'invoice.searchPlaceholderPartner': 'Rechercher...',
  'invoice.noPartnerFound': 'Aucun {partner} trouvé',
  'invoice.iceLabel': 'ICE',
  'invoice.deliveryAddressLabel': 'Adresse de livraison',
  'invoice.dateRequired': 'Date *',
  'invoice.dueDateLabel': 'Date d\'échéance',
  'invoice.paymentTermsLabel': 'Conditions de paiement',
  'invoice.paymentTermsPlaceholder': 'Ex: Paiement à 30 jours',
  'invoice.articlesTitle': 'Articles',
  'invoice.addLine': 'Ajouter ligne',
  'invoice.descriptionHeader': 'Description',
  'invoice.quantityHeader': 'Quantité',
  'invoice.unitPriceHeader': 'Prix unitaire',
  'invoice.discountHeader': 'Remise',
  'invoice.totalHeader': 'Total',
  'invoice.itemDescriptionPlaceholder': 'Description de l\'article',
  'invoice.productSearchPlaceholder': 'Rechercher un produit...',
  'invoice.noProductsFound': 'Aucun produit trouvé',
  'invoice.percentage': 'Pourcentage',
  'invoice.discountTypeAmount': 'Montant',
  'invoice.discountTypePercentage': '%',
  'invoice.summary': 'Résumé',
  'invoice.globalDiscount': 'Remise globale',
  'invoice.globalDiscountPlaceholder': 'Remise',
  'invoice.globalTax': 'Taxe globale',
  'invoice.globalTaxPlaceholder': 'Taxe (%)',
  'invoice.notesLabel': 'Notes',
  'invoice.supplier': 'Fournisseur',
};
