export default {
  // Invoices Main
  'invoice.title': 'Factures',
  'invoice.subtitle': 'Gestion des factures et paiements',
  'invoice.create': 'Créer une facture',
  'invoice.number': 'N° facture',
  'invoice.customer': 'Client',
  'invoice.date': 'Date',
  'invoice.dueDate': 'Date d\'échéance',
  'invoice.amount': 'Montant',
  'invoice.paid': 'Payé',
  'invoice.status': 'Statut',
  'invoice.payment': 'Paiement',
  'invoice.actions': 'Actions',
  'invoice.noInvoices': 'Aucune facture trouvée',
  
  // Search & Filters
  'invoice.searchPlaceholder': 'Rechercher par n° facture ou client...',
  'invoice.filterStatus': 'Filtrer par statut',
  'invoice.filterPayment': 'Filtrer par paiement',
  'invoice.allStatuses': 'Tous les statuts',
  'invoice.allPayments': 'Tous les paiements',
  'invoice.clearFilters': 'Effacer les filtres',
  
  // Selection
  'invoice.selectedCount': '{count} sélectionné(s)',
  'invoice.deleteSelected': 'Supprimer la sélection',
  'invoice.clearSelection': 'Effacer la sélection',
  
  // Items
  'invoice.items': 'Articles',
  'invoice.product': 'Produit',
  'invoice.quantity': 'Quantité',
  'invoice.unitPrice': 'Prix unitaire',
  'invoice.discount': 'Remise',
  'invoice.tax': 'Taxe',
  'invoice.total': 'Total',
  'invoice.subtotal': 'Sous-total',
  'invoice.remaining': 'Restant',
  'invoice.note': 'Note',
  'invoice.terms': 'Conditions',
  
  // Details
  'invoice.viewDetails': 'Voir les détails de la facture',
  'invoice.customerInfo': 'Informations client',
  'invoice.invoiceInfo': 'Informations facture',
  'invoice.download': 'Télécharger',
  
  // Payment
  'invoice.recordPayment': 'Enregistrer un paiement',
  'invoice.paymentAmount': 'Montant du paiement',
  'invoice.paymentRecorded': 'Paiement enregistré avec succès',
  'invoice.paymentError': 'Échec de l\'enregistrement du paiement',
  'invoice.invalidAmount': 'Montant invalide',
  'invoice.quickAmounts': 'Montants rapides',
  'invoice.payInFull': 'Payer en entier',
  'invoice.recording': 'Enregistrement en cours',
  'invoice.amountMustBePositive': 'Le montant doit être supérieur à zéro',
  'invoice.paymentExceedsRemaining': 'Le montant dépasse le solde restant',
  'invoice.paymentHistory': 'Historique des paiements',
  'invoice.payments': 'Paiements',
  'invoice.noPayments': 'Aucun paiement',
  'invoice.noMethod': 'Aucune méthode',
  
  // Delete
  'invoice.deleteSuccess': 'Facture supprimée avec succès',
  'invoice.deleteError': 'Échec de suppression de la facture',
  'invoice.confirmBulkDelete': 'Êtes-vous sûr de vouloir supprimer {count} factures ?',
  'invoice.deleteConfirm': 'Confirmer la suppression',
  'invoice.deleteConfirmMessage': 'Êtes-vous sûr de vouloir supprimer cette facture ? Cette action ne peut pas être annulée.',
  
  // Status Updates
  'invoice.statusUpdated': 'Statut mis à jour avec succès',
  'invoice.statusError': 'Échec de mise à jour du statut',
  'invoice.markAsSent': 'Marquer comme envoyée',
  'invoice.markAsPaid': 'Marquer comme payée',
  'invoice.cancel': 'Annuler',
  
  // Status Values
  'invoice.status.draft': 'Brouillon',
  'invoice.status.sent': 'Envoyée',
  'invoice.status.paid': 'Payée',
  'invoice.status.overdue': 'En retard',
  'invoice.status.cancelled': 'Annulée',
  
  // Payment Status Values
  'invoice.paymentStatus.unpaid': 'Non payée',
  'invoice.paymentStatus.partial': 'Partiellement payée',
  'invoice.paymentStatus.paid': 'Payée',
  
  // Statistics
  'invoice.stats.total': 'Total factures',
  'invoice.stats.totalAmount': 'Montant total',
  'invoice.stats.paid': 'Payé',
  'invoice.stats.unpaid': 'Non payé',
  'invoice.stats.overdue': 'En retard',
  'invoice.overdue': 'En retard',
  
  // Additional Fields
  'invoice.createdAt': 'Date de création',
  'invoice.issueDate': 'Date d\'émission',
  'invoice.taxRate': 'Taux de taxe',
  'invoice.notes': 'Notes',
  'invoice.information': 'Informations facture',
  'invoice.noCustomer': 'Aucun client',
  'invoice.noItems': 'Aucun article',
  
  // Create/Edit Invoice
  'invoice.customerRequired': 'Le client est requis',
  'invoice.validItemsRequired': 'Des articles valides sont requis',
  'invoice.createSubtitle': 'Créer une nouvelle facture pour le client',
  'invoice.selectCustomer': 'Sélectionner le client',
  'invoice.addItem': 'Ajouter un article',
  'invoice.productName': 'Nom du produit',
  'invoice.itemDescription': 'Description de l\'article',
  'invoice.notesPlaceholder': 'Notes ou instructions spéciales...',
  'invoice.createSuccess': 'Facture créée avec succès',
  'invoice.createError': 'Échec de la création de la facture',
  'invoice.noMatchingInvoices': 'Aucune facture correspondant aux filtres sélectionnés',
  'invoice.getStarted': 'Commencez par créer votre première facture',
  'invoice.basicInfo': 'Informations de base',
  'invoice.searchProduct': 'Rechercher un produit...',
  'invoice.openCatalog': 'Ouvrir le catalogue',
  'invoice.productCatalog': 'Catalogue de produits',
  'invoice.saveDraft': 'Enregistrer comme brouillon',
  'invoice.createAndSend': 'Créer et envoyer',
  'invoice.edit': 'Modifier la facture',
  'invoice.editSubtitle': 'Modifier les détails de la facture',
  'invoice.totalHT': 'Total HT',
  
  // Customer Info
  'customer.information': 'Informations client',
  
  // Form Labels
  'invoice.partnerNamePlaceholder': 'Nom du {partner}',
  'invoice.phoneLabel': 'Tél:',
  'invoice.addressLabel': 'Adresse:',
  'invoice.searchPlaceholderPartner': 'Rechercher...',
  'invoice.noPartnerFound': 'Aucun {partner} trouvé',
  'invoice.iceLabel': 'ICE',
  'invoice.deliveryAddressLabel': 'Adresse de livraison',
  'invoice.dateRequired': 'Date *',
  'invoice.dueDateLabel': 'Date d\'échéance',
  'invoice.paymentTermsLabel': 'Conditions de paiement',
  'invoice.paymentTermsPlaceholder': 'Ex: Paiement à 30 jours',
  'invoice.articlesTitle': 'Articles',
  'invoice.addLine': 'Ajouter ligne',
  'invoice.descriptionHeader': 'Description',
  'invoice.quantityHeader': 'Quantité',
  'invoice.unitPriceHeader': 'Prix unitaire',
  'invoice.discountHeader': 'Remise',
  'invoice.totalHeader': 'Total',
  'invoice.itemDescriptionPlaceholder': 'Description de l\'article',
  'invoice.productSearchPlaceholder': 'Rechercher un produit...',
  'invoice.noProductsFound': 'Aucun produit trouvé',
  'invoice.percentage': 'Pourcentage',
  'invoice.discountTypeAmount': 'Montant',
  'invoice.discountTypePercentage': '%',
  'invoice.summary': 'Résumé',
  'invoice.globalDiscount': 'Remise globale',
  'invoice.globalDiscountPlaceholder': 'Remise',
  'invoice.globalTax': 'Taxe globale',
  'invoice.globalTaxPlaceholder': 'Taxe (%)',
  'invoice.notesLabel': 'Notes',
  'invoice.supplier': 'Fournisseur',
  
  // Payment Modal
  'invoice.editPayment': 'Modifier le paiement',
  'invoice.addPayment': 'Ajouter un paiement',
  'invoice.amountMustBeGreaterThanZero': 'Le montant doit être supérieur à 0',
  'invoice.errorOccurred': 'Une erreur est survenue',
  'invoice.totalInvoice': 'Total facture',
  'invoice.totalPaid': 'Total payé',
  'invoice.payRemainingAmount': 'Payer le montant restant',
  'invoice.paymentDate': 'Date de paiement',
  'invoice.paymentMethod': 'Méthode de paiement',
  'invoice.referenceNumber': 'Numéro de référence',
  'invoice.additionalNotes': 'Notes supplémentaires',
  'invoice.notesPlaceholder2': 'Notes supplémentaires...',
  
  // Document Items Table
  'invoice.productCatalogue': 'Catalogue produits',
  
  // Document Edit/Create Messages (non-prefixed for direct use)
  errorLoadingDocument: 'Erreur lors du chargement du document',
  pleaseAddAtLeastOneItem: 'Veuillez ajouter au moins un article',
  pleaseSelectDate: 'Veuillez sélectionner une date',
  errorValidating: 'Erreur lors de la validation',
  errorDevalidating: 'Erreur lors de la dévalidation',
  deliveryNoteMarkedDelivered: 'Bon de livraison marqué comme livré',
  errorMarkingDelivered: 'Erreur lors de la livraison',
  deliveryNoteCancelled: 'Bon de livraison annulé',
  errorCancelling: 'Erreur lors de l\'annulation',
  invoiceCreatedQuoteUpdated: 'Facture créée avec succès et devis mis à jour',
  invoiceCreatedDeliveryUpdated: 'Facture créée avec succès et bon de livraison mis à jour',
  errorCreatingInvoice: 'Erreur lors de la création de la facture',
  deliveryNoteCreatedQuoteUpdated: 'Bon de livraison créé avec succès et devis mis à jour',
  errorCreatingDeliveryNote: 'Erreur lors de la création du bon de livraison',
  shareLinkGenerated: 'Lien de partage généré avec succès',
  errorGeneratingLink: 'Erreur lors de la génération du lien',
  quoteSigned: 'Devis signé avec succès',
  errorSigning: 'Erreur lors de la signature',
  quoteRejectedClosed: 'Devis refusé et fermé avec succès',
  errorValidatingDocument: 'Erreur lors de la validation du document',
  errorDevalidatingDocument: 'Erreur lors de la dévalidation du document',
  
  // Document Action Titles
  validateDocumentTitle: 'Valider le document',
  devalidateDocumentTitle: 'Dévalider le document',
  createInvoiceTitle: 'Créer une facture',
  createDeliveryNoteTitle: 'Créer un bon de livraison',
  signQuoteTitle: 'Signer le devis',
  rejectQuoteTitle: 'Refuser le devis',
  markAsDeliveredTitle: 'Marquer comme livré',
  cancelDeliveryNoteTitle: 'Annuler le bon de livraison',
  additionalNotesPlaceholder: 'Notes additionnelles...',
  
  // Document Status Labels
  paid: 'Payé',
  unpaid: 'Impayé',
  signedToInvoice: 'Signée (à facturer)',
  unsignedClosed: 'Non signée (fermée)',
  toDeliver: 'À livrer',
  invoiced: 'Facturée',
  validated: 'Validée',
  delivered: 'Livrée',
  cancelled: 'Annulée',
  invoicedStatus: 'Facturé',
  
  // Confirmation Messages
  confirmValidateDocument: 'Êtes-vous sûr de vouloir valider ce document ? Il ne pourra plus être modifié.',
  confirmDevalidateDocument: 'Êtes-vous sûr de vouloir dévalider ce document ?',
  confirmCreateInvoice: 'Voulez-vous créer une facture à partir de ce document ?',
  confirmCreateDeliveryNote: 'Voulez-vous créer un bon de livraison à partir de ce devis ? Toutes les données seront copiées.',
  confirmSignQuote: 'Voulez-vous marquer ce devis comme signé ?',
  confirmRejectQuote: 'Voulez-vous vraiment refuser ce devis ? Le statut sera changé à \'Fermé\'.',
  confirmMarkDelivered: 'Êtes-vous sûr de vouloir marquer ce bon de livraison comme livré ?',
  confirmCancelDelivery: 'Êtes-vous sûr de vouloir annuler ce bon de livraison ? Cette action peut être irréversible.',
  confirmDeleteDocument: 'Êtes-vous sûr de vouloir supprimer ce document ? Cette action est irréversible.',
  confirmValidate: 'Êtes-vous sûr de vouloir valider ce document ?',
  confirmDevalidate: 'Êtes-vous sûr de vouloir dévalider ce document ?',
  
  // Success Messages
  success: 'Succès',
  documentValidated: 'Document validé avec succès',
  documentDevalidated: 'Document dévalidé avec succès',
  
  // Error Messages  
  errorDevalidatingInList: 'Erreur lors de la dévalidation du document',
  unsupportedDocumentType: 'Type de document non supporté',
  
  // Additional Labels
  totalRevenue: 'Revenu',
  totalExpenses: 'Dépenses',
  create: 'Créer',
  devalidate: 'Dévalider',
  signedStatus: '✓ Signé',
  closedStatus: '✕ Fermé',
  awaitingSignature: 'En attente de signature',
  signedByLabel: 'Signé par:',
  dateLabel: 'Date:',
  signedByPlaceholder: 'Votre nom complet',
  validateDocument: 'Valider',
  devalidateDocument: 'Dévalider',
  markAsDelivered: 'Marquer comme livré',
  signQuote: 'Signer',
  rejectQuote: 'Refuser',
  cancelDeliveryTitle: 'Annuler le bon de livraison',
  createInvoiceMessage: 'Voulez-vous créer une facture à partir de',
  thisQuote: 'ce devis',
  thisDeliveryNote: 'ce bon de livraison',
  allDataWillBeCopied: '? Toutes les données seront copiées.',
  deliverButton: 'Livrer',
  cancelDeliveryButton: 'Annuler le bon',
  rejectButton: 'Refuser',
  shareQuote: 'Partager le devis',
  generateSecureLink: 'Générez un lien de partage sécurisé pour permettre à votre client de consulter et signer ce devis.',
  downloadPDF: 'Télécharger PDF',
  errorGeneratingPDF: 'Erreur lors de la génération du PDF',
  
  // Document Create Page
  pleaseSelect: 'Veuillez sélectionner un',
  createdSuccessfully: 'créée avec succès',
  new: 'Nouvelle',
  createNew: 'Créer une nouvelle',
  documentInformation: 'Informations du document',
  expirationDate: 'Date d\'expiration',
  additionalNotes: 'Notes additionnelles...',
  draft: 'Brouillon',
  subtotalHT: 'Sous-total HT',
  totalTVA: 'Total TVA',
  totalTTC: 'Total TTC',
  
  // Document List Page
  listOf: 'Liste des',
  manageYour: 'Gérez vos',
  nouveau: 'Nouveau',
  partial: 'Partielles',
  partiallyPaid: 'Partiellement payées',
  amount: 'Montant',
  lastThree: 'Les 3 dernières',
  noRecentDocument: 'Aucune',
  recentSuffix: 'récente',
  drafts: 'Brouillons',
  noDrafts: 'Aucun brouillon',
  error: 'Erreur',
  deletionImpossible: 'Suppression impossible',
  errorDeletingDocument: 'Erreur lors de la suppression du document',
  
  // Document Types & Titles
  salesInvoices: 'Factures de Vente',
  salesInvoice: 'Facture Client',
  purchaseInvoices: 'Factures d\'Achat',
  purchaseInvoice: 'Facture Fournisseur',
  quotes: 'Devis',
  quote: 'Devis',
  deliveryNotes: 'Bons de Livraison',
  deliveryNote: 'Bon de Livraison',
  client: 'Client',
  supplier: 'Fournisseur',
  
  // DocumentTable
  columns: 'Colonnes',
  showColumns: 'Afficher colonnes',
  showHideColumns: 'Afficher/Masquer colonnes',
  taxAmount: 'Montant TVA',
  alreadyPaid: 'Déjà réglé',
  remainingToPay: 'Reste à payer',
  searchByNumberOrName: 'Rechercher par numéro ou nom...',
  pdfPreview: 'Aperçu PDF',
  number: 'Numéro',
  invoiceDate: 'Date facturation',
  quoteDate: 'Date devis',
  deliveryDate: 'Date livraison',
  dueDate: 'Date échéance',
  validationDate: 'Date validation',
  amountHT: 'Montant HT',
  amountTTC: 'Montant TTC',
  status: 'Statut',
  loading: 'Chargement...',
  noDocumentFound: 'Aucun document trouvé',
  showingFrom: 'Affichage de',
  to: 'à',
  on: 'sur',
  previous: 'Précédent',
  next: 'Suivant',
  
  // Status Labels - Payment
  statusPaid: 'Payé',
  statusPartial: 'Partiel',
  statusUnpaid: 'Impayé',
  statusDraft: 'Brouillon',
  
  // Status Labels - Quote
  statusOpen: 'Ouvert',
  statusSigned: 'Signée (à facturer)',
  statusClosed: 'Non signée (fermée)',
  statusDelivered: 'À livrer',
  statusInvoiced: 'Facturée',
  
  // Status Labels - Delivery Note
  statusValidated: 'Validée',
  statusInProgress: 'En cours',
  statusDeliveredBon: 'Livrée',
  statusCancelled: 'Annulée',
  statusInvoicedBon: 'Facturé',
  
  // Additional Success Messages
  successUpdated: 'mise à jour avec succès',
  successValidated: 'validée avec succès',
  successDevalidated: 'dévalidée avec succès',
  successDelivered: 'Bon de livraison marqué comme livré',
  successCancelled: 'Bon de livraison annulé',
  successInvoiceCreatedQuoteUpdated: 'Facture créée avec succès et devis mis à jour',
  successInvoiceCreatedDeliveryUpdated: 'Facture créée avec succès et bon de livraison mis à jour',
  successDeliveryCreatedQuoteUpdated: 'Bon de livraison créé avec succès et devis mis à jour',
  successLinkGenerated: 'Lien de partage généré avec succès',
  successQuoteSigned: 'Devis signé avec succès',
  successQuoteRejected: 'Devis refusé et fermé avec succès',
  
  // Additional Error Messages
  errorUnsigning: 'Erreur lors de l\'annulation de la signature',
  errorUpdatingDocument: 'Erreur lors de la mise à jour',
  errorDelivering: 'Erreur lors de la livraison',
  
  // Additional Edit/Create messages
  selectPartner: 'Veuillez sélectionner un',
  
  // Document Edit UI
  editDocument: 'Modifier la',
  notValidated: 'Non validé',
  paymentDetails: 'Détails de paiement',
  totalAmount: 'Montant total',
  paidAmount: 'Montant payé',
  remainingAmount: 'Montant restant',
  date: 'Date',
  notes: 'Notes',
  signature: 'Signature',
  signedBy: 'Signé par:',
  comment: 'Commentaire:',
  paymentHistory: 'Historique des paiements',
  cancel: 'Annuler',
  actions: 'Actions',
  convertToInvoice: 'Convertir en facture',
  shareWithClient: 'Partager avec client',
  createAnInvoice: 'Créer une facture',
  createDeliveryNote: 'Créer un bon de livraison',
  save: 'Enregistrer',
  saving: 'Enregistrement...',
  
  // Payment Modal & History
  errorPaymentExceedsInvoice: 'Le montant total des paiements ne peut pas dépasser le total de la facture',
  errorOccurred: 'Une erreur est survenue',
  errorDeletingPayment: 'Erreur lors de la suppression du paiement',
  referenceNumberHint: '(N° chèque, transaction, etc.)',
  referenceNumberPlaceholder: 'Ex: CHK-12345',
  invoice: 'Facture',
  totalInvoice: 'Total facture',
  totalPaid: 'Total payé',
  remainingToPay: 'Reste à payer',
  invoiceFullyPaid: 'Facture entièrement payée',
  addPayment: 'Ajouter un paiement',
  noPaymentsRecorded: 'Aucun paiement enregistré',
  amount: 'Montant',
  paymentMethod: 'Mode de paiement',
  reference: 'Référence',
  close: 'Fermer',
  deleteTitle: 'Confirmer la suppression',
  confirmDeletePayment: 'Êtes-vous sûr de vouloir supprimer ce paiement ?',
  delete: 'Supprimer',
  edit: 'Modifier',
  add: 'Ajouter',
  
  // Payment Pages
  purchasePayments: 'Paiements d\'achat',
  managePurchasePayments: 'Gérer les paiements fournisseurs',
  salesPayments: 'Paiements de vente',
  manageSalesPayments: 'Gérer les paiements clients',
  totalPayments: 'Total des paiements',
  thisMonth: 'Ce mois',
  supplier: 'Fournisseur',
  client: 'Client',
  searchByInvoice: 'Rechercher par facture, client ou référence...',
  modify: 'Modifier',
  error: 'Erreur',
};
