export default {
  // Customers
  customers: 'Clients',
  customer: 'Client',
  manageCustomers: 'Gérer les clients',
  searchCustomers: 'Rechercher des clients...',
  noCustomersFound: 'Aucun client trouvé',
  customerUpdated: 'Client mis à jour avec succès',
  customerCreated: 'Client créé avec succès',
  customerDeleted: 'Client supprimé avec succès',
  addCustomer: 'Ajouter un client',
  phoneNumberRequired: 'Numéro de téléphone requis',
  city: 'Ville',
  
  // Suppliers
  suppliers: 'Fournisseurs',
  supplier: 'Fournisseur',
  manageSuppliers: 'Gérer les fournisseurs',
  searchSuppliers: 'Rechercher des fournisseurs...',
  noSuppliersFound: 'Aucun fournisseur trouvé',
  supplierUpdated: 'Fournisseur mis à jour avec succès',
  supplierCreated: 'Fournisseur créé avec succès',
  supplierDeleted: 'Fournisseur supprimé avec succès',
  addSupplier: 'Ajouter un fournisseur',
  
  // Partner Form
  partnerType: 'Type de partenaire',
  individual: 'Particulier',
  company: 'Société',
  fillInformation: 'Remplissez les informations ci-dessous',
  basicInformation: 'Informations de base',
  businessIdentifiers: 'Identifiants commerciaux',
  nameRequired: 'Le nom est requis',
  invalidEmail: 'Email invalide',
  enterName: 'Entrez le nom',
  deliveryAddress: 'Adresse de livraison',
  enterDeliveryAddress: 'Entrez l\'adresse de livraison',
  enterAddress: 'Entrez l\'adresse',
  tvaNumber: 'Numéro TVA',
  enterTvaNumber: 'Entrez le numéro TVA',
  ice: 'Numéro ICE',
  enterICE: 'Entrez le numéro ICE',
  if: 'Numéro IF',
  enterIF: 'Entrez le numéro IF',
  cnss: 'Numéro CNSS',
  enterCNSS: 'Entrez le numéro CNSS',
  rc: 'Numéro RC',
  enterRC: 'Entrez le numéro RC',
  patente: 'Numéro Patente',
  enterPatente: 'Entrez le numéro Patente',
  updatePartner: 'Mettre à jour le partenaire',
  createPartner: 'Créer un partenaire',
  deletePartnerConfirmation: 'Êtes-vous sûr de vouloir supprimer ce partenaire ? Cette action ne peut pas être annulée.',
};
