export default {
  // POS
  pos: 'Point de vente',
  pointOfSale: 'Point de vente',
  createOrders: 'Créer des commandes',

  // Cart
  cart: 'Panier',
  cartEmpty: 'Le panier est vide',
  emptyCartMessage: 'Commencez à ajouter des produits',
  selectCustomer: 'Veuillez sélectionner un client',
  newCustomer: 'Nouveau client',
  searchByNameOrPhone: 'Rechercher par nom ou téléphone...',
  change: 'Changer',
  searchResults: 'Résultats de recherche',
  searchForCustomer: 'Chercher un client',
  searchCustomerInstructions: 'Entrez au moins 2 caractères pour rechercher',
  currentCustomer: 'Client actuel',
  createNewCustomer: 'Créer un nouveau client',
  createCustomer: 'Créer le client',
  cartProduct: 'produit',
  cartProducts: 'produits',
  piece: 'pièce',
  pieces: 'pièces',
  perUnit: '/ unité',
  clear: 'Effacer',
  confirmClearCart: 'Vider le panier ?',
  clearCart: 'Vider',
  addToCart: 'Ajouter au panier',
  updateQty: 'Modifier la quantité',
  confirmPrice: 'Confirmer le prix',
  originalPrice: 'Prix original',
  applyDiscount: 'Appliquer une remise',
  percentage: 'Pourcentage',
  belowCostWarning: 'Vente en dessous du prix de revient',
  confirmCash: 'Encaissement',
  orderSummary: 'Résumé de la commande',
  reviewAndConfirmOrder: 'Vérifier et confirmer la commande',
  backToPOS: 'Retour à la caisse',

  // Documents
  downloadDocuments: 'Téléchargez les documents ci-dessous',
  receipt: 'Reçu',
  invoice: 'Facture',
  thermalReceipt80mm: 'Reçu thermique 80mm',
  deliveryNoteA5: 'Bon de livraison A5',
  preview: 'Aperçu',
  print: 'Imprimer',

  // Image upload (POS)
  addPhoto: 'Photo',
  takePhoto: 'Prendre une photo',
  orChooseFromGallery: 'Choisir depuis la galerie',
  uploading: 'Envoi en cours',
  imageUploadedSuccess: 'Image mise à jour avec succès',
};
