export default {
  // Products Management
  products: 'Produits',
  product: 'Produit',
  manageProducts: 'Gérer les produits',
  addProduct: 'Ajouter un produit',
  editProduct: 'Modifier le produit',
  productName: 'Nom du produit',
  productCode: 'Code du produit',
  description: 'Description',
  price: 'Prix',
  cost: 'Coût',
  stock: 'Stock',
  image: 'Image',
  productImage: 'Image du produit',
  chooseImage: 'Choisir une image',
  orImageUrl: 'Ou coller l\'URL de l\'image',
  imageDescription: 'Télécharger une image du produit (JPG, PNG, max 5MB)',
  isService: 'Service',
  isEnabled: 'Activé',
  isPriceChangeAllowed: 'Autoriser le changement de prix',
  allowPriceChange: 'Autoriser le changement de prix',
  lockPriceChange: 'Verrouiller le changement de prix',
  enable: 'Activer',
  disable: 'Désactiver',
  importFile: 'Importer image',
  fileSelected: 'Fichier sélectionné',
  bulkImportFeatureComingSoon: 'Fonctionnalité d\'importation en cours de développement',
  selectOneProductForImageUpload: 'Veuillez sélectionner un seul produit pour télécharger l\'image',
  confirmDelete: 'Êtes-vous sûr de vouloir supprimer ce produit ?',
  code: 'Code',
  searchProducts: 'Rechercher des produits...',
  noProductsFound: 'Aucun produit trouvé',
  noResultsMessage: 'Essayez un autre terme de recherche',
  noProductsInCategory: 'Aucun produit disponible',
};
