export default {
  // ─── Users & Roles Module ─────────────────────────────────
  usersAndRoles: 'Utilisateurs & Rôles',
  usersManagement: 'Gestion des utilisateurs',
  rolesManagement: 'Gestion des rôles',
  adminUsers: 'Utilisateurs Admin',
  clientUsers: 'Utilisateurs Client',
  roleName: 'Nom du rôle',
  roleDescription: 'Description du rôle',
  superAdmin: 'Super Admin',
  permissions: 'Permissions',
  assignRole: 'Attribuer un rôle',
  noRole: 'Aucun rôle',
  userType: "Type d'utilisateur",
  admin: 'Admin',
  clientUser: 'Client',
  roleCreated: 'Rôle créé avec succès',
  roleUpdated: 'Rôle mis à jour avec succès',
  roleDeleted: 'Rôle supprimé avec succès',
  userCreated: 'Utilisateur créé avec succès',
  userUpdated: 'Utilisateur mis à jour avec succès',
  userDeleted: 'Utilisateur supprimé avec succès',
  userActivated: 'Utilisateur activé avec succès',
  userDeactivated: 'Utilisateur désactivé avec succès',
  createUser: 'Créer un utilisateur',
  editUser: "Modifier l'utilisateur",
  createRole: 'Créer un rôle',
  editRole: 'Modifier le rôle',
  confirmDeleteUser: 'Confirmez-vous la suppression de cet utilisateur ?',
  confirmDeleteRole: 'Confirmez-vous la suppression de ce rôle ?',
  passwordMinLength: 'Le mot de passe doit contenir au moins 8 caractères',
  phoneRequired: 'Le numéro de téléphone est requis',
  nameRequired2: 'Le nom est requis',
  password: 'Mot de passe',
  newPassword: 'Nouveau mot de passe',
  avatar: 'Avatar',
  role: 'Rôle',
  roles: 'Rôles',
  users: 'Utilisateurs',
  allPermissions: 'Toutes les permissions',
  permissionView: 'Voir',
  permissionCreate: 'Créer',
  permissionEdit: 'Modifier',
  permissionDelete: 'Supprimer',
  permissionManage: 'Gérer',
  permissionUse: 'Utiliser',
  selectAll: 'Tout sélectionner',
  deselectAll: 'Tout désélectionner',
  noPermissionsAssigned: 'Aucune permission attribuée',
  cannotDeactivateSelf: 'Vous ne pouvez pas désactiver votre propre compte',
  cannotDeleteSelf: 'Vous ne pouvez pas supprimer votre propre compte',
  cannotRemoveOwnSuperAdmin: 'Vous ne pouvez pas enlever votre propre rôle super admin',
  superAdminBadge: 'Super Admin',
  moduleName: 'Module',
  approved: 'Approuvé',
  rejected: 'Rejeté',
  userApproved: 'Utilisateur approuvé avec succès',
  userRejected: 'Utilisateur rejeté avec succès',

  // ─── Users page (previously untranslated) ─────────────────
  activate: 'Activer',
  deactivate: 'Désactiver',
  reject: 'Rejeter',
  confirmDeactivateUser: 'Désactiver cet utilisateur ?',
  confirmActivateUser: 'Activer cet utilisateur ?',
  confirmRejectUser: 'Rejeter cet accès portail ?',
  confirmApproveUser: 'Approuver cet accès portail ?',
  noUsersFound: 'Aucun utilisateur trouvé',
  usersCountLabel: 'utilisateurs',
  userCountLabel: 'utilisateur',
  confirmDeleteUsersPlural: 'Supprimer {count} utilisateur(s) ?',

  // ─── Client access requests (portal sign-ups) ────────────
  clientRequests: 'Demandes clients',
  clientRequestsSubtitle: 'Approuvez ou refusez les comptes créés depuis le portail client',
  clientRequestsCountLabel: 'demandes',
  searchClientRequests: 'Rechercher par nom ou téléphone…',
  clearSearch: 'Effacer la recherche',
  approveRequest: 'Approuver',
  declineRequest: 'Refuser',
  confirmDeclineRequest: 'Refuser cette demande d’accès ?',
  noClientRequests: 'Aucune demande client',
  requestedOn: 'Demandé le',
  bulkApprove: 'Approuver la sélection',
  bulkDecline: 'Refuser la sélection',
  requestApproved: 'Demande approuvée',
  requestDeclined: 'Demande refusée',
};
