export default {
  // ─── Access Control ───────────────────────────────────────
  accessForbiddenTitle: 'الوصول غير مصرح به',
  accessForbiddenBody:
    'دورك لا يمنحك الوصول إلى هذه الصفحة. تواصل مع المسؤول إذا كنت تعتقد أن هذا خطأ.',
  accessForbiddenRoles: 'الأدوار الحالية',
  backToDashboard: 'العودة إلى لوحة التحكم',

  // Levels
  accessLevel: 'مستوى الوصول',
  accessLevelNone: 'بدون',
  accessLevelRead: 'قراءة',
  accessLevelUser: 'مستخدم',
  accessLevelManager: 'مدير',
  accessLevelCustom: 'مخصص',
  accessLevelNoneHelp: 'الوحدة مخفية وجميع إجراءاتها مرفوضة',
  accessLevelReadHelp: 'الاطلاع فقط',
  accessLevelUserHelp: 'الاطلاع والإنشاء والتعديل',
  accessLevelManagerHelp: 'تحكم كامل بما في ذلك الحذف',

  // Role editor
  roleAccessMatrix: 'مصفوفة الصلاحيات',
  roleAdvancedActions: 'الإجراءات التفصيلية',
  roleImplied: 'الأدوار الموروثة',
  roleImpliedHelp: 'يمنح هذا الدور أيضًا كل ما تمنحه الأدوار المحددة.',
  roleSystemBadge: 'دور النظام',
  roleSystemLocked: 'دور نظام: لا يمكن تغيير اسمه ولا حذفه.',
  roleSuperAdminHelp: 'يتجاوز جميع عمليات التحقق من الصلاحيات. للمسؤولين فقط.',
  roleEffectivePermissions: 'الصلاحيات الفعلية',
  roleInheritedFrom: 'موروث من {role}',
  roleNoModulesGranted: 'لم تُمنح أي وحدة',
  roleModulesGranted: '{count} وحدة ممنوحة',
  roleSyncCatalogue: 'مزامنة الكتالوج',
  roleSyncCatalogueDone: 'تمت مزامنة كتالوج الصلاحيات',
  roleCycleError: 'هذه التبعية ستُنشئ حلقة في تسلسل الأدوار',

  // User ↔ roles
  userRoles: 'الأدوار',
  userRolesHelp: 'يمكن للمستخدم الجمع بين عدة أدوار؛ صلاحياته هي اتحادها جميعًا.',
  userNoRoles: 'لم يتم تعيين أي دور',
  userRolesAssigned: '{count} دور',
  userSelfLockout: 'لا يمكنك إزالة دور المسؤول الخاص بك',

  // Categories
  accessCategory_general: 'عام',
  accessCategory_sales: 'المبيعات',
  accessCategory_purchases: 'المشتريات',
  accessCategory_accounting: 'المحاسبة',
  accessCategory_catalog: 'الكتالوج',
  accessCategory_contacts: 'جهات الاتصال',
  accessCategory_inventory: 'المخزون',
  accessCategory_delivery: 'التوصيل',
  accessCategory_reporting: 'التقارير',
  accessCategory_tools: 'الأدوات',
  accessCategory_settings: 'الإدارة',

  // Modules
  accessModule_dashboard: 'لوحة التحكم',
  accessModule_orders: 'الطلبات',
  accessModule_quotes: 'عروض الأسعار',
  accessModule_pos: 'نقطة البيع',
  accessModule_caisse: 'الصندوق',
  accessModule_invoices: 'فواتير العملاء',
  accessModule_payments: 'المدفوعات',
  accessModule_products: 'المنتجات',
  accessModule_categories: 'الفئات',
  accessModule_brands: 'العلامات التجارية',
  accessModule_partners: 'العملاء والموردون',
  accessModule_stock: 'المخزون',
  accessModule_warehouses: 'المستودعات',
  accessModule_uom: 'وحدات القياس',
  accessModule_delivery: 'التوصيل',
  accessModule_drive: 'الملفات',
  accessModule_images: 'الصور',
  accessModule_documents: 'إنشاء المستندات',
  accessModule_bulk: 'العمليات الجماعية',
  accessModule_notifications: 'الإشعارات',
  accessModule_configurations: 'الإعدادات',
  accessModule_sequences: 'تسلسلات المستندات',
  accessModule_printers: 'الطابعات',
  accessModule_users: 'المستخدمون',
  accessModule_roles: 'الأدوار والصلاحيات',
  accessModule_reports_sales: 'تقارير المبيعات',
  accessModule_reports_purchases: 'تقارير المشتريات',
  accessModule_reports_invoices: 'تقارير الفوترة',
  accessModule_reports_payments: 'تقارير المدفوعات',
  accessModule_reports_clients: 'تقارير العملاء',
  accessModule_reports_suppliers: 'تقارير الموردين',
  accessModule_reports_products: 'تقارير المنتجات',
  accessModule_reports_stock: 'تقارير المخزون',

  // Actions
  accessAction_view: 'الاطلاع',
  accessAction_create: 'الإنشاء',
  accessAction_edit: 'التعديل',
  accessAction_delete: 'الحذف',
  accessAction_export: 'التصدير',
  accessAction_import: 'الاستيراد',
  accessAction_validate: 'التأكيد',
  accessAction_cancel: 'الإلغاء',
  accessAction_convert: 'التحويل',
  accessAction_adjust: 'التسوية',
  accessAction_transfer: 'النقل',
  accessAction_assign: 'الإسناد',
  accessAction_upload: 'الرفع',
  accessAction_share: 'المشاركة',
  accessAction_send: 'الإرسال',
  accessAction_manage: 'الإدارة',
  accessAction_use: 'الاستخدام',
  accessAction_discount: 'منح التخفيضات',
  accessAction_refund: 'الاسترجاع',
  accessAction_generate: 'التوليد',
  accessAction_print: 'الطباعة',
  accessAction_open: 'فتح جلسة',
  accessAction_close: 'إغلاق الجلسة',

  // Preset role names
  accessRole_administrator: 'مسؤول',
  accessRole_sales_read: 'المبيعات — قراءة',
  accessRole_sales_user: 'المبيعات — مستخدم',
  accessRole_sales_manager: 'المبيعات — مدير',
  accessRole_purchase_user: 'المشتريات — مستخدم',
  accessRole_purchase_manager: 'المشتريات — مدير',
  accessRole_accounting_user: 'المحاسبة — مستخدم',
  accessRole_accounting_manager: 'المحاسبة — مدير',
  accessRole_inventory_user: 'المخزون — مستخدم',
  accessRole_inventory_manager: 'المخزون — مدير',
  accessRole_pos_operator: 'مشغّل الصندوق',
  accessRole_delivery_manager: 'مدير التوصيل',
  accessRole_readonly: 'قراءة فقط',

  // ─── Roles page ───────────────────────────────────────────
  rolesDescription: 'حدّد الأدوار وما يمكن لكل دور فعله في كل وحدة',
  permissionsCount: 'الصلاحيات',
  cannotDeleteSuperAdmin: 'لا يمكن حذف دور المسؤول',
  rolesCountLabel: 'أدوار',
  roleCountLabel: 'دور',
  noRolesFound: 'لم يتم العثور على أي دور',
  rolePermissionsShort: '{count} صلاحية',
  confirmDeleteRolesPlural: 'حذف {count} أدوار؟',
  permissionsMatrix: 'مصفوفة الصلاحيات',
  module: 'الوحدة',

  // ─── Module descriptions ──────────────────────────────────
  accessModuleDesc_dashboard: 'لوحة التحكم الرئيسية والإحصائيات الأساسية',
  accessModuleDesc_orders: 'طلبات العملاء وسطور الدفع الخاصة بها',
  accessModuleDesc_quotes: 'عروض أسعار البيع وطلبات أسعار الشراء',
  accessModuleDesc_pos: 'طرفية نقطة البيع',
  accessModuleDesc_caisse: 'جلسات الصندوق والتسوية',
  accessModuleDesc_invoices: 'فواتير البيع وإشعارات الدائن',
  accessModuleDesc_payments: 'مدفوعات العملاء والموردين',
  accessModuleDesc_products: 'كتالوج المنتجات والأسعار والمتغيرات',
  accessModuleDesc_categories: 'فئات المنتجات',
  accessModuleDesc_brands: 'العلامات التجارية للمنتجات',
  accessModuleDesc_partners: 'بطاقات الشركاء والعناوين وجهات الاتصال',
  accessModuleDesc_stock: 'مستويات المخزون والحركات والتسويات',
  accessModuleDesc_warehouses: 'المستودعات ومواقع التخزين',
  accessModuleDesc_uom: 'وحدات القياس والتحويلات',
  accessModuleDesc_delivery: 'عمال التوصيل والجولات وسندات التسليم',
  accessModuleDesc_drive: 'تخزين المستندات المشترك',
  accessModuleDesc_images: 'مكتبة الصور المستخدمة في المنتجات والمستندات',
  accessModuleDesc_documents: 'إنشاء ملفات PDF لعروض الأسعار والطلبات والفواتير',
  accessModuleDesc_bulk: 'الاستيراد والتصدير الجماعي عبر الوحدات',
  accessModuleDesc_notifications: 'الإشعارات داخل التطبيق والقوالب',
  accessModuleDesc_configurations: 'إعدادات الشركة والضرائب والعملات وشروط الدفع',
  accessModuleDesc_sequences: 'تسلسلات الترقيم لكل نوع مستند',
  accessModuleDesc_printers: 'الطابعات ومهام الطباعة',
  accessModuleDesc_users: 'حسابات مستخدمي لوحة الإدارة والبوابة',
  accessModuleDesc_roles: 'مجموعات الوصول والصلاحيات وإسناد الأدوار',
  accessModuleDesc_reports_sales: 'يوميات المبيعات وتحليل الإيرادات',
  accessModuleDesc_reports_purchases: 'يوميات المشتريات ومصروفات الموردين',
  accessModuleDesc_reports_invoices: 'أعمار الديون والأرصدة المستحقة والضريبة',
  accessModuleDesc_reports_payments: 'التدفق النقدي والحركات وطرق الدفع',
  accessModuleDesc_reports_clients: 'كشوف العملاء وأعمار الديون وأفضل العملاء',
  accessModuleDesc_reports_suppliers: 'كشوف الموردين وأعمار الديون',
  accessModuleDesc_reports_products: 'تحليل الهوامش وأداء المنتجات',
  accessModuleDesc_reports_stock: 'تقييم المخزون وسجل الحركات',

  // ─── Preset role descriptions ─────────────────────────────
  accessRoleDesc_administrator: 'وصول كامل إلى جميع الوحدات — يتجاوز جميع عمليات التحقق',
  accessRoleDesc_sales_read: 'اطلاع فقط على مسار المبيعات',
  accessRoleDesc_sales_user: 'إنشاء وإدارة مستندات البيع الخاصة',
  accessRoleDesc_sales_manager: 'تحكم كامل في المبيعات بما في ذلك الحذف والتقارير',
  accessRoleDesc_purchase_user: 'إصدار ومتابعة طلبات الموردين',
  accessRoleDesc_purchase_manager: 'تحكم كامل في المشتريات وتقارير الموردين',
  accessRoleDesc_accounting_user: 'تسجيل الفواتير والمدفوعات',
  accessRoleDesc_accounting_manager: 'تأكيد وإلغاء المستندات المحاسبية وإدارة الترقيم والإعدادات',
  accessRoleDesc_inventory_user: 'إدارة حركات المخزون اليومية',
  accessRoleDesc_inventory_manager: 'تحكم كامل في المخزون والكتالوج والمستودعات',
  accessRoleDesc_pos_operator: 'تشغيل نقطة البيع والصندوق',
  accessRoleDesc_delivery_manager: 'تخطيط الجولات وإسناد عمليات التوصيل',
  accessRoleDesc_readonly: 'اطلاع فقط على جميع الوحدات',
};
