export default {
  // App & Branding
  appName: 'Morocom',
  adminBackoffice: 'لوحة التحكم الإدارية',

  // Navigation
  dashboard: 'لوحة التحكم',
  welcomeBack: 'مرحباً بعودتك',
  welcome: 'مرحباً',
  goodMorning: 'صباح الخير',
  goodAfternoon: 'مساء الخير',
  goodEvening: 'مساء النور',

  // Common Actions
  create: 'إنشاء',
  update: 'تحديث',
  edit: 'تعديل',
  delete: 'حذف',
  save: 'حفظ',
  cancel: 'إلغاء',
  close: 'إغلاق',
  back: 'رجوع',
  confirm: 'تأكيد',
  add: 'إضافة',

  // Common Fields
  name: 'الاسم',
  code: 'الرمز',
  email: 'البريد الإلكتروني',
  phone: 'الهاتف',
  phoneNumber: 'رقم الهاتف',
  address: 'العنوان',
  status: 'الحالة',
  actions: 'الإجراءات',
  date: 'التاريخ',
  note: 'ملاحظة',
  description: 'الوصف',
  details: 'التفاصيل',
  customer: 'العميل',

  // Status
  active: 'نشط',
  inactive: 'غير نشط',
  enabled: 'مفعل',
  disabled: 'معطل',

  // Common Validation
  required: 'مطلوب',
  nameRequired: 'الاسم مطلوب',

  // Search & Filter
  search: 'بحث',

  // Pagination
  showing: 'عرض',
  to: 'إلى',
  of: 'من',
  results: 'نتيجة',
  perPage: 'لكل صفحة',
  first: 'الأولى',
  previous: 'السابق',
  next: 'التالي',
  last: 'الأخيرة',
  pageReportTemplate: '{first} - {last} من {totalRecords}',

  // Loading & States
  loading: 'جاري التحميل...',
  saving: 'جاري الحفظ',
  deleting: 'جاري الحذف',
  creating: 'جاري الإنشاء',
  generating: 'جاري التوليد...',
  downloading: 'جاري التحميل',
  downloaded: 'تم التحميل',
  failedToGenerate: 'فشل في التوليد',
  'common.loading': 'جاري التحميل...',
  'common.saving': 'جاري الحفظ...',
  'common.close': 'إغلاق',
  'common.cancel': 'إلغاء',

  // Selection
  selected: 'محدد',
  selectAll: 'تحديد الكل',
  deselectAll: 'إلغاء تحديد الكل',

  // General
  items: 'عناصر',
  item: 'عنصر',
  all: 'الكل',
  total: 'المجموع',

  // Currency
  currency: 'د.م',
  currencyCode: 'MAD',

  // Date Filters
  today: 'اليوم',
  yesterday: 'أمس',
  thisWeek: 'هذا الأسبوع',
  thisMonth: 'هذا الشهر',
  thisYear: 'هذا العام',
  lastWeek: 'الأسبوع الماضي',
  lastMonth: 'الشهر الماضي',
  lastYear: 'العام الماضي',
  selectDate: 'اختر تاريخاً',
  period: 'الفترة',
  selectDates: 'اختر التواريخ',
  start: 'البداية',
  end: 'النهاية',
  predefinedPeriod: 'فترة محددة مسبقاً',
  ok: 'موافق',

  // Confirmation
  areYouSure: 'هل أنت متأكد؟',
  actionCannotBeUndone: 'لا يمكن التراجع عن هذا الإجراء',

  // Dashboard
  quickAccess: 'وصول سريع',
  week: 'أسبوع',
  month: 'شهر',
  year: 'سنة',
  custom: 'مخصص',
  vsPeriod: 'مقارنةً بالفترة السابقة',

  // Language Toggle
  switchToFrench: 'Changer en français',
  switchToArabic: 'التبديل للعربية',

  // Error Messages
  error: 'حدث خطأ',
  errorPrefix: 'خطأ',
  failedToCreate: 'فشل الإنشاء',
  failedToUpdate: 'فشل التحديث',
  failedToDelete: 'فشل الحذف',
  useAuthError: 'يجب استخدام useAuth داخل AuthProvider',
  useLanguageError: 'يجب استخدام useLanguage داخل LanguageProvider',

  // Menu Items
  sales: 'المبيعات',
  purchases: 'المشتريات',
  quote: 'عرض أسعار',
  deliveryNote: 'مذكرة التسليم',
  salesInvoice: 'فاتورة المبيعات',
  payments: 'المدفوعات',
  clients: 'العملاء',
  priceRequest: 'طلب سعر',
  purchaseOrder: 'أمر شراء',
  purchaseInvoice: 'فاتورة الشراء',
  suppliers: 'الموردون',
  stockMovements: 'حركات المخزون',
  inventoryAdjustments: 'تسويات المخزون',
  warehouses: 'المستودعات',

  // Document Statuses
  paid: 'مدفوعة',
  partial: 'جزئية',
  pending: 'قيد الانتظار',
  overdue: 'متأخرة',
  unpaid: 'غير مدفوعة',
  open: 'مفتوح',
  signed: 'موقعة (للفوترة)',
  closed: 'غير موقعة (مغلقة)',
  invoiced: 'فوترت',
  validated: 'معتمدة',
  inProgress: 'قيد التنفيذ',
  delivered: 'تم التسليم',
  cancelled: 'ملغاة',
  draft: 'مسودة',
  confirmed: 'مؤكد',
  assigned: 'معين',
  done: 'تم',
  allTypes: 'جميع الأنواع',
  allStatuses: 'جميع الحالات',

  // Month Names (abbreviated)
  monthJan: 'يناير',
  monthFeb: 'فبراير',
  monthMar: 'مارس',
  monthApr: 'أبريل',
  monthMay: 'مايو',
  monthJun: 'يونيو',
  monthJul: 'يوليو',
  monthAug: 'أغسطس',
  monthSep: 'سبتمبر',
  monthOct: 'أكتوبر',
  monthNov: 'نوفمبر',
  monthDec: 'ديسمبر',

  // Full Month Names
  monthJanuary: 'يناير',
  monthFebruary: 'فبراير',
  monthMarch: 'مارس',
  monthApril: 'أبريل',
  monthMayFull: 'مايو',
  monthJune: 'يونيو',
  monthJuly: 'يوليو',
  monthAugust: 'أغسطس',
  monthSeptember: 'سبتمبر',
  monthOctober: 'أكتوبر',
  monthNovember: 'نوفمبر',
  monthDecember: 'ديسمبر',

  // Status Labels
  upToDate: 'محدث',
  pendingPayments: 'مدفوعات معلقة',
  allPaymentsUpToDate: 'جميع المدفوعات محدثة',
  invoicesIssuedPerMonth: 'عدد الفواتير الصادرة شهرياً',

  // Preview/Download
  previewPDF: 'معاينة PDF',
  downloadPDF: 'تحميل PDF',
  download: 'تحميل',
  generateLink: 'إنشاء رابط',

  // Confirmations
  confirmCancelMovement: 'هل أنت متأكد من إلغاء هذه الحركة؟',
  confirmRejectQuote: 'هل تريد حقاً رفض هذا العرض؟',
  searchByNumberOrName: 'ابحث برقم أو اسم',
  manageCompanyInformation: 'إدارة معلومات الشركة',
  newPasswordOptional: 'كلمة مرور جديدة (اختياري)',
  minCharacters: 'حد أدنى 6 أحرف',
  informationSavedSuccess: 'تم حفظ المعلومات بنجاح',
  errorSaving: 'خطأ أثناء الحفظ',
  errorGeneratingPDF: 'خطأ في إنشاء ملف PDF',
  pdfDownloaded: 'تم التحميل بنجاح',
  pdfDownloadedShort: 'تم التحميل',
  confirmDeletePayment: 'هل أنت متأكد من حذف هذا الدفع؟ هذا الإجراء لا رجعة فيه.',
  errorDeletingPayment: 'خطأ أثناء حذف الدفع',
  previewReceipt: 'معاينة الإيصال',
  previewDeliveryNote: 'معاينة وصل التسليم',
  iosInstallHint: 'للتثبيت على iOS، اضغط على مشاركة واختر "إضافة إلى الشاشة الرئيسية".',
  deleteError: 'خطأ في الحذف',
  exportSuccess: 'تم التصدير بنجاح',
  exportError: 'خطأ أثناء التصدير',
  templateDownloaded: 'تم تحميل النموذج بنجاح',
  templateDownloadError: 'خطأ أثناء تحميل النموذج',
  importInProgress: 'جاري الاستيراد...',
  importSuccess: 'تم الاستيراد: {{created}} تم إنشاؤها، {{updated}} تم تحديثها',
  importPartial:
    'اكتمل الاستيراد مع أخطاء: {{created}} تم إنشاؤها، {{updated}} تم تحديثها، {{failed}} فشلت',
  importError: 'خطأ أثناء الاستيراد',
  confirmBulkDelete:
    'هل أنت متأكد من حذف {{count}} عنصر(عناصر) محدد(ة)؟ لا يمكن التراجع عن هذا الإجراء.',
  deleteProducts: 'حذف المنتجات',
  unsupportedDocumentType: 'نوع المستند غير مدعوم',
  confirmDeleteCategory: 'هل أنت متأكد من حذف "{{name}}"؟',
  enterYourName: 'يرجى إدخال اسمك',
  errorSigningQuote: 'خطأ أثناء توقيع العرض',
  confirmRejectQuoteMessage: 'هل تريد حقاً رفض هذا العرض؟ سيتم تغيير حالته إلى مغلق.',
  rejectLabel: 'رفض',
  errorRejectingQuote: 'خطأ أثناء رفض العرض',
  failedToGenerateCode: 'فشل في إنشاء رمز المنتج الفريد',
  newCodeGenerated: 'تم إنشاء رمز منتج فريد جديد',
  failedToGenerateCodeRetry: 'فشل في إنشاء الرمز الفريد. يرجى المحاولة مرة أخرى.',
  productCreatedSuccess: 'تم إنشاء المنتج بنجاح',
  failedToCreateProduct: 'فشل في إنشاء المنتج',
  failedToUpdateProduct: 'فشل في تحديث المنتج',
  failedToCorrectStock: 'فشل في تصحيح المخزون',
  failedToTransferStock: 'فشل في نقل المخزون',
  errorCreating: 'خطأ أثناء الإنشاء',
  failedToCreateWarehouse: 'فشل في إنشاء المستودع',
  failedToUpdateWarehouse: 'فشل في تحديث المستودع',
  failedToDeleteWarehouse: 'فشل في حذف المستودع',
  deleteWarehouseTitle: 'حذف المستودع',
  confirmDeleteWarehouse: 'هل أنت متأكد من حذف هذا المستودع؟ لا يمكن التراجع عن هذا الإجراء.',
  noWarehousesFound: 'لا توجد مستودعات',
  noAddress: 'لا يوجد عنوان',
  createFirstWarehouse: 'أنشئ أول مستودع للبدء',
  tryDifferentSearch: 'جرب بحثاً مختلفاً',
  errorCreatingDocument: 'خطأ أثناء إنشاء المستند',
  errorUpdatingDocument: 'خطأ أثناء تحديث المستند',
  loadingQuote: 'جاري تحميل العرض...',
  errorLoadingQuote: 'خطأ أثناء تحميل العرض',
  quoteNotFound: 'العرض غير موجود',
  no: 'لا',

  // Image Upload
  invalidFileType: 'نوع ملف غير صالح. المسموح: JPEG، PNG، WebP',
  fileSizeExceeds: 'حجم الملف يتجاوز الحد الأقصى',
  uploadFailed: 'فشل التحميل',
  pleaseTryAgain: 'يرجى المحاولة مرة أخرى',
  imageUploadedSuccessfully: 'تم تحميل الصورة بنجاح',
  failedToConstructImageUrl: 'فشل في إنشاء عنوان URL للصورة',
  failedToRemoveImage: 'فشل في إزالة الصورة',
  productPreview: 'معاينة المנت',
  removeImage: 'إزالة الصورة',

  // Dashboard
  dashboardOverview: 'نظرة عامة على نشاطك',
  revenueTrend: 'اتجاه الإيرادات',
  last7Days: 'آخر 7 أيام',
  ordersDistribution: 'توزيع الطلبات',
  byStatus: 'حسب الحالة',
  salesComparison: 'مقارنة المبيعات',
  currentVsPrevious: 'الفترة الحالية مقابل السابقة',
  currentPeriod: 'الفترة الحالية',
  previousPeriod: 'الفترة السابقة',
  performanceMetrics: 'مؤشرات الأداء',
  keyIndicators: 'المؤشرات الرئيسية',
  avgOrderValue: 'متوسط قيمة الطلب',
  customerGrowth: 'نمو العملاء',
  conversionRate: 'معدل التحويل',
  recentActivity: 'النشاط الأخير',
  latestUpdates: 'آخر التحديثات',
  live: 'مباشر',
  viewAll: 'عرض الكل',
  newOrderReceived: 'تم استلام طلب جديد',
  newCustomer: 'عميل جديد',
  lowStock: 'مخزون منخفض',
  dailyGoal: 'الهدف اليومي',
  quickActions: 'إجراءات سريعة',
  getStartedQuickly: 'ابدأ بسرعة',
  newOrder: 'طلب جديد',
  viewOrders: 'عرض الطلبات',
  ordersAwaitingProcessing: 'طلبات في الانتظار',
  ordersInTransit: 'طلبات في الطريق',
  successfulDeliveries: 'التسليمات الناجحة',
  currentlyActive: 'نشط حالياً',
  revenue: 'الإيرادات',

  totalCustomers: 'إجمالي العملاء',
  topProducts: 'أفضل المنتجات',
  bestSellers: 'الأكثر مبيعاً',
  ordersTimeline: 'الجدول الزمني للطلبات',
  dailyOrdersFlow: 'تدفق الطلبات اليومي',
  newOrders: 'طلبات جديدة',
  secondsAgo: 'ثواني',
  minutesAgo: 'دقيقة',
  hoursAgo: 'ساعات',
  daysAgo: 'أيام',
  noRecentActivity: 'لا يوجد نشاط مؤخراً',

  // Common Actions
  validate: 'تأكيد',
  devalidate: 'إلغاء التأكيد',
  view: 'عرض',
  deleteTitle: 'حذف',
  validating: 'جاري...',
  modify: 'تعديل',
  remove: 'حذف',
  validateDocument: 'تأكيد المستند',
  devalidateDocument: 'إلغاء تأكيد المستند',

  // Document action bar
  moreActions: 'المزيد من الإجراءات',
  confirmDeleteDocument: 'هل أنت متأكد من حذف هذا المستند؟ لا يمكن التراجع عن هذا الإجراء.',
  documentDeleted: 'تم حذف المستند بنجاح',

  // Accessibility
  refresh: 'تحديث',
  moreOptions: 'خيارات إضافية',
  settings: 'الإعدادات',

  // General
  noItems: 'لا توجد عناصر',
  completed: 'مكتمل',
  type: 'النوع',

  // Search & empty states
  noResults: 'لا توجد نتائج',
  resetFilters: 'إعادة تعيين الفلاتر',

  // Common fields (extended)
  reference: 'المرجع',
  city: 'المدينة',
  zipCode: 'الرمز البريدي',
  select: 'اختر',
  qty: 'الكمية',
  totalWithTax: 'المجموع شامل الضريبة',

  // Common actions (extended)
  import: 'استيراد',
  export: 'تصدير',
  print: 'طباعة',
  share: 'مشاركة',
  copy: 'نسخ',
  copied: 'تم النسخ !',
  copyUrl: 'نسخ الرابط',
  new: 'جديد',

  // Upload
  imageLoadError: 'خطأ في تحميل الصورة',
  clickToChange: 'انقر لتغيير الصورة',
  clickOrDrag: 'انقر أو اسحب وأفلت',

  // Share
  shareLinkGenerated: 'تم إنشاء رابط المشاركة',
  shareLinkError: 'خطأ أثناء إنشاء رابط المشاركة',
  linkRevoked: 'تم إلغاء الرابط بنجاح',
  linkRevocationError: 'خطأ أثناء إلغاء الرابط',

  // Paginator
  paginatorReport: '{first}-{last} من {totalRecords}',

  // Navigation (mobile + sidebar)
  navBoard: 'Board',
  navInventory: 'المخزون',
  navMore: 'المزيد',
  navExpand: 'توسيع',
  navCollapse: 'طي',
  navTeam: 'الفريق',
  navPos: 'نقطة البيع',
  rolesPermissions: 'الأدوار والصلاحيات',

  // Stock / inventory
  negativeStock: 'مخزون سالب',
  zeroStock: 'مخزون صفري',
  positiveStock: 'مخزون موجب',
  inStock: 'في المخزون',

  // Documents
  shareLink: 'رابط المشاركة',
  preview: 'معاينة',
  linkExpires: 'ينتهي صلاحية هذا الرابط بتاريخ',
  shareQuote: 'مشاركة عرض الأسعار',
  shareInvoice: 'مشاركة الفاتورة',
  shareBL: 'مشاركة وصل التسليم',
  sendWhatsApp: 'إرسال عبر واتساب',
  revokeLink: 'إلغاء الرابط',
  backToPOS: 'العودة إلى نقطة البيع',
  orderSummary: 'ملخص الطلب',
  lines: 'البنود',

  // ── User Profile Menu ──
  myProfile: 'ملفي الشخصي',
  userSettings: 'الإعدادات',
  profileAndAccount: 'الملف الشخصي والحساب',
  editProfile: 'تعديل الملف الشخصي',
  profileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح',
  profileUpdateError: 'خطأ في تحديث الملف الشخصي',
  administrator: 'مسؤول النظام',
  fullName: 'الاسم الكامل',
  currentPassword: 'كلمة المرور الحالية',
  newPassword: 'كلمة المرور الجديدة',
  confirmPassword: 'تأكيد كلمة المرور',
  passwordsDoNotMatch: 'كلمتا المرور غير متطابقتين',
  leaveBlankToKeep: 'اتركه فارغاً لعدم التغيير',
  accountInfo: 'معلومات الحساب',
  securitySection: 'الأمان',
  changePassword: 'تغيير كلمة المرور',

  // ── User Settings Modal ──
  languageAndRegion: 'اللغة والمنطقة',
  selectLanguage: 'اختيار اللغة',
  french: 'الفرنسية',
  arabic: 'العربية',
  languageChanged: 'تم تغيير اللغة بنجاح',
  notificationPreferences: 'تفضيلات الإشعارات',
  notifAll: 'جميع الإشعارات',
  notifOrders: 'الطلبات الجديدة',
  notifPayments: 'المدفوعات والتحصيلات',
  notifStock: 'تنبيهات المخزون',
  notifSystem: 'إشعارات النظام',
  notifDelivery: 'تحديثات التوصيل',
  notifMarketing: 'العروض والأخبار',
  professionalSettings: 'الإعدادات المهنية',
  compactMode: 'الوضع المدمج',
  compactModeDesc: 'تقليل المسافات لعرض محتوى أكثر',
  autoSave: 'الحفظ التلقائي',
  autoSaveDesc: 'حفظ المسودات تلقائياً',
  showTutorials: 'عرض الأدلة التعليمية',
  showTutorialsDesc: 'عرض الأدلة التفاعلية والنصائح',
  defaultCurrency: 'العملة الافتراضية',
  dateFormat: 'تنسيق التاريخ',
  settingsSaved: 'تم حفظ الإعدادات',
  install: 'تثبيت',

  // Order payments
  paidAmount: 'المبلغ المدفوع',
  remainingAmount: 'المبلغ المتبقي',
  addPayment: 'إضافة دفعة',
  pay: 'دفع',
  paymentType: 'طريقة الدفع',
  paymentDate: 'تاريخ الدفع',
  paymentHistory: 'سجل المدفوعات',
  deletePayment: 'حذف الدفعة',
  optional: 'اختياري',
  notes: 'ملاحظات',

  // Dates
  createdAt: 'تاريخ الإنشاء',
  updatedAt: 'تاريخ التحديث',

  // ── Deletion guard error codes (returned by API) ─────────────────────────
  deletionBlocked: 'لا يمكن الحذف',
  PRODUCT_IN_INVOICES: 'هذا المنتج مستخدم في فواتير ولا يمكن حذفه.',
  PRODUCT_IN_ORDERS: 'هذا المنتج مستخدم في طلبات ولا يمكن حذفه.',
  PRODUCT_IN_QUOTES: 'هذا المنتج مستخدم في عروض أسعار ولا يمكن حذفه.',
  ORDER_VALIDATED: 'هذا الطلب مُعتمد. يرجى إلغاء اعتماده قبل الحذف.',
  ORDER_HAS_PAYMENTS: 'هذا الطلب مرتبط بمدفوعات ولا يمكن حذفه.',
  INVOICE_VALIDATED: 'هذه الفاتورة مُعتمدة. يرجى إلغاء اعتمادها قبل الحذف.',
  INVOICE_HAS_PAYMENTS: 'هذه الفاتورة مرتبطة بمدفوعات ولا يمكن حذفها.',
  QUOTE_VALIDATED: 'هذا العرض مُعتمد. يرجى إلغاء اعتماده قبل الحذف.',
  QUOTE_CONVERTED_TO_INVOICE: 'تم تحويل هذا العرض إلى فاتورة ولا يمكن حذفه.',
  PARTNER_HAS_DOCUMENTS:
    'هذا الشريك مرتبط بطلبات أو فواتير أو عروض أسعار ولا يمكن حذفه.',
  DELIVERY_PERSON_HAS_ORDERS: 'هذا المندوب مخصص لطلبات نشطة ولا يمكن حذفه.',
  CATEGORY_HAS_CHILDREN: 'هذه الفئة تحتوي على فئات فرعية ولا يمكن حذفها.',
  CATEGORY_HAS_PRODUCTS: 'هذه الفئة مخصصة لمنتجات ولا يمكن حذفها.',
  WAREHOUSE_HAS_PRODUCTS: 'هذا المستودع مخصص لمنتجات ولا يمكن حذفه.',
};

