export default {
  // Configurations Main Page
  configurations: 'التكوينات',
  manageSystemConfigurations: 'إدارة تكوينات النظام',
  backToDashboard: 'العودة للوحة التحكم',
  
  // Configuration Modules
  taxes: 'الضرائب',
  currencies: 'العملات',
  paymentTerms: 'شروط الدفع',
  
  // Module Descriptions
  manageTaxRatesDescription: 'إدارة معدلات الضرائب والإعدادات الافتراضية',
  manageCurrenciesDescription: 'تكوين العملات المدعومة والعملة الافتراضية',
  managePaymentTermsDescription: 'إعداد شروط الدفع ومواعيد الاستحقاق',
  
  // Tax Rates
  taxRates: 'معدلات الضرائب',
  manageTaxRatesAndSettings: 'إدارة معدلات الضرائب والإعدادات الافتراضية',
  searchTaxRates: 'البحث في معدلات الضرائب...',
  addTaxRate: 'إضافة معدل ضريبة',
  editTaxRate: 'تعديل معدل الضريبة',
  
  // Currencies
  manageSupportedCurrencies: 'إدارة العملات المدعومة',
  searchCurrencies: 'البحث في العملات...',
  addCurrency: 'إضافة عملة',
  editCurrency: 'تعديل العملة',
  
  // Payment Terms
  configurePaymentTermsAndDueDates: 'تكوين شروط الدفع ومواعيد الاستحقاق',
  searchPaymentTerms: 'البحث في شروط الدفع...',
  addPaymentTerm: 'إضافة شرط دفع',
  editPaymentTerm: 'تعديل شرط الدفع',
  
  // Common Fields
  rate: 'المعدل',
  symbol: 'الرمز',
  code: 'الرمز',
  label: 'التسمية',
  days: 'الأيام',
  key: 'المفتاح',
  default: 'افتراضي',
  
  // Common Actions
  retour: 'العودة',
  
  // Form Labels
  taxRateName: 'اسم المعدل',
  taxRateValue: 'المعدل (%)',
  setAsDefault: 'تعيين كافتراضي',
  currencyCode: 'رمز العملة',
  currencyName: 'اسم العملة',
  currencySymbol: 'رمز العملة',
  termKey: 'مفتاح الشرط',
  termLabel: 'تسمية الشرط',
  termDays: 'عدد الأيام',
  
  // Validation Messages
  nameRequired: 'الاسم مطلوب',
  rateRequired: 'المعدل مطلوب',
  codeRequired: 'الرمز مطلوب',
  symbolRequired: 'الرمز مطلوب',
  labelRequired: 'التسمية مطلوبة',
  keyRequired: 'المفتاح مطلوب',
  daysRequired: 'عدد الأيام مطلوب',
  
  // Success Messages
  taxRateCreated: 'تم إنشاء معدل الضريبة بنجاح',
  taxRateUpdated: 'تم تحديث معدل الضريبة بنجاح',
  taxRateDeleted: 'تم حذف معدل الضريبة بنجاح',
  currencyCreated: 'تم إنشاء العملة بنجاح',
  currencyUpdated: 'تم تحديث العملة بنجاح',
  currencyDeleted: 'تم حذف العملة بنجاح',
  paymentTermCreated: 'تم إنشاء شرط الدفع بنجاح',
  paymentTermUpdated: 'تم تحديث شرط الدفع بنجاح',
  paymentTermDeleted: 'تم حذف شرط الدفع بنجاح',
    // Table Headers
  name: 'الاسم',
  status: 'الحالة',
  actions: 'الإجراءات',
  
  // Empty States
  noTaxRatesConfigured: 'لا توجد معدلات ضرائب مكونة. انقر على "إضافة معدل ضريبة" لإنشاء واحد.',
  noCurrenciesConfigured: 'لا توجد عملات مكونة. انقر على "إضافة عملة" لإنشاء واحدة.',
  noPaymentTermsConfigured: 'لا توجد شروط دفع مكونة. انقر على "إضافة شرط دفع" لإنشاء واحد.',
  
  // Form Labels and Placeholders
  ratePercentage: 'المعدل (%)',
  currencyCodePlaceholder: 'USD',
  currencyNamePlaceholder: 'الدولار الأمريكي',
  currencySymbolPlaceholder: '$',
  paymentTermLabelPlaceholder: 'صافي 30',
  paymentTermKeyPlaceholder: 'net_30',
  setAsDefaultTaxRate: 'تعيين كمعدل ضريبة افتراضي',
  setAsDefaultCurrency: 'تعيين كعملة افتراضية',
  setAsDefaultPaymentTerm: 'تعيين كشرط دفع افتراضي',
  
  // Form Help Text
  lowercaseWithUnderscores: 'أحرف صغيرة مع الشرطة السفلية (مثال: net_30)',
  autoGeneratedFromLabel: 'يتم إنشاؤه تلقائيًا من التسمية',
  numberOfDaysUntilDue: 'عدد الأيام حتى استحقاق الدفع',
  
  // Button States
  cancel: 'إلغاء',
  save: 'حفظ',
  saving: 'جارٍ الحفظ...',
  
  // Status Labels
  default: 'افتراضي',
  daysLabel: 'أيام',
    // Confirmation Messages
  confirmDeleteTaxRate: 'هل أنت متأكد من حذف معدل الضريبة هذا؟',
  confirmDeleteCurrency: 'هل أنت متأكد من حذف هذه العملة؟',
  confirmDeletePaymentTerm: 'هل أنت متأكد من حذف شرط الدفع هذا؟',
};