export default {
  // Configurations Main Page
  configurations: 'التكوينات',
  manageSystemConfigurations: 'إدارة تكوينات النظام',
  backToDashboard: 'العودة للوحة التحكم',

  // Configuration Modules
  taxes: 'الضرائب',
  currencies: 'العملات',
  paymentTerms: 'شروط الدفع',
  sequences: 'التسلسلات',

  // Module Descriptions
  manageTaxRatesDescription: 'إدارة معدلات الضرائب والإعدادات الافتراضية',
  manageCurrenciesDescription: 'تكوين العملات المدعومة والعملة الافتراضية',
  managePaymentTermsDescription: 'تكوين شروط الدفع والاستحقاقات',
  manageSequencesDescription: 'إدارة تسلسل ترقيم المستندات',

  // Tax Rates
  taxRates: 'معدلات الضرائب',
  manageTaxRatesAndSettings: 'إدارة معدلات الضرائب والإعدادات الافتراضية',
  searchTaxRates: 'البحث في معدلات الضرائب...',
  addTaxRate: 'إضافة معدل ضريبة',
  editTaxRate: 'تعديل معدل الضريبة',

  // Currencies
  manageSupportedCurrencies: 'إدارة العملات المدعومة',
  searchCurrencies: 'البحث في العملات...',
  addCurrency: 'إضافة عملة',
  editCurrency: 'تعديل العملة',

  // Payment Terms
  configurePaymentTermsAndDueDates: 'تكوين شروط الدفع ومواعيد الاستحقاق',
  searchPaymentTerms: 'البحث في شروط الدفع...',
  addPaymentTerm: 'إضافة شرط دفع',
  editPaymentTerm: 'تعديل شرط الدفع',

  // Common Fields
  rate: 'المعدل',
  symbol: 'الرمز',
  code: 'الرمز',
  label: 'التسمية',
  days: 'الأيام',
  key: 'المفتاح',
  default: 'افتراضي',

  // Common Actions
  retour: 'العودة',

  // Form Labels
  taxRateName: 'اسم المعدل',
  taxRateValue: 'المعدل (%)',
  setAsDefault: 'تعيين كافتراضي',
  currencyCode: 'رمز العملة',
  currencyName: 'اسم العملة',
  currencySymbol: 'رمز العملة',
  termKey: 'مفتاح الشرط',
  termLabel: 'تسمية الشرط',
  termDays: 'عدد الأيام',

  // Validation Messages
  nameRequired: 'الاسم مطلوب',
  rateRequired: 'المعدل مطلوب',
  codeRequired: 'الرمز مطلوب',
  symbolRequired: 'الرمز مطلوب',
  labelRequired: 'التسمية مطلوبة',
  keyRequired: 'المفتاح مطلوب',
  daysRequired: 'عدد الأيام مطلوب',

  // Success Messages
  taxRateCreated: 'تم إنشاء معدل الضريبة بنجاح',
  taxRateUpdated: 'تم تحديث معدل الضريبة بنجاح',
  taxRateDeleted: 'تم حذف معدل الضريبة بنجاح',
  currencyCreated: 'تم إنشاء العملة بنجاح',
  currencyUpdated: 'تم تحديث العملة بنجاح',
  currencyDeleted: 'تم حذف العملة بنجاح',
  paymentTermCreated: 'تم إنشاء شرط الدفع بنجاح',
  paymentTermUpdated: 'تم تحديث شرط الدفع بنجاح',
  paymentTermDeleted: 'تم حذف شرط الدفع بنجاح',
  // Table Headers
  name: 'الاسم',
  status: 'الحالة',
  actions: 'الإجراءات',

  // Empty States
  noTaxRatesConfigured: 'لا توجد معدلات ضرائب مكونة. انقر على "إضافة معدل ضريبة" لإنشاء واحد.',
  noCurrenciesConfigured: 'لا توجد عملات مكونة. انقر على "إضافة عملة" لإنشاء واحدة.',
  noPaymentTermsConfigured: 'لا توجد شروط دفع مكونة. انقر على "إضافة شرط دفع" لإنشاء واحد.',

  // Form Labels and Placeholders
  ratePercentage: 'المعدل (%)',
  currencyCodePlaceholder: 'USD',
  currencyNamePlaceholder: 'الدولار الأمريكي',
  currencySymbolPlaceholder: '$',
  paymentTermLabelPlaceholder: 'صافي 30',
  paymentTermKeyPlaceholder: 'net_30',
  setAsDefaultTaxRate: 'تعيين كمعدل ضريبة افتراضي',
  setAsDefaultCurrency: 'تعيين كعملة افتراضية',
  setAsDefaultPaymentTerm: 'تعيين كشرط دفع افتراضي',

  // Form Help Text
  lowercaseWithUnderscores: 'أحرف صغيرة مع الشرطة السفلية (مثال: net_30)',
  autoGeneratedFromLabel: 'يتم إنشاؤه تلقائيًا من التسمية', nextNumberAutoManaged: 'يُدار تلقائياً بواسطة النظام', numberOfDaysUntilDue: 'عدد الأيام حتى استحقاق الدفع',

  // Button States
  cancel: 'إلغاء',
  save: 'حفظ',
  saving: 'جارٍ الحفظ...',

  // Status Labels
  daysLabel: 'أيام',
  // Confirmation Messages
  confirmDeleteTaxRate: 'هل أنت متأكد من حذف معدل الضريبة هذا؟',
  confirmDeleteCurrency: 'هل أنت متأكد من حذف هذه العملة؟',
  confirmDeletePaymentTerm: 'هل أنت متأكد من حذف شرط الدفع هذا؟',

  // Sequences
  manageDocumentSequences: 'إدارة تسلسل ترقيم المستندات',
  searchSequences: 'البحث في التسلسلات...',
  addSequence: 'إضافة تسلسل',
  editSequence: 'تعديل التسلسل',
  entityType: 'نوع المستند',
  format: 'التنسيق',
  nextDocumentNumber: 'رقم المستند التالي',
  nextNumber: 'الرقم التالي',
  numberLength: 'طول الرقم',
  resetPeriod: 'فترة إعادة التعيين',
  dateFormat: 'تنسيق التاريخ',
  prefix: 'البادئة',
  suffix: 'اللاحقة',
  includeYearInPrefix: 'تضمين السنة في البادئة',
  includeMonthInPrefix: 'تضمين الشهر في البادئة',
  includeDayInPrefix: 'تضمين اليوم في البادئة',
  includeTrimesterInPrefix: 'تضمين الربع في البادئة',
  isActive: 'نشط',
  active: 'نشط',
  inactive: 'غير نشط',
  preview: 'معاينة',
  resetSequence: 'إعادة تعيين',

  // Entity Types
  invoiceSale: 'فاتورة بيع',
  invoicePurchase: 'فاتورة شراء',
  quote: 'عرض أسعار',
  deliveryNote: 'سند تسليم',
  priceRequest: 'طلب أسعار',
  purchaseOrder: 'أمر شراء',
  payment: 'دفعة',
  creditNote: 'إشعار دائن',
  receipt: 'إيصال',

  // Reset Periods
  never: 'أبداً',
  yearly: 'سنوياً',
  monthly: 'شهرياً',
  daily: 'يومياً',

  // Date Formats
  none: 'لا شيء',

  // Placeholders
  sequenceNamePlaceholder: 'اسم التسلسل',

  // Empty States
  noSequencesConfigured: 'لا توجد تسلسلات مكونة. انقر على "إضافة تسلسل" لإنشاء واحد.',

  // Confirmation Messages
  confirmDeleteSequence: 'هل أنت متأكد من حذف التسلسل هذا؟',
  confirmResetSequence: 'هل أنت متأكد من إعادة تعيين التسلسل هذا؟',

  // Database Integration
  exampleOnly: 'مثال فقط',
  actualNextNumber: 'الرقم التالي الفعلي',
  basedOnDatabaseRecords: 'بناءً على سجلات قاعدة البيانات',

  // ISequence Protection
  cannotEditUsedSequence: 'لا يمكن تعديل هذا التسلسل لأنه تم إنشاء فواتير باستخدامه',
  sequenceInUseWarning: 'هذا التسلسل مستخدم ولا يمكن تعديله. يرجى إنشاء تسلسل جديد إذا كنت بحاجة إلى تعديلات.',
  sequenceInUseReadonly: 'هذا التسلسل مستخدم بالفعل من قبل الفواتير ولا يمكن تعديله. الحقول للقراءة فقط.',
  edit: 'تعديل',
  // Warehouses
  warehouses: 'المستودعات',
  warehouse: 'مستودع',
  manageWarehouses: 'إدارة المستودعات',
  addWarehouse: 'إضافة مستودع',
  editWarehouse: 'تعديل المستودع',
  deleteWarehouse: 'حذف المستودع',
  mainWarehouse: 'المستودع الرئيسي',
  warehouseCreated: 'تم إنشاء المستودع بنجاح',
  warehouseUpdated: 'تم تحديث المستودع بنجاح',
  warehouseDeleted: 'تم حذف المستودع بنجاح',

  // Stock Movements
  stockMovements: 'حركات المخزون',
  movementValidated: 'تم التحقق من الحركة بنجاح',
  movementCancelled: 'تم إلغاء الحركة',
  'movementTypes.receipt': 'استلام',
  'movementTypes.delivery': 'تسليم',
  'movementTypes.internal': 'تحويل',
  'movementTypes.adjustment': 'تسوية',
  'movementTypes.productionIn': 'إنتاج (دخول)',
  'movementTypes.productionOut': 'إنتاج (خروج)',
  'movementTypes.scrap': 'التخريد',
  'movementTypes.returnIn': 'مرتجع من العميل',
  'movementTypes.returnOut': 'مرتجع للمورد',
  searchByReferenceOrProduct: 'البحث بالمرجع أو المنتج...',
  stockMovementsSubtitle: 'تتبع وإدارة جميع حركات المخزون',
  noMovementsFound: 'لا توجد حركات',
  validateMovement: 'تأكيد',
  cancelMovement: 'إلغاء',
  movementDetails: 'تفاصيل',

  // Warehouses - English Labels
  manageWarehousesSubtitle: 'إدارة مستودعاتك ومرافق التخزين',
  searchWarehouses: 'البحث عن مستودعات...',
  deleteWarehouseTitle: 'حذف المستودع', warehouseCode: 'WH-001', warehouseNamePlaceholder: 'المستودع الرئيسي',
  locationPlaceholder: 'الدار البيضاء',

  // Inventory Adjustments
  inventoryAdjustments: 'تعديلات المخزون',
  manageInventoryAdjustments: 'إدارة التعديلات والجرد',
  searchByReference: 'البحث بالمرجع أو الاسم...',
  countingStartedSuccess: 'تم بدء العد بنجاح',
  adjustmentValidatedSuccess: 'تم التحقق من التعديل بنجاح',
  adjustmentCancelled: 'تم إلغاء التعديل',
  adjustmentDeleted: 'تم حذف التعديل',
  confirmDeleteAdjustment: 'هل أنت متأكد من أنك تريد حذف هذا التعديل؟',
  newAdjustment: 'تعديل جديد',
  noAdjustmentsFound: 'لم يتم العثور على تعديلات',
  createFirstAdjustment: 'أنشئ تعديل المخزون الأول',
  draft: 'مسودة',
  inProgress: 'قيد التقدم',
  validated: 'تم التحقق',
  cancelled: 'ملغى',

  // Units of Measure
  unitsOfMeasure: 'وحدات القياس',
  manageUomDescription: 'إدارة وحدات القياس للمخزون',
  addUom: 'إضافة وحدة قياس',
  editUom: 'تعديل وحدة القياس',
  searchUom: 'البحث بالاسم أو الرمز...',
  noUomFound: 'لم يتم العثور على وحدات قياس',
  confirmDeleteUom: 'هل أنت متأكد من حذف وحدة القياس هذه؟',
  baseUnit: 'وحدة أساسية',
  isBaseUnit: 'هذه وحدة أساسية',
  selectBaseUnit: 'اختر وحدة أساسية',
  derived: 'مشتقة',
  ratio: 'النسبة',
  ratioHelp: '1 هذه الوحدة = X وحدة أساسية',
  rounding: 'التقريب',
  roundingPrecision: 'دقة التقريب',
  allCategories: 'جميع الفئات',

  // Inventory Settings
  inventorySettings: 'إعدادات المخزون',
  inventorySettingsSubtitle: 'تكوين حركات المخزون التلقائية',
  incrementStock: 'زيادة المخزون',
  decrementStock: 'تخفيض المخزون',
  noAutomaticMovement: 'لا توجد حركة تلقائية',
  defaultWarehouse: 'المستودع الافتراضي',
  selectDefaultWarehouse: 'اختر مستودعاً افتراضياً',
  stockMovementAutomation: 'أتمتة حركات المخزون',
  incrementOnInvoiceAchat: 'زيادة المخزون عند التحقق من فاتورة شراء',
  decrementOnInvoiceVente: 'تخفيض المخزون عند التحقق من فاتورة بيع',
  incrementOnOrderAchat: 'زيادة المخزون عند التحقق من أمر شراء',
  decrementOnOrderVente: 'تخفيض المخزون عند التحقق من وصل تسليم',
  inventorySettingsSaved: 'تم حفظ إعدادات المخزون',
  noWarehouseConfigured: 'لم يتم تكوين مستودع افتراضي. لن يتم إنشاء حركات المخزون.',

  // Module tab labels
  tabOverview: 'نظرة عامة',
  tabTeam: 'الفريق',
  tabInventoryConfig: 'المخزون',
  tabCompany: 'الشركة',
  units: 'الوحدات',
  roles: 'الأدوار',
};