export default {
  // Invoices Main
  'invoice.title': 'الفواتير',
  'invoice.subtitle': 'إدارة الفواتير والمدفوعات',
  'invoice.create': 'إنشاء فاتورة',
  'invoice.number': 'رقم الفاتورة',
  'invoice.customer': 'العميل',
  'invoice.date': 'التاريخ',
  'invoice.dueDate': 'تاريخ الاستحقاق',
  'invoice.amount': 'المبلغ',
  'invoice.paid': 'المدفوع',
  'invoice.status': 'الحالة',
  'invoice.payment': 'الدفع',
  'invoice.actions': 'الإجراءات',
  'invoice.noInvoices': 'لا توجد فواتير',
  
  // Search & Filters
  'invoice.searchPlaceholder': 'ابحث برقم الفاتورة أو العميل...',
  'invoice.filterStatus': 'تصفية حسب الحالة',
  'invoice.filterPayment': 'تصفية حسب الدفع',
  'invoice.allStatuses': 'كل الحالات',
  'invoice.allPayments': 'كل المدفوعات',
  'invoice.clearFilters': 'مسح الفلاتر',
  
  // Selection
  'invoice.selectedCount': '{count} محدد',
  'invoice.deleteSelected': 'حذف المحدد',
  'invoice.clearSelection': 'مسح التحديد',
  
  // Items
  'invoice.items': 'العناصر',
  'invoice.product': 'المنتج',
  'invoice.quantity': 'الكمية',
  'invoice.unitPrice': 'السعر',
  'invoice.discount': 'الخصم',
  'invoice.tax': 'الضريبة',
  'invoice.total': 'المجموع',
  'invoice.subtotal': 'المجموع الفرعي',
  'invoice.remaining': 'المتبقي',
  'invoice.note': 'ملاحظة',
  'invoice.terms': 'الشروط',
  
  // Details
  'invoice.viewDetails': 'عرض تفاصيل الفاتورة',
  'invoice.customerInfo': 'معلومات العميل',
  'invoice.invoiceInfo': 'معلومات الفاتورة',
  'invoice.download': 'تحميل',
  
  // Payment
  'invoice.recordPayment': 'تسجيل دفعة',
  'invoice.paymentAmount': 'مبلغ الدفع',
  'invoice.paymentRecorded': 'تم تسجيل الدفعة بنجاح',
  'invoice.paymentError': 'فشل تسجيل الدفعة',
  'invoice.invalidAmount': 'مبلغ غير صحيح',
  'invoice.quickAmounts': 'مبالغ سريعة',
  'invoice.payInFull': 'دفع كامل',
  'invoice.recording': 'جاري التسجيل',
  'invoice.amountMustBePositive': 'يجب أن يكون المبلغ أكبر من الصفر',
  'invoice.paymentExceedsRemaining': 'المبلغ يتجاوز المتبقي',
  'invoice.paymentHistory': 'سجل المدفوعات',
  'invoice.payments': 'المدفوعات',
  'invoice.noPayments': 'لا توجد مدفوعات',
  'invoice.noMethod': 'لا توجد طريقة',
  
  // Delete
  'invoice.deleteSuccess': 'تم حذف الفاتورة بنجاح',
  'invoice.deleteError': 'فشل حذف الفاتورة',
  'invoice.confirmBulkDelete': 'هل أنت متأكد من حذف {count} فاتورة؟',
  'invoice.deleteConfirm': 'تأكيد الحذف',
  'invoice.deleteConfirmMessage': 'هل أنت متأكد من حذف هذه الفاتورة؟ لا يمكن التراجع عن هذا الإجراء.',
  
  // Status Updates
  'invoice.statusUpdated': 'تم تحديث الحالة بنجاح',
  'invoice.statusError': 'فشل تحديث الحالة',
  'invoice.markAsSent': 'تحديد كمرسلة',
  'invoice.markAsPaid': 'تحديد كمدفوعة',
  'invoice.cancel': 'إلغاء',
  
  // Status Values
  'invoice.status.draft': 'مسودة',
  'invoice.status.sent': 'مرسلة',
  'invoice.status.paid': 'مدفوعة',
  'invoice.status.overdue': 'متأخرة',
  'invoice.status.cancelled': 'ملغاة',
  
  // Payment Status Values
  'invoice.paymentStatus.unpaid': 'غير مدفوعة',
  'invoice.paymentStatus.partial': 'مدفوعة جزئياً',
  'invoice.paymentStatus.paid': 'مدفوعة',
  
  // Statistics
  'invoice.stats.total': 'إجمالي الفواتير',
  'invoice.stats.totalAmount': 'المبلغ الإجمالي',
  'invoice.stats.paid': 'المدفوع',
  'invoice.stats.unpaid': 'غير المدفوع',
  'invoice.stats.overdue': 'المتأخر',
  'invoice.overdue': 'متأخرة',
  
  // Additional Fields
  'invoice.createdAt': 'تاريخ الإنشاء',
  'invoice.issueDate': 'تاريخ الإصدار',
  'invoice.taxRate': 'معدل الضريبة',
  'invoice.notes': 'ملاحظات',
  'invoice.information': 'معلومات الفاتورة',
  'invoice.noCustomer': 'لا يوجد عميل',
  'invoice.noItems': 'لا توجد عناصر',
  
  // Create/Edit Invoice
  'invoice.customerRequired': 'العميل مطلوب',
  'invoice.validItemsRequired': 'عناصر صالحة مطلوبة',
  'invoice.createSubtitle': 'إنشاء فاتورة جديدة للعميل',
  'invoice.selectCustomer': 'اختر العميل',
  'invoice.addItem': 'إضافة عنصر',
  'invoice.productName': 'اسم المنتج',
  'invoice.itemDescription': 'وصف العنصر',
  'invoice.notesPlaceholder': 'أي ملاحظات أو تعليمات خاصة...',
  'invoice.createSuccess': 'تم إنشاء الفاتورة بنجاح',
  'invoice.createError': 'فشل في إنشاء الفاتورة',
  'invoice.noMatchingInvoices': 'لا توجد فواتير مطابقة للمرشحات المحددة',
  'invoice.getStarted': 'ابدأ بإنشاء فاتورتك الأولى',
  'invoice.basicInfo': 'المعلومات الأساسية',
  'invoice.searchProduct': 'ابحث عن منتج...',
  'invoice.openCatalog': 'فتح الكتالوج',
  'invoice.productCatalog': 'كتالوج المنتجات',
  'invoice.saveDraft': 'حفظ كمسودة',
  'invoice.createAndSend': 'إنشاء وإرسال',
  'invoice.edit': 'تعديل الفاتورة',
  'invoice.editSubtitle': 'تعديل تفاصيل الفاتورة',
  'invoice.totalHT': 'المجموع ب.ض',
  
  // Customer Info
  'customer.information': 'معلومات العميل',
  
  // Form Labels
  'invoice.partnerNamePlaceholder': 'اسم {partner}',
  'invoice.phoneLabel': 'هاتف:',
  'invoice.addressLabel': 'العنوان:',
  'invoice.searchPlaceholderPartner': 'بحث...',
  'invoice.noPartnerFound': 'لا يوجد {partner}',
  'invoice.iceLabel': 'ICE',
  'invoice.deliveryAddressLabel': 'عنوان التسليم',
  'invoice.dateRequired': 'التاريخ *',
  'invoice.dueDateLabel': 'تاريخ الاستحقاق',
  'invoice.paymentTermsLabel': 'شروط الدفع',
  'invoice.paymentTermsPlaceholder': 'مثال: الدفع خلال 30 يوم',
  'invoice.articlesTitle': 'العناصر',
  'invoice.addLine': 'إضافة سطر',
  'invoice.descriptionHeader': 'الوصف',
  'invoice.quantityHeader': 'الكمية',
  'invoice.unitPriceHeader': 'السعر',
  'invoice.discountHeader': 'الخصم',
  'invoice.totalHeader': 'المجموع',
  'invoice.itemDescriptionPlaceholder': 'وصف العنصر',
  'invoice.productSearchPlaceholder': 'ابحث عن منتج...',
  'invoice.noProductsFound': 'لا توجد منتجات',
  'invoice.percentage': 'النسبة',
  'invoice.discountTypeAmount': 'المبلغ',
  'invoice.discountTypePercentage': '%',
  'invoice.summary': 'الملخص',
  'invoice.globalDiscount': 'الخصم الإجمالي',
  'invoice.globalDiscountPlaceholder': 'الخصم',
  'invoice.globalTax': 'الضريبة الإجمالية',
  'invoice.globalTaxPlaceholder': 'الضريبة (%)',
  'invoice.notesLabel': 'ملاحظات',
  'invoice.supplier': 'المورد',
};
