export default {
  // Invoices Main
  'invoice.title': 'الفواتير',
  'invoice.subtitle': 'إدارة الفواتير والمدفوعات',
  'invoice.create': 'إنشاء فاتورة',
  'invoice.number': 'رقم الفاتورة',
  'invoice.customer': 'العميل',
  'invoice.date': 'التاريخ',
  'invoice.dueDate': 'تاريخ الاستحقاق',
  'invoice.amount': 'المبلغ',
  'invoice.paid': 'المدفوع',
  'invoice.status': 'الحالة',
  'invoice.payment': 'الدفع',
  'invoice.actions': 'الإجراءات',
  'invoice.noInvoices': 'لا توجد فواتير',

  // Search & Filters
  'invoice.searchPlaceholder': 'ابحث برقم الفاتورة أو العميل...',
  'invoice.filterStatus': 'تصفية حسب الحالة',
  'invoice.filterPayment': 'تصفية حسب الدفع',
  'invoice.allStatuses': 'كل الحالات',
  'invoice.allPayments': 'كل المدفوعات',
  'invoice.clearFilters': 'مسح الفلاتر',

  // Selection
  'invoice.selectedCount': '{count} محدد',
  'invoice.deleteSelected': 'حذف المحدد',
  'invoice.clearSelection': 'مسح التحديد',

  // Items
  'invoice.items': 'العناصر',
  'invoice.product': 'المنتج',
  'invoice.quantity': 'الكمية',
  'invoice.unitPrice': 'السعر',
  'invoice.discount': 'الخصم',
  'invoice.tax': 'الضريبة',
  'invoice.total': 'المجموع',
  'invoice.subtotal': 'المجموع الفرعي',
  'invoice.remaining': 'المتبقي',
  'invoice.note': 'ملاحظة',
  'invoice.terms': 'الشروط',

  // Details
  'invoice.viewDetails': 'عرض تفاصيل الفاتورة',
  'invoice.customerInfo': 'معلومات العميل',
  'invoice.invoiceInfo': 'معلومات الفاتورة',
  'invoice.download': 'تحميل',

  // Payment
  'invoice.recordPayment': 'تسجيل دفعة',
  'invoice.paymentAmount': 'مبلغ الدفع',
  'invoice.paymentRecorded': 'تم تسجيل الدفعة بنجاح',
  'invoice.paymentError': 'فشل تسجيل الدفعة',
  'invoice.invalidAmount': 'مبلغ غير صحيح',
  'invoice.quickAmounts': 'مبالغ سريعة',
  'invoice.payInFull': 'دفع كامل',
  'invoice.recording': 'جاري التسجيل',
  'invoice.amountMustBePositive': 'يجب أن يكون المبلغ أكبر من الصفر',
  'invoice.paymentExceedsRemaining': 'المبلغ يتجاوز المتبقي',
  'invoice.paymentHistory': 'سجل المدفوعات',
  'invoice.payments': 'المدفوعات',
  'invoice.noPayments': 'لا توجد مدفوعات',
  'invoice.noMethod': 'لا توجد طريقة',

  // Delete
  'invoice.deleteSuccess': 'تم حذف الفاتورة بنجاح',
  'invoice.deleteError': 'فشل حذف الفاتورة',
  'invoice.confirmBulkDelete': 'هل أنت متأكد من حذف {count} فاتورة؟',
  'invoice.deleteConfirm': 'تأكيد الحذف',
  'invoice.deleteConfirmMessage':
    'هل أنت متأكد من حذف هذه الفاتورة؟ لا يمكن التراجع عن هذا الإجراء.',

  // Status Updates
  'invoice.statusUpdated': 'تم تحديث الحالة بنجاح',
  'invoice.statusError': 'فشل تحديث الحالة',
  'invoice.markAsSent': 'تحديد كمرسلة',
  'invoice.markAsPaid': 'تحديد كمدفوعة',
  'invoice.cancel': 'إلغاء',

  // Status Values
  'invoice.status.draft': 'مسودة',
  'invoice.status.sent': 'مرسلة',
  'invoice.status.paid': 'مدفوعة',
  'invoice.status.overdue': 'متأخرة',
  'invoice.status.cancelled': 'ملغاة',

  // Payment Status Values
  'invoice.paymentStatus.unpaid': 'غير مدفوعة',
  'invoice.paymentStatus.partial': 'مدفوعة جزئياً',
  'invoice.paymentStatus.paid': 'مدفوعة',

  // Statistics
  'invoice.stats.total': 'إجمالي الفواتير',
  'invoice.stats.totalAmount': 'المبلغ الإجمالي',
  'invoice.stats.paid': 'المدفوع',
  'invoice.stats.unpaid': 'غير المدفوع',
  'invoice.stats.overdue': 'المتأخر',
  'invoice.overdue': 'متأخرة',

  // Document KPIs
  totalQuotes: 'إجمالي الأسعار',
  acceptedQuotes: 'الأسعار المقبولة',
  pendingQuotes: 'الأسعار قيد الانتظار',
  conversionRate: 'معدل التحويل',
  totalDeliveries: 'إجمالي التسليمات',
  totalItems: 'المواد المسلمة',
  totalInvoices: 'إجمالي الفواتير',
  unpaidInvoices: 'الفواتير غير المدفوعة',
  paidInvoices: 'الفواتير المدفوعة',
  unpaidAmount: 'المبلغ غير المدفوع',
  delivered: 'مسلم',
  inProgress: 'قيد التنفيذ',
  // Chart Analysis
  invoiceAnalysis: 'تحليل الفواتير',
  quoteAnalysis: 'تحليل عروض الأسعار',
  deliveryAnalysis: 'تحليل وصولات التسليم',
  count: 'العدد',
  status: 'الحالة',
  validatedCount: 'المعتمدة',
  remaining: 'المبلغ المتبقي',
  totalValue: 'القيمة الإجمالية',
  deliveryCount: 'عدد التسليمات',
  documents: 'مستندات',
  invoices: 'فواتير',
  quotes: 'عروض أسعار',
  deliveries: 'مذكرات',

  // Status labels for charts
  draft: 'مسودة',
  unpaid: 'غير مدفوعة',
  partial: 'مدفوعة جزئياً',
  paid: 'مدفوعة',
  open: 'مفتوح',
  signed: 'موقع',
  closed: 'مغلق',
  invoiced: 'تمت الفوترة',
  validated: 'معتمد',
  cancelled: 'ملغى',

  // Month names
  january: 'يناير',
  february: 'فبراير',
  march: 'مارس',
  april: 'أبريل',
  may: 'مايو',
  june: 'يونيو',
  july: 'يوليو',
  august: 'أغسطس',
  september: 'سبتمبر',
  october: 'أكتوبر',
  november: 'نوفمبر',
  december: 'ديسمبر',
  // Document Filter Fields
  quoteNumber: 'رقم عرض السعر',
  deliveryNumber: 'رقم سند التسليم',
  invoiceNumber: 'رقم الفاتورة',
  selectPartner: 'اختر',
  noPartnerFound: 'لا يوجد {partner}',
  quoteDate: 'تاريخ عرض السعر',
  deliveryDate: 'تاريخ التسليم',

  // Additional Fields
  'invoice.createdAt': 'تاريخ الإنشاء',
  'invoice.issueDate': 'تاريخ الإصدار',
  'invoice.taxRate': 'معدل الضريبة',
  'invoice.notes': 'ملاحظات',
  'invoice.information': 'معلومات الفاتورة',
  'invoice.noCustomer': 'لا يوجد عميل',
  'invoice.noItems': 'لا توجد عناصر',

  // Create/Edit Invoice
  'invoice.customerRequired': 'العميل مطلوب',
  'invoice.validItemsRequired': 'عناصر صالحة مطلوبة',
  'invoice.createSubtitle': 'إنشاء فاتورة جديدة للعميل',
  'invoice.selectCustomer': 'اختر العميل',
  'invoice.addItem': 'إضافة عنصر',
  'invoice.productName': 'اسم المنتج',
  'invoice.itemDescription': 'وصف العنصر',
  'invoice.notesPlaceholder': 'أي ملاحظات أو تعليمات خاصة...',
  'invoice.createSuccess': 'تم إنشاء الفاتورة بنجاح',
  'invoice.createError': 'فشل في إنشاء الفاتورة',
  'invoice.noMatchingInvoices': 'لا توجد فواتير مطابقة للمرشحات المحددة',
  'invoice.getStarted': 'ابدأ بإنشاء فاتورتك الأولى',
  'invoice.basicInfo': 'المعلومات الأساسية',
  'invoice.searchProduct': 'ابحث عن منتج...',
  'invoice.openCatalog': 'فتح الكتالوج',
  'invoice.productCatalog': 'كتالوج المنتجات',
  'invoice.saveDraft': 'حفظ كمسودة',
  'invoice.createAndSend': 'إنشاء وإرسال',
  'invoice.edit': 'تعديل الفاتورة',
  'invoice.editSubtitle': 'تعديل تفاصيل الفاتورة',
  'invoice.totalHT': 'المجموع ب.ض',

  // Customer Info
  'customer.information': 'معلومات العميل',

  // Form Labels
  'invoice.partnerNamePlaceholder': 'اسم {partner}',
  'invoice.phoneLabel': 'هاتف:',
  'invoice.addressLabel': 'العنوان:',
  'invoice.searchPlaceholderPartner': 'بحث...',
  'invoice.noPartnerFound': 'لا يوجد {partner}',
  'invoice.iceLabel': 'ICE',
  'invoice.deliveryAddressLabel': 'عنوان التسليم',
  'invoice.dateRequired': 'التاريخ *',
  'invoice.dueDateLabel': 'تاريخ الاستحقاق',
  'invoice.paymentTermsLabel': 'شروط الدفع',
  'invoice.paymentTermsPlaceholder': 'مثال: الدفع خلال 30 يوم',
  'invoice.articlesTitle': 'العناصر',
  'invoice.addLine': 'إضافة سطر',
  'invoice.descriptionHeader': 'الوصف',
  'invoice.quantityHeader': 'الكمية',
  'invoice.unitPriceHeader': 'السعر',
  'invoice.discountHeader': 'الخصم',
  'invoice.totalHeader': 'المجموع',
  'invoice.itemDescriptionPlaceholder': 'وصف العنصر',
  'invoice.productSearchPlaceholder': 'ابحث عن منتج...',
  'invoice.noProductsFound': 'لا توجد منتجات',
  'invoice.percentage': 'النسبة',
  'invoice.discountTypeAmount': 'المبلغ',
  'invoice.discountTypePercentage': '%',
  'invoice.summary': 'الملخص',
  'invoice.globalDiscount': 'الخصم الإجمالي',
  'invoice.globalDiscountPlaceholder': 'الخصم',
  'invoice.globalTax': 'الضريبة الإجمالية',
  'invoice.globalTaxPlaceholder': 'الضريبة (%)',
  'invoice.notesLabel': 'ملاحظات',
  'invoice.supplier': 'المورد',
  // Payment Modal
  'invoice.editPayment': 'تعديل الدفع',
  'invoice.addPayment': 'إضافة دفع',
  'invoice.amountMustBeGreaterThanZero': 'يجب أن يكون المبلغ أكبر من 0',
  'invoice.errorOccurred': 'حدث خطأ',
  'invoice.totalInvoice': 'إجمالي الفاتورة',
  'invoice.totalPaid': 'إجمالي المدفوع',
  'invoice.payRemainingAmount': 'دفع المبلغ المتبقي',
  'invoice.paymentDate': 'تاريخ الدفع',
  'invoice.paymentMethod': 'طريقة الدفع',
  'invoice.referenceNumber': 'الرقم المرجعي',
  'invoice.additionalNotes': 'ملاحظات إضافية',
  'invoice.notesPlaceholder2': 'ملاحظات إضافية...',
  'invoice.productCatalogue': 'كتالوج المنتجات',

  // Document Edit/Create Messages
  errorLoadingDocument: 'خطأ في تحميل المستند',
  pleaseAddAtLeastOneItem: 'الرجاء إضافة عنصر واحد على الأقل',
  pleaseSelectDate: 'الرجاء تحديد تاريخ',
  errorValidating: 'خطأ في التحقق',
  errorDevalidating: 'خطأ في إلغاء التحقق',
  deliveryNoteMarkedDelivered: 'تم وضع علامة تم التسليم',
  errorMarkingDelivered: 'خطأ في وضع علامة التسليم',
  deliveryNoteCancelled: 'تم إلغاء إشعار التسليم',
  errorCancelling: 'خطأ في الإلغاء',
  invoiceCreatedQuoteUpdated: 'تم إنشاء الفاتورة وتحديث السعر',
  invoiceCreatedDeliveryUpdated: 'تم إنشاء الفاتورة وتحديث التسليم',
  errorCreatingInvoice: 'خطأ في إنشاء الفاتورة',
  deliveryNoteCreatedQuoteUpdated: 'تم إنشاء التسليم وتحديث السعر',
  errorCreatingDeliveryNote: 'خطأ في إنشاء إشعار التسليم',
  shareLinkGenerated: 'تم إنشاء رابط المشاركة',
  errorGeneratingLink: 'خطأ في إنشاء الرابط',
  quoteSigned: 'تم توقيع عرض السعر',
  errorSigning: 'خطأ في التوقيع',
  quoteRejectedClosed: 'تم رفض وإغلاق عرض السعر',
  errorValidatingDocument: 'خطأ في التحقق من المستند',
  errorDevalidatingDocument: 'خطأ في إلغاء التحقق',

  // Document Action Titles
  validateDocumentTitle: 'التحقق من المستند',
  devalidateDocumentTitle: 'إلغاء التحقق',
  createInvoiceTitle: 'إنشاء فاتورة',
  createDeliveryNoteTitle: 'إنشاء إشعار تسليم',
  signQuoteTitle: 'توقيع عرض السعر',
  rejectQuoteTitle: 'رفض عرض السعر',
  markAsDeliveredTitle: 'تحديد كمسلم',
  cancelDeliveryNoteTitle: 'إلغاء وصل التسليم',
  additionalNotesPlaceholder: 'ملاحظات إضافية...',

  // Document Status Labels
  signedToInvoice: 'موقع (للفوترة)',
  unsignedClosed: 'غير موقع (مغلق)',
  toDeliver: 'للتسليم',
  invoicedStatus: 'تم الفوترة',

  // Confirmation Messages
  confirmValidateDocument:
    'هل أنت متأكد من أنك تريد التحقق من هذا المستند؟ لن يمكن تعديله بعد ذلك.',
  confirmDevalidateDocument: 'هل أنت متأكد من أنك تريد إلغاء التحقق من هذا المستند؟',
  confirmCreateInvoice: 'هل تريد إنشاء فاتورة من هذا المستند؟',
  confirmCreateDeliveryNote: 'هل تريد إنشاء وصل تسليم من هذا العرض؟ سيتم نسخ جميع البيانات.',
  confirmSignQuote: 'هل تريد تحديد هذا العرض كموقع؟',
  confirmRejectQuote: "هل تريد حقًا رفض هذا العرض؟ سيتغير الحالة إلى 'مغلق'.",
  confirmMarkDelivered: 'هل أنت متأكد من أنك تريد تحديد وصل التسليم هذا كمسلم؟',
  confirmCancelDelivery:
    'هل أنت متأكد من أنك تريد إلغاء وصل التسليم هذا؟ قد يكون هذا الإجراء غير قابل للإلغاء.',
  confirmDeleteDocument: 'هل أنت متأكد من أنك تريد حذف هذا المستند؟ هذا الإجراء لا رجعة فيه.',
  confirmValidate: 'هل أنت متأكد من أنك تريد التحقق من هذا المستند؟',
  confirmDevalidate: 'هل أنت متأكد من أنك تريد إلغاء التحقق من هذا المستند؟',

  // Success Messages
  success: 'نجاح',
  documentValidated: 'تم التحقق من المستند بنجاح',
  documentDevalidated: 'تم إلغاء التحقق من المستند بنجاح',

  // Error Messages
  errorDevalidatingInList: 'خطأ عند إلغاء التحقق من المستند',
  unsupportedDocumentType: 'نوع مستند غير مدعوم',

  // Additional Labels
  totalRevenue: 'الإيرادات',
  totalExpenses: 'المصروفات',
  create: 'إنشاء',
  devalidate: 'إلغاء التحقق',
  signedStatus: '✓ موقع',
  closedStatus: '✕ مغلق',
  awaitingSignature: 'بانتظار التوقيع',
  signedByLabel: 'موقع من:',
  dateLabel: 'التاريخ:',
  signedByPlaceholder: 'اسمك الكامل',
  validateDocument: 'تحقق',
  devalidateDocument: 'إلغاء التحقق',
  pdfGenerated: 'تم إنشاء PDF',
  markAsDelivered: 'وضع علامة كتم التسليم',
  signQuote: 'توقيع',
  rejectQuote: 'رفض',
  createInvoiceMessage: 'هل تريد إنشاء فاتورة من',
  thisQuote: 'عرض السعر هذا',
  thisDeliveryNote: 'وصل التسليم هذا',
  allDataWillBeCopied: '؟ سيتم نسخ جميع البيانات.',
  deliverButton: 'تسليم',
  cancelDeliveryButton: 'إلغاء الوصل',
  rejectButton: 'رفض',
  shareQuote: 'مشاركة عرض السعر',
  generateSecureLink: 'إنشاء رابط مشاركة آمن للسماح لعميلك بالاطلاع والتوقيع على عرض السعر هذا.',
  downloadPDF: 'تحميل PDF',
  errorGeneratingPDF: 'خطأ في إنشاء ملف PDF',

  // Document Create Page
  pleaseSelect: 'يرجى اختيار',
  createdSuccessfully: 'تم الإنشاء بنجاح',
  new: 'جديد',
  createNew: 'إنشاء جديد',
  documentInformation: 'معلومات المستند',
  expirationDate: 'تاريخ انتهاء الصلاحية',
  additionalNotes: 'ملاحظات إضافية...',
  drafts: 'مسودات',
  subtotalHT: 'المجموع الفرعي (قبل الضريبة)',
  totalTVA: 'إجمالي الضريبة',
  totalTTC: 'المجموع الإجمالي (شامل الضريبة)',

  // Document List Page
  listOf: 'قائمة',
  manageYour: 'إدارة',
  nouveau: 'جديد',

  partiallyPaid: 'مدفوع جزئيًا',
  amount: 'المبلغ',
  lastThree: 'آخر 3',
  noRecentDocument: 'لا توجد',
  recentSuffix: 'حديثة',
  noDrafts: 'لا توجد مسودات',
  error: 'خطأ',
  deletionImpossible: 'لا يمكن الحذف',
  errorDeletingDocument: 'خطأ عند حذف المستند',

  // Document Types & Titles
  salesInvoices: 'فواتير المبيعات',
  salesInvoice: 'فاتورة عميل',
  purchaseInvoices: 'فواتير المشتريات',
  purchaseInvoice: 'فاتورة مورد',
  quote: 'عرض سعر',
  deliveryNotes: 'وصول التسليم',
  deliveryNote: 'وصل تسليم',
  client: 'عميل',
  supplier: 'مورد',

  // DocumentTable
  columns: 'الأعمدة',
  showColumns: 'عرض الأعمدة',
  showHideColumns: 'إظهار/إخفاء الأعمدة',
  taxAmount: 'مبلغ الضريبة',
  alreadyPaid: 'تم الدفع',
  remainingToPay: 'المتبقي للدفع',
  searchByNumberOrName: 'البحث بالرقم أو الاسم...',
  pdfPreview: 'معاينة PDF',
  number: 'الرقم',
  invoiceDate: 'تاريخ الفوترة',
  dueDate: 'تاريخ الاستحقاق',
  validationDate: 'تاريخ التحقق',
  amountHT: 'المبلغ (قبل الضريبة)',
  amountTTC: 'المبلغ (شامل الضريبة)',
  loading: 'جارٍ التحميل...',
  noDocumentFound: 'لا توجد مستندات',
  showingFrom: 'عرض',
  to: 'إلى',
  on: 'من',
  previous: 'السابق',
  next: 'التالي',

  // Status Labels - Payment
  statusPaid: 'مدفوع',
  statusPartial: 'جزئي',
  statusUnpaid: 'غير مدفوع',
  statusDraft: 'مسودة',

  // Status Labels - Quote
  statusOpen: 'مفتوح',
  statusSigned: 'موقع (للفوترة)',
  statusClosed: 'غير موقع (مغلق)',
  statusDelivered: 'للتسليم',
  statusInvoiced: 'تم إصدار فاتورة',

  // Status Labels - Delivery Note
  statusValidated: 'تم التحقق',
  statusInProgress: 'جاري',
  statusDeliveredBon: 'تم التسليم',
  statusCancelled: 'ملغى',
  statusInvoicedBon: 'تم الفوترة',

  // Additional Success Messages
  successUpdated: 'تم التحديث بنجاح',
  successValidated: 'تم التحقق بنجاح',
  successDevalidated: 'تم إلغاء التحقق بنجاح',
  successDelivered: 'تم وضع علامة على التسليم',
  successCancelled: 'تم إلغاء التسليم',
  successInvoiceCreatedQuoteUpdated: 'تم إنشاء الفاتورة وتحديث العرض',
  successInvoiceCreatedDeliveryUpdated: 'تم إنشاء الفاتورة وتحديث التسليم',
  successDeliveryCreatedQuoteUpdated: 'تم إنشاء التسليم وتحديث العرض',
  successLinkGenerated: 'تم إنشاء رابط المشاركة',
  successQuoteSigned: 'تم توقيع العرض بنجاح',
  successQuoteRejected: 'تم رفض العرض وإغلاقه',

  // Additional Error Messages
  errorUnsigning: 'خطأ في إلغاء التوقيع',
  errorUpdatingDocument: 'خطأ في التحديث',
  errorDelivering: 'خطأ في التسليم',

  // Additional Edit/Create messages

  // Document Edit UI
  editDocument: 'تعديل',
  notValidated: 'لم يتم التحقق',
  paymentDetails: 'تفاصيل الدفع',
  totalAmount: 'المبلغ الإجمالي',
  paidAmount: 'المبلغ المدفوع',
  remainingAmount: 'المبلغ المتبقي',
  date: 'التاريخ',
  dateDeFacturation: 'تاريخ الفاتورة',
  dateDeBon: 'تاريخ إذن التسليم',
  dateDeDevis: 'تاريخ العرض',
  notes: 'ملاحظات',
  signature: 'التوقيع',
  signedBy: 'وقعه:',
  comment: 'تعليق:',
  paymentHistory: 'سجل المدفوعات',
  cancel: 'إلغاء',
  actions: 'إجراءات',
  convertToInvoice: 'تحويل إلى فاتورة',
  shareWithClient: 'مشاركة مع العميل',
  createAnInvoice: 'إنشاء فاتورة',
  createDeliveryNote: 'إنشاء وصل تسليم',
  save: 'حفظ',
  saving: 'جارٍ الحفظ...',

  // Payment Modal & History
  errorPaymentExceedsInvoice: 'لا يمكن أن يتجاوز إجمالي المدفوعات إجمالي الفاتورة',
  errorOccurred: 'حدث خطأ',
  errorDeletingPayment: 'خطأ في حذف الدفعة',
  referenceNumberHint: '(رقم الشيك، المعاملة، إلخ.)',
  referenceNumberPlaceholder: 'مثال: CHK-12345',
  invoice: 'فاتورة',
  totalInvoice: 'إجمالي الفاتورة',
  totalPaid: 'إجمالي المدفوع',
  invoiceFullyPaid: 'تم دفع الفاتورة بالكامل',
  addPayment: 'إضافة دفعة',
  noPaymentsRecorded: 'لا توجد مدفوعات مسجلة',
  paymentMethod: 'طريقة الدفع',
  reference: 'المرجع',
  close: 'إغلاق',
  deleteTitle: 'تأكيد الحذف',
  confirmDeletePayment: 'هل أنت متأكد من حذف هذه الدفعة؟',
  delete: 'حذف',
  edit: 'تعديل',
  add: 'إضافة',

  // Payment Pages
  purchasePayments: 'مدفوعات المشتريات',
  managePurchasePayments: 'إدارة مدفوعات الموردين',
  salesPayments: 'مدفوعات المبيعات',
  manageSalesPayments: 'إدارة مدفوعات العملاء',
  totalPayments: 'إجمالي المدفوعات',
  thisMonth: 'هذا الشهر',
  searchByInvoice: 'البحث بالفاتورة أو العميل أو المرجع...',
  modify: 'تعديل',
};
