export default {
  // ── Welcome screen ──
  onboardingWelcomeTitle: 'مرحباً بك في Morocom',
  onboardingWelcomeSubtitle: 'لنقم بإعداد شركتك في خطوتين فقط',
  onboardingTimeEstimate: 'حوالي دقيقتين',
  onboardingGetStarted: '← ابدأ الآن',
  onboardingNoCreditCard: 'مجاني، لا حاجة لبطاقة بنكية',

  // ── Steps ──
  onboardingStepCompanyTitle: 'ملف الشركة',
  onboardingStepCompanyDesc: 'أخبرنا عن نشاطك التجاري',
  onboardingStepCompanySubtitle: 'الخطوة 1 من 2 — المعلومات الأساسية',
  onboardingStepAdminTitle: 'حساب المدير',
  onboardingStepAdminDesc: 'أنشئ حساب المدير الخاص بك',
  onboardingStepAdminSubtitle: 'الخطوة 2 من 2 — بيانات اعتماد المدير',

  // ── Company step ──
  onboardingCompanyIntro: 'أخبرنا عن شركتك. يمكنك تعديل هذه المعلومات في أي وقت من الإعدادات.',
  onboardingSectionBasicInfo: 'المعلومات الأساسية',
  onboardingCompanyName: 'اسم الشركة',
  onboardingCompanyNamePlaceholder: 'مثال: Acme Distribution SARL',
  onboardingBusinessType: 'نوع النشاط / المهن',
  onboardingBusinessTypePlaceholder: 'مثال: التوزيع بالجملة، البناء',
  onboardingCompanyLogo: 'شعار الشركة',
  onboardingLogoPreview: 'معاينة الشعار',
  onboardingClickToUpload: 'انقر للرفع',
  onboardingDragAndDrop: ' أو اسحب وأفلت',
  onboardingLogoHint: 'PNG أو JPG أو SVG حتى 5 ميغابايت',
  onboardingSectionContact: 'جهة الاتصال',
  onboardingEmailPlaceholder: 'contact@entreprise.com',
  onboardingSectionAddress: 'العنوان',
  onboardingAddressPlaceholder: '123 شارع محمد الخامس',
  onboardingCityPlaceholder: 'الدار البيضاء',
  onboardingStatePlaceholder: 'الدار البيضاء سطات',
  onboardingSectionLegal: 'المعلومات القانونية والمالية',
  onboardingTaxId: 'المعرف الضريبي (IF)',
  onboardingSelectPlaceholder: 'اختر...',
  onboardingSaving: 'جاري الحفظ...',

  onboardingContinueToAdmin: '← المتابعة إلى حساب المدير',
  onboardingLegalStructureOther: 'أخرى',
  onboardingErrCompanyNameRequired: 'اسم الشركة مطلوب',
  onboardingErrInvalidEmailAddress: 'أدخل عنوان بريد إلكتروني صالحاً',
  onboardingErrWebsiteScheme: 'يجب أن يبدأ الرابط بـ http:// أو https://',

  // ── Admin step ──
  onboardingCreateAdminAccount: '← إنشاء حساب المدير',
  onboardingErrFullNameRequired: 'الاسم الكامل مطلوب',
  onboardingErrInvalidEmail: 'أدخل بريداً إلكترونياً صالحاً',
  onboardingErrPhoneRequired: 'رقم الهاتف مطلوب',
  onboardingErrPhoneFormat: 'أرقام فقط، مثال: ‎+212600000000',
  onboardingErrPasswordRequired: 'كلمة المرور مطلوبة',
  onboardingErrPasswordTooShort: 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
  onboardingErrConfirmPassword: 'يرجى تأكيد كلمة المرور',
  onboardingAdminIntro: 'أنشئ حساب المدير العام. سيكون هذا هو حساب دخولك لإدارة المنصة.',
  onboardingFullNamePlaceholder: 'أحمد بنعلي',
  onboardingEmailAddress: 'البريد الإلكتروني',
  onboardingAdminEmailPlaceholder: 'ahmed@entreprise.com',
  onboardingUsernameHint: 'سيكون هذا اسم المستخدم لتسجيل الدخول',
  onboardingPasswordPlaceholder: '8 أحرف على الأقل',
  onboardingConfirmPasswordPlaceholder: 'أعد إدخال كلمة المرور',
  onboardingCreatingAccount: 'جاري إنشاء الحساب...',

  // ── Success screen ──
  onboardingSuccessSubtitle: 'مرحباً بك في Morocom، {company}. حساب المدير الخاص بك جاهز.',
  onboardingCopied: 'تم النسخ!',
  onboardingAllSet: 'كل شيء جاهز!',
  onboardingCompanyLogoAlt: 'شعار الشركة',
  onboardingAdminPanel: 'لوحة الإدارة',
  onboardingClientPortal: 'بوابة العملاء',
  onboardingDeliveryPortal: 'بوابة التوصيل',
  onboardingShareLinks: 'شارك هذه الروابط مع فريقك',
  onboardingGoToDashboard: 'الذهاب إلى لوحة التحكم',
  onboardingShareWhatsapp: 'المشاركة عبر واتساب',

  companyProfileSaveError: 'فشل حفظ ملف الشركة',
  adminAccountCreated: 'تم إنشاء حساب المسؤول بنجاح!',
  adminAccountCreateError: 'فشل إنشاء حساب المسؤول',
  yourCompany: 'شركتك',
  onlyImageFilesSupported: 'يُقبل فقط ملفات الصور',
  imageMustBeSmallerThan5Mb: 'يجب أن يكون حجم الصورة أقل من 5 ميغابايت',
};
