export default {
  // Customers
  customers: 'العملاء',
  customer: 'العميل',
  manageCustomers: 'إدارة العملاء',
  searchCustomers: 'ابحث عن العملاء...',
  noCustomersFound: 'لا يوجد عملاء',
  customerUpdated: 'تم تحديث العميل بنجاح',
  customerCreated: 'تم إنشاء العميل بنجاح',
  customerDeleted: 'تم حذف العميل بنجاح',
  addCustomer: 'إضافة عميل',
  phoneNumberRequired: 'رقم الهاتف مطلوب',
  city: 'المدينة',
  
  // Suppliers
  suppliers: 'الموردين',
  supplier: 'مورد',
  manageSuppliers: 'إدارة الموردين',
  searchSuppliers: 'ابحث عن الموردين...',
  noSuppliersFound: 'لا يوجد موردين',
  supplierUpdated: 'تم تحديث المورد بنجاح',
  supplierCreated: 'تم إنشاء المورد بنجاح',
  supplierDeleted: 'تم حذف المورد بنجاح',
  addSupplier: 'إضافة مورد',
  
  // Partner Form
  partnerType: 'نوع الشريك',
  individual: 'فرد',
  company: 'شركة',
  fillInformation: 'املأ المعلومات أدناه',
  basicInformation: 'المعلومات الأساسية',
  businessIdentifiers: 'المعرفات التجارية',
  nameRequired: 'الاسم مطلوب',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  enterName: 'أدخل الاسم',
  deliveryAddress: 'عنوان التسليم',
  enterDeliveryAddress: 'أدخل عنوان التسليم',
  enterAddress: 'أدخل العنوان',
  tvaNumber: 'رقم TVA',
  enterTvaNumber: 'أدخل رقم TVA',
  ice: 'رقم ICE',
  enterICE: 'أدخل رقم ICE',
  if: 'رقم IF',
  enterIF: 'أدخل رقم IF',
  cnss: 'رقم CNSS',
  enterCNSS: 'أدخل رقم CNSS',
  rc: 'رقم RC',
  enterRC: 'أدخل رقم RC',
  patente: 'رقم Patente',
  enterPatente: 'أدخل رقم Patente',
  updatePartner: 'تحديث الشريك',
  createPartner: 'إنشاء شريك',
  deletePartnerConfirmation: 'هل أنت متأكد من حذف هذا الشريك؟ لا يمكن التراجع عن هذا الإجراء.',
};
