export default {
  // POS
  pos: 'نقطة البيع',
  pointOfSale: 'نقطة البيع',
  createOrders: 'إنشاء الطلبات',

  // Cart
  cart: 'السلة',
  cartEmpty: 'السلة فارغة',
  emptyCartMessage: 'ابدأ بإضافة المنتجات',
  selectCustomer: 'يرجى اختيار عميل',
  newCustomer: 'عميل جديد',
  searchByNameOrPhone: 'ابحث بالاسم أو الهاتف...',
  change: 'تغيير',
  searchResults: 'نتائج البحث',
  searchForCustomer: 'ابحث عن عميل',
  searchCustomerInstructions: 'أدخل حرفين على الأقل للبحث',
  currentCustomer: 'العميل الحالي',
  createNewCustomer: 'إنشاء عميل جديد',
  createCustomer: 'إنشاء العميل',
  cartProduct: 'منتج',
  cartProducts: 'منتجات',
  piece: 'قطعة',
  pieces: 'قطع',
  perUnit: '/ وحدة',
  clear: 'مسح',
  confirmClearCart: 'تفريغ السلة؟',
  clearCart: 'تفريغ',
  addToCart: 'أضف للسلة',
  updateQty: 'تحديث الكمية',
  confirmPrice: 'تأكيد السعر',
  originalPrice: 'السعر الأصلي',
  applyDiscount: 'تطبيق الخصم',
  percentage: 'نسبة مئوية',
  belowCostWarning: 'البيع بأقل من سعر التكلفة',
  confirmCash: 'تأكيد نقداً',
  orderSummary: 'ملخص الطلب',
  reviewAndConfirmOrder: 'مراجعة وتأكيد الطلب',
  backToPOS: 'العودة إلى نقطة البيع',

  // Documents
  downloadDocuments: 'قم بتحميل المستندات أدناه',
  receipt: 'إيصال',
  invoice: 'فاتورة',
  thermalReceipt80mm: 'إيصال حراري 80 مم',
  deliveryNoteA5: 'سند تسليم A5',
  preview: 'معاينة',
  print: 'طباعة',

  // Image upload (POS)
  addPhoto: 'صورة',
  takePhoto: 'التقاط صورة',
  orChooseFromGallery: 'اختر من المعرض',
  uploading: 'جارٍ الرفع',
  imageUploadedSuccess: 'تم تحديث الصورة بنجاح',
};
