export default {
  // Products Management
  products: 'المنتجات',
  product: 'المنتج',
  manageProducts: 'إدارة المنتجات',
  addProduct: 'إضافة منتج',
  editProduct: 'تعديل المنتج',
  productName: 'اسم المنتج',
  productCode: 'رمز المنتج',
  description: 'الوصف',
  price: 'السعر',
  cost: 'التكلفة',
  stock: 'المخزون',
  image: 'الصورة',
  productImage: 'صورة المنتج',
  chooseImage: 'اختر صورة',
  orImageUrl: 'أو الصق رابط الصورة',
  imageDescription: 'ارفع صورة المنتج (JPG, PNG, حجم أقصى 5 ميجا)',
  isService: 'خدمة',
  isEnabled: 'نشط',
  isPriceChangeAllowed: 'السماح بتغيير السعر',
  allowPriceChange: 'السماح بتغيير السعر',
  lockPriceChange: 'قفل تغيير السعر',
  enable: 'تفعيل',
  disable: 'تعطيل',
  importFile: 'استيراد صورة',
  fileSelected: 'تم اختيار الملف',
  bulkImportFeatureComingSoon: 'ميزة الاستيراد الجماعي قيد التطوير',
  selectOneProductForImageUpload: 'يرجى تحديد منتج واحد فقط لتحميل الصورة',
  confirmDelete: 'هل أنت متأكد من حذف هذا المنتج؟',
  code: 'الرمز',
  searchProducts: 'ابحث عن المنتجات...',
  noProductsFound: 'لا توجد منتجات',
  noResultsMessage: 'جرب كلمة بحث أخرى',
  noProductsInCategory: 'لا توجد منتجات متاحة',
};
