export default {
  // ─── Users & Roles Module ─────────────────────────────────
  usersAndRoles: 'المستخدمون والأدوار',
  usersManagement: 'إدارة المستخدمين',
  rolesManagement: 'إدارة الأدوار',
  adminUsers: 'مستخدمو الإدارة',
  clientUsers: 'مستخدمو العملاء',
  roleName: 'اسم الدور',
  roleDescription: 'وصف الدور',
  superAdmin: 'مشرف رئيسي',
  permissions: 'الصلاحيات',
  assignRole: 'تعيين دور',
  noRole: 'بدون دور',
  userType: 'نوع المستخدم',
  admin: 'مشرف',
  clientUser: 'عميل',
  roleCreated: 'تم إنشاء الدور بنجاح',
  roleUpdated: 'تم تحديث الدور بنجاح',
  roleDeleted: 'تم حذف الدور بنجاح',
  userCreated: 'تم إنشاء المستخدم بنجاح',
  userUpdated: 'تم تحديث المستخدم بنجاح',
  userDeleted: 'تم حذف المستخدم بنجاح',
  userActivated: 'تم تفعيل المستخدم بنجاح',
  userDeactivated: 'تم تعطيل المستخدم بنجاح',
  createUser: 'إنشاء مستخدم',
  editUser: 'تعديل المستخدم',
  createRole: 'إنشاء دور',
  editRole: 'تعديل الدور',
  confirmDeleteUser: 'هل تؤكد حذف هذا المستخدم؟',
  confirmDeleteRole: 'هل تؤكد حذف هذا الدور؟',
  passwordMinLength: 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
  phoneRequired: 'رقم الهاتف مطلوب',
  nameRequired2: 'الاسم مطلوب',
  password: 'كلمة المرور',
  newPassword: 'كلمة مرور جديدة',
  avatar: 'الصورة الرمزية',
  role: 'الدور',
  roles: 'الأدوار',
  users: 'المستخدمون',
  allPermissions: 'جميع الصلاحيات',
  permissionView: 'عرض',
  permissionCreate: 'إنشاء',
  permissionEdit: 'تعديل',
  permissionDelete: 'حذف',
  permissionManage: 'إدارة',
  permissionUse: 'استخدام',
  selectAll: 'تحديد الكل',
  deselectAll: 'إلغاء تحديد الكل',
  noPermissionsAssigned: 'لم يتم تعيين أي صلاحيات',
  cannotDeactivateSelf: 'لا يمكنك تعطيل حسابك الخاص',
  cannotDeleteSelf: 'لا يمكنك حذف حسابك الخاص',
  cannotRemoveOwnSuperAdmin: 'لا يمكنك إزالة دور المشرف الرئيسي الخاص بك',
  superAdminBadge: 'مشرف رئيسي',
  moduleName: 'الوحدة',
  approved: 'موافق عليه',
  rejected: 'مرفوض',
  userApproved: 'تم اعتماد المستخدم بنجاح',
  userRejected: 'تم رفض المستخدم بنجاح',

  // ─── Users page (previously untranslated) ─────────────────
  activate: 'تفعيل',
  deactivate: 'تعطيل',
  reject: 'رفض',
  confirmDeactivateUser: 'تعطيل هذا المستخدم؟',
  confirmActivateUser: 'تفعيل هذا المستخدم؟',
  confirmRejectUser: 'رفض هذا الوصول إلى البوابة؟',
  confirmApproveUser: 'الموافقة على هذا الوصول إلى البوابة؟',
  noUsersFound: 'لم يتم العثور على أي مستخدم',
  usersCountLabel: 'مستخدمون',
  userCountLabel: 'مستخدم',
  confirmDeleteUsersPlural: 'حذف {count} مستخدم؟',

  // ─── Client access requests (portal sign-ups) ────────────
  clientRequests: 'طلبات العملاء',
  clientRequestsSubtitle: 'وافق على الحسابات المنشأة من بوابة العملاء أو ارفضها',
  clientRequestsCountLabel: 'طلبات',
  searchClientRequests: 'ابحث بالاسم أو رقم الهاتف…',
  clearSearch: 'مسح البحث',
  approveRequest: 'موافقة',
  declineRequest: 'رفض',
  confirmDeclineRequest: 'رفض طلب الوصول هذا؟',
  noClientRequests: 'لا توجد طلبات عملاء',
  requestedOn: 'تاريخ الطلب',
  bulkApprove: 'الموافقة على المحدد',
  bulkDecline: 'رفض المحدد',
  requestApproved: 'تمت الموافقة على الطلب',
  requestDeclined: 'تم رفض الطلب',
};
