import { DataSource } from 'typeorm';
import { Configuration } from '../../modules/configurations/entities/configuration.entity';

export async function seedConfigurations(dataSource: DataSource) {
  const configRepository = dataSource.getRepository(Configuration);

  const configurations = [
    {
      entity: 'taxes',
      values: {
        defaultRate: 20,
        rates: [
          { name: 'Taux Normal', rate: 20, isDefault: true },
          { name: 'Taux Intermédiaire', rate: 14, isDefault: false },
          { name: 'Taux Réduit', rate: 10, isDefault: false },
          { name: 'Taux Super Réduit', rate: 7, isDefault: false },
          { name: 'Taux Zéro', rate: 0, isDefault: false },
        ],
      },
    },
    {
      entity: 'currencies',
      values: {
        default: 'MAD',
        currencies: [
          {
            code: 'MAD',
            name: 'Moroccan Dirham',
            symbol: 'DH',
            isDefault: true,
          },
          { code: 'EUR', name: 'Euro', symbol: '€', isDefault: false },
          { code: 'USD', name: 'US Dollar', symbol: '$', isDefault: false },
        ],
      },
    },
    {
      entity: 'payment_terms',
      values: {
        default: 'immediate',
        terms: [
          { key: 'immediate', label: 'Immediate', days: 0, isDefault: true },
          { key: 'net_15', label: 'Net 15', days: 15, isDefault: false },
          { key: 'net_30', label: 'Net 30', days: 30, isDefault: false },
          { key: 'net_60', label: 'Net 60', days: 60, isDefault: false },
        ],
      },
    },
    {
      entity: 'sequences',
      values: {
        sequences: [
          {
            id: 'seq_invoice_sale_001',
            name: 'Factures de vente',
            prefix: 'FA',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-18T00:22:44.228Z',
            updatedAt: '2026-01-27T12:55:23.322Z',
            dateFormat: 'YYYY',
            entityType: 'invoice_sale',
            nextNumber: 6,
            dayInPrefix: false,
            resetPeriod: 'monthly',
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: false,
            trimesterInPrefix: true,
            format: 'FA YYYY-TRIM-XXXX',
            nextDocumentNumber: 'FA 2026-01-0006',
            realTimeNextNumber: 6,
          },
          {
            id: 'seq_invoice_purchase_001',
            name: "Factures d\\'achat",
            prefix: 'PA',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-18T00:22:44.228Z',
            updatedAt: '2026-01-26T12:27:57.677Z',
            dateFormat: 'YYYY',
            entityType: 'invoice_purchase',
            nextNumber: 1,
            dayInPrefix: false,
            resetPeriod: 'yearly',
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: true,
            trimesterInPrefix: false,
            format: 'PA YYYY-MM-XXXX',
            nextDocumentNumber: 'PA 2026-01-0001',
            realTimeNextNumber: 1,
          },
          {
            id: 'seq_quote_001',
            name: 'Devis',
            prefix: 'DV ',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-18T00:22:44.228Z',
            updatedAt: '2026-01-29T00:25:46.846Z',
            dateFormat: 'YYYY',
            entityType: 'quote',
            nextNumber: 1,
            dayInPrefix: false,
            resetPeriod: 'yearly',
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: true,
            trimesterInPrefix: false,
            format: 'DV  YYYY-MM-XXXX',
            nextDocumentNumber: 'DV  2026-01-0001',
            realTimeNextNumber: 1,
          },
          {
            id: 'seq_delivery_note_001',
            name: 'Bons de livraison',
            prefix: 'BL',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-18T00:22:44.228Z',
            updatedAt: '2026-01-29T13:07:14.622Z',
            dateFormat: 'YYYY',
            entityType: 'delivery_note',
            nextNumber: 3,
            dayInPrefix: false,
            resetPeriod: 'yearly',
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: true,
            trimesterInPrefix: false,
            format: 'BL YYYY-MM-XXXX',
            nextDocumentNumber: 'BL 2026-01-0003',
            realTimeNextNumber: 3,
          },
          {
            id: 'seq_purchase_order_001',
            name: "Bons d\\'achat",
            prefix: 'BA',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-18T00:22:44.228Z',
            updatedAt: '2026-01-29T15:12:28.806Z',
            dateFormat: 'YYYY',
            entityType: 'purchase_order',
            nextNumber: 1,
            dayInPrefix: false,
            resetPeriod: 'yearly',
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: true,
            trimesterInPrefix: false,
            format: 'BA YYYY-MM-XXXX',
            nextDocumentNumber: 'BA 2026-01-0001',
            realTimeNextNumber: 1,
          },
          {
            id: 'seq_payment_001',
            name: 'Paiements',
            prefix: 'PAY',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-18T00:22:44.228Z',
            updatedAt: '2026-01-29T15:12:41.601Z',
            dateFormat: 'YYYY',
            entityType: 'payment',
            nextNumber: 1,
            dayInPrefix: false,
            resetPeriod: 'yearly',
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: true,
            trimesterInPrefix: false,
            format: 'PAY YYYY-MM-XXXX',
            nextDocumentNumber: 'PAY 2026-01-0001',
            realTimeNextNumber: 1,
          },
          {
            id: 'seq_receipt_001',
            name: 'Reçu',
            prefix: '',
            suffix: '',
            isActive: true,
            createdAt: '2026-01-29T15:09:58.977Z',
            updatedAt: '2026-01-29T15:09:58.977Z',
            entityType: 'receipt',
            nextNumber: 1,
            dayInPrefix: true,
            numberLength: 4,
            yearInPrefix: true,
            monthInPrefix: true,
            trimesterInPrefix: false,
            format: 'YYYY-MM-DD-XXXX',
            nextDocumentNumber: '2026-01-29-0001',
            realTimeNextNumber: 1,
          },
        ],
      },
    },
    {
      entity: 'my_company',
      values: {
        companyName: '',
        address: '',
        zipCode: '',
        city: '',
        country: 'Maroc',
        state: '',
        phone: '',
        fax: '',
        email: '',
        website: '',
        logo: '',
        professions: '',
        vatNumber: '',
        ice: '',
        taxId: '',
        registrationNumber: '',
        legalStructure: '',
        capital: 0,
        fiscalYearStartMonth: 1,
      },
    },
  ];

  for (const config of configurations) {
    const existing = await configRepository.findOne({
      where: { entity: config.entity },
    });

    if (!existing) {
      await configRepository.save(configRepository.create(config));
      console.log(`✓ Created configuration: ${config.entity}`);
    } else {
      console.log(`- Configuration already exists: ${config.entity}`);
    }
  }
}
