import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSupplierFieldsToInvoices1768522548671 implements MigrationInterface {
    name = 'AddSupplierFieldsToInvoices1768522548671'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "portal" DROP CONSTRAINT "FK_portal_customerId"`);
        await queryRunner.query(`ALTER TABLE "portal" DROP CONSTRAINT "FK_portal_deliveryId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_customerId"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_orderId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_customerId"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_items_invoiceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customers_phoneNumber"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customers_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_delivery_persons_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_delivery_persons_phoneNumber"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_delivery_orderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_delivery_deliveryPersonId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_delivery_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_portal_phoneNumber"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_orderNumber"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_customerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_order_items_orderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_order_items_productId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_isRead"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_dateCreated"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_invoiceNumber"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_customerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_items_productId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_items_invoiceId"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "supplierId" integer`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "supplierName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "supplierPhone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "supplierAddress" text`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "partners_id_seq" OWNED BY "partners"."id"`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "id" SET DEFAULT nextval('"partners_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "phoneNumber" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "isCustomer" SET DEFAULT false`);
        await queryRunner.query(`CREATE INDEX "IDX_7cfc24d6c24f0ec91294003d6b" ON "products" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b39bc13ab676e74eada2e744d" ON "partners" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e9597dd1009c60cc359ef9452" ON "partners" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_8cc291687cdb44d42a208c9631" ON "delivery_persons" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_29dd6f4506c39a32e73b4c2c8f" ON "delivery_persons" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5c9fa770236835894f85316ac" ON "orders_delivery" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_500bc42c16ef014f0b14040d66" ON "orders_delivery" ("deliveryPersonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f01dffdb2fd3c0f7e28b309bb3" ON "orders_delivery" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d80146508aa51bbc72f995189" ON "portal" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_6dc3a53d92a338eb56dbc82cf5" ON "orders" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5de51ca888d8b1f5ac25799dd" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_59b0c3b34ea0fa5562342f2414" ON "orders" ("orderNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e174e347d448617acdf98fef0" ON "orders" ("number") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdb99c05982d5191ac8465ac01" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_394cb9629118027d34274bb081" ON "notifications" ("dateCreated") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ba28344602d583583b9ea1a50" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_df62845187eb4c31c0dcda454e" ON "invoices" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cf9a7d463c3262c954f3300fe" ON "invoices" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1df049f8943c6be0c1115541ef" ON "invoices" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf8e0f9dd4558ef209ec111782" ON "invoices" ("invoiceNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bec360ed9928668b73dac2ec1" ON "invoice_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fb6895fc8fad9f5200e91abb5" ON "invoice_items" ("invoiceId") `);
        await queryRunner.query(`ALTER TABLE "portal" ADD CONSTRAINT "FK_218766a99fd41fcf4424056ab4f" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portal" ADD CONSTRAINT "FK_76c3a13509109c5f1681217a129" FOREIGN KEY ("deliveryId") REFERENCES "delivery_persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_0cf9a7d463c3262c954f3300fe9" FOREIGN KEY ("supplierId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_0cf9a7d463c3262c954f3300fe9"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "portal" DROP CONSTRAINT "FK_76c3a13509109c5f1681217a129"`);
        await queryRunner.query(`ALTER TABLE "portal" DROP CONSTRAINT "FK_218766a99fd41fcf4424056ab4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fb6895fc8fad9f5200e91abb5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bec360ed9928668b73dac2ec1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf8e0f9dd4558ef209ec111782"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df049f8943c6be0c1115541ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cf9a7d463c3262c954f3300fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df62845187eb4c31c0dcda454e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ba28344602d583583b9ea1a50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_394cb9629118027d34274bb081"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdb99c05982d5191ac8465ac01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e174e347d448617acdf98fef0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59b0c3b34ea0fa5562342f2414"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5de51ca888d8b1f5ac25799dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6dc3a53d92a338eb56dbc82cf5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d80146508aa51bbc72f995189"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f01dffdb2fd3c0f7e28b309bb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_500bc42c16ef014f0b14040d66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5c9fa770236835894f85316ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29dd6f4506c39a32e73b4c2c8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cc291687cdb44d42a208c9631"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e9597dd1009c60cc359ef9452"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b39bc13ab676e74eada2e744d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cfc24d6c24f0ec91294003d6b"`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "isCustomer" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "phoneNumber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "id" SET DEFAULT nextval('customers_id_seq')`);
        await queryRunner.query(`ALTER TABLE "partners" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "partners_id_seq"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "supplierAddress"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "supplierPhone"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "supplierName"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "supplierId"`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_items_invoiceId" ON "invoice_items" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_items_productId" ON "invoice_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_date" ON "invoices" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_customerId" ON "invoices" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_invoiceNumber" ON "invoices" ("invoiceNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_dateCreated" ON "notifications" ("dateCreated") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_isRead" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_userId" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_items_productId" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_items_orderId" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_date" ON "orders" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_customerId" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_orderNumber" ON "orders" ("orderNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_number" ON "orders" ("number") `);
        await queryRunner.query(`CREATE INDEX "IDX_portal_phoneNumber" ON "portal" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_delivery_status" ON "orders_delivery" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_delivery_deliveryPersonId" ON "orders_delivery" ("deliveryPersonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_delivery_orderId" ON "orders_delivery" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_delivery_persons_phoneNumber" ON "delivery_persons" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_delivery_persons_email" ON "delivery_persons" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_customers_email" ON "partners" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_customers_phoneNumber" ON "partners" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_code" ON "products" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_name" ON "products" ("name") `);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_items_invoiceId" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_customerId" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_orderId" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_customerId" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portal" ADD CONSTRAINT "FK_portal_deliveryId" FOREIGN KEY ("deliveryId") REFERENCES "delivery_persons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portal" ADD CONSTRAINT "FK_portal_customerId" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
