import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1774300911703 implements MigrationInterface {
    name = 'InitialMigration1774300911703'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" integer NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'MAD', "paymentMethod" character varying(50), "planName" character varying(20) NOT NULL, "billingCycle" character varying(10) NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "validatedBy" character varying(255), "validatedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" text, "referenceNumber" character varying(100), "receiptUrl" character varying(500), "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98a04cdcbac4f6a2c55c7d1935" ON "payments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE TABLE "tenant_activity_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" integer NOT NULL, "action" character varying(50) NOT NULL, "details" jsonb NOT NULL DEFAULT '{}', "performedBy" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_78c02b41527dbfec6f28a499ba7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0db175c3ceea97e92869ef3bd" ON "tenant_activity_log" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(50) NOT NULL, "databaseName" character varying(100) NOT NULL, "databaseHost" character varying(255) NOT NULL DEFAULT 'localhost', "databasePort" integer NOT NULL DEFAULT '5432', "isActive" boolean NOT NULL DEFAULT true, "logoUrl" character varying(500), "primaryColor" character varying(7), "contactName" character varying(100), "contactEmail" character varying(255), "contactPhone" character varying(20), "address" text, "notes" text, "status" character varying(20) NOT NULL DEFAULT 'trial', "previousStatus" character varying(20), "statusChangedAt" TIMESTAMP WITH TIME ZONE, "statusReason" text, "subscriptionPlan" character varying(20) NOT NULL DEFAULT 'trial', "trialDays" integer NOT NULL DEFAULT '30', "trialStartedAt" TIMESTAMP WITH TIME ZONE, "trialEndsAt" TIMESTAMP WITH TIME ZONE, "subscriptionStartedAt" TIMESTAMP WITH TIME ZONE, "subscriptionEndsAt" TIMESTAMP WITH TIME ZONE, "autoRenew" boolean NOT NULL DEFAULT false, "maxUsers" integer NOT NULL DEFAULT '5', "maxProducts" integer NOT NULL DEFAULT '100', "maxOrdersPerMonth" integer NOT NULL DEFAULT '500', "maxStorageMb" integer NOT NULL DEFAULT '500', "settings" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "disabledAt" TIMESTAMP WITH TIME ZONE, "archivedAt" TIMESTAMP WITH TIME ZONE, "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2310ecc5cb8be427097154b18f" ON "tenants" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_c59559e7872bc9726adef4669f" ON "tenants" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_aeda3fbdae9b3fbd23a3ba2dc8" ON "tenants" ("subscriptionEndsAt") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "key" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "module" character varying(100) NOT NULL, "action" character varying(50) NOT NULL, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b634526cdd01f2adba6c7ac07" ON "permissions" ("module") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_017943867ed5ceef9c03edd974" ON "permissions" ("key") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "isSuperAdmin" boolean NOT NULL DEFAULT false, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "partners" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "phoneNumber" character varying(50) NOT NULL, "email" character varying(255), "address" text, "ice" character varying(50), "if" character varying(50), "cnss" character varying(50), "rc" character varying(50), "patente" character varying(50), "tvaNumber" character varying(50), "deliveryAddress" text, "isCompany" boolean NOT NULL DEFAULT false, "latitude" numeric(10,7), "longitude" numeric(10,7), "googleMapsUrl" character varying(500), "wazeUrl" character varying(500), "isEnabled" boolean NOT NULL DEFAULT true, "isCustomer" boolean NOT NULL DEFAULT false, "isSupplier" boolean NOT NULL DEFAULT false, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6e9597dd1009c60cc359ef94521" UNIQUE ("phoneNumber"), CONSTRAINT "PK_998645b20820e4ab99aeae03b41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b39bc13ab676e74eada2e744d" ON "partners" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e9597dd1009c60cc359ef9452" ON "partners" ("phoneNumber") `);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "address" text, "city" character varying(100), "latitude" numeric(10,7), "longitude" numeric(10,7), "phoneNumber" character varying(50), "managerName" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8b96d60ff9a288f5ed862280d9" UNIQUE ("code"), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8b96d60ff9a288f5ed862280d" ON "warehouses" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_be9dd3cc2931f11f7440f2eeb1" ON "warehouses" ("name") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "type" character varying(50) NOT NULL DEFAULT 'product', "isActive" boolean NOT NULL DEFAULT true, "parentId" integer, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc591a3520526561b639a2432e" ON "categories" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b0be371d28245da6e4f4b6187" ON "categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "unit_of_measures" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "category" character varying(100) NOT NULL, "ratio" numeric(18,6) NOT NULL DEFAULT '1', "roundingPrecision" character varying(10), "isBaseUnit" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "baseUnitId" integer, CONSTRAINT "UQ_8b7582f97801147940892a96e08" UNIQUE ("code"), CONSTRAINT "PK_e875eebb54ac0b74160345926d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba507c058dae49c0bb3c0277dd" ON "unit_of_measures" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ad0970ca0247cec3c63a2c0dd" ON "unit_of_measures" ("name") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(100), "description" text, "price" numeric(18,2) NOT NULL DEFAULT '0', "cost" numeric(18,2) NOT NULL DEFAULT '0', "isService" boolean NOT NULL DEFAULT false, "isEnabled" boolean NOT NULL DEFAULT true, "isPriceChangeAllowed" boolean NOT NULL DEFAULT true, "imageUrl" text, "imagePublicId" character varying(500), "stock" integer, "saleTax" numeric(5,2) NOT NULL DEFAULT '0', "purchaseTax" numeric(5,2) NOT NULL DEFAULT '0', "minPrice" numeric(18,2) NOT NULL DEFAULT '0', "saleUnitId" integer, "purchaseUnitId" integer, "warehouseId" integer, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cfc24d6c24f0ec91294003d6b" ON "products" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."quotes_direction_enum" AS ENUM('VENTE', 'ACHAT')`);
        await queryRunner.query(`CREATE TYPE "public"."quotes_status_enum" AS ENUM('draft', 'open', 'signed', 'closed', 'delivered', 'invoiced')`);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" SERIAL NOT NULL, "date" date NOT NULL, "total" numeric(18,2) NOT NULL DEFAULT '0', "discount" numeric(18,2) NOT NULL DEFAULT '0', "discountType" integer NOT NULL DEFAULT '0', "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "customerId" integer, "direction" "public"."quotes_direction_enum" NOT NULL DEFAULT 'VENTE', "documentNumber" character varying(50) NOT NULL, "customerName" character varying(255), "customerPhone" character varying(50), "customerAddress" text, "subtotal" numeric(18,2) NOT NULL DEFAULT '0', "tax" numeric(18,2) NOT NULL DEFAULT '0', "isValidated" boolean NOT NULL DEFAULT false, "notes" text, "supplierId" integer, "supplierName" character varying(255), "supplierPhone" character varying(50), "supplierAddress" text, "expirationDate" date, "dueDate" date, "status" "public"."quotes_status_enum" NOT NULL DEFAULT 'draft', "validationDate" date, "pdfUrl" text, "clientNotes" text, "signedBy" character varying(255), "signedDate" TIMESTAMP, "shareToken" character varying(100), "shareTokenExpiry" TIMESTAMP, "convertedToInvoiceId" integer, "convertedToOrderId" integer, CONSTRAINT "UQ_ed719dddc8817c7088b921d0223" UNIQUE ("documentNumber"), CONSTRAINT "UQ_afd53cb409bcdc6a81c43c75ebe" UNIQUE ("shareToken"), CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1fc1db17214b25db2adc52ffd" ON "quotes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_93a085c3005dcd0d949a40b909" ON "quotes" ("expirationDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_5576bb64e37d0c192294627687" ON "quotes" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdc0e0c51bc015c5113e78136f" ON "quotes" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccf1feb9e280240bb05dc0aed2" ON "quotes" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed719dddc8817c7088b921d022" ON "quotes" ("documentNumber") `);
        await queryRunner.query(`CREATE TABLE "quote_items" ("id" SERIAL NOT NULL, "productId" integer, "quantity" numeric(18,3) NOT NULL DEFAULT '0', "discount" numeric(18,2) NOT NULL DEFAULT '0', "discountType" integer NOT NULL DEFAULT '0', "total" numeric(18,2) NOT NULL DEFAULT '0', "description" character varying(255) NOT NULL, "unitPrice" numeric(18,2) NOT NULL DEFAULT '0', "tax" numeric(5,2) NOT NULL DEFAULT '0', "quoteId" integer NOT NULL, CONSTRAINT "PK_135ad3f02b5abcf65fb5cb20ad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac5c52bd99a4569e49db986b82" ON "quote_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef162674660b3ed9dc76de2116" ON "quote_items" ("quoteId") `);
        await queryRunner.query(`CREATE TABLE "portal" ("id" SERIAL NOT NULL, "phoneNumber" character varying(50) NOT NULL, "password" character varying(255) NOT NULL, "name" character varying(255), "email" character varying(255), "isAdmin" boolean NOT NULL DEFAULT false, "isCustomer" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "status" character varying(20) NOT NULL DEFAULT 'pending', "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "customerId" integer, "userType" character varying(20) NOT NULL DEFAULT 'client', "avatarUrl" text, "roleId" integer, CONSTRAINT "UQ_3d80146508aa51bbc72f9951896" UNIQUE ("phoneNumber"), CONSTRAINT "PK_725cd9381e64f6b19862e564137" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d80146508aa51bbc72f995189" ON "portal" ("phoneNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_direction_enum" AS ENUM('VENTE', 'ACHAT')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'unpaid', 'partial', 'paid')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" SERIAL NOT NULL, "date" date NOT NULL, "total" numeric(18,2) NOT NULL DEFAULT '0', "discount" numeric(18,2) NOT NULL DEFAULT '0', "discountType" integer NOT NULL DEFAULT '0', "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "customerId" integer, "direction" "public"."invoices_direction_enum" NOT NULL DEFAULT 'VENTE', "documentNumber" character varying(50) NOT NULL, "customerName" character varying(255), "customerPhone" character varying(50), "customerAddress" text, "subtotal" numeric(18,2) NOT NULL DEFAULT '0', "tax" numeric(18,2) NOT NULL DEFAULT '0', "isValidated" boolean NOT NULL DEFAULT false, "notes" text, "supplierId" integer, "supplierName" character varying(255), "supplierPhone" character varying(50), "supplierAddress" text, "dueDate" date, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "validationDate" date, "pdfUrl" text, "paidAmount" numeric(18,2) NOT NULL DEFAULT '0', "remainingAmount" numeric(18,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_0c95a02856a1acb54a4168be9b0" UNIQUE ("documentNumber"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_df62845187eb4c31c0dcda454e" ON "invoices" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cf9a7d463c3262c954f3300fe" ON "invoices" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1df049f8943c6be0c1115541ef" ON "invoices" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c95a02856a1acb54a4168be9b" ON "invoices" ("documentNumber") `);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" SERIAL NOT NULL, "productId" integer, "quantity" numeric(18,3) NOT NULL DEFAULT '0', "discount" numeric(18,2) NOT NULL DEFAULT '0', "discountType" integer NOT NULL DEFAULT '0', "total" numeric(18,2) NOT NULL DEFAULT '0', "description" character varying(255) NOT NULL, "unitPrice" numeric(18,2) NOT NULL DEFAULT '0', "tax" numeric(5,2) NOT NULL DEFAULT '0', "invoiceId" integer NOT NULL, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7bec360ed9928668b73dac2ec1" ON "invoice_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fb6895fc8fad9f5200e91abb5" ON "invoice_items" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_direction_enum" AS ENUM('VENTE', 'ACHAT')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('draft', 'validated', 'in_progress', 'delivered', 'invoiced', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_deliverystatus_enum" AS ENUM('pending', 'assigned', 'confirmed', 'picked_up', 'to_delivery', 'in_delivery', 'delivered', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "date" date NOT NULL, "total" numeric(18,2) NOT NULL DEFAULT '0', "discount" numeric(18,2) NOT NULL DEFAULT '0', "discountType" integer NOT NULL DEFAULT '0', "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "customerId" integer, "direction" "public"."orders_direction_enum" NOT NULL DEFAULT 'VENTE', "documentNumber" character varying(50) NOT NULL, "customerName" character varying(255), "customerPhone" character varying(50), "customerAddress" text, "subtotal" numeric(18,2) NOT NULL DEFAULT '0', "tax" numeric(18,2) NOT NULL DEFAULT '0', "isValidated" boolean NOT NULL DEFAULT false, "notes" text, "supplierId" integer, "supplierName" character varying(255), "supplierPhone" character varying(50), "supplierAddress" text, "dueDate" date, "validationDate" date, "pdfUrl" text, "convertedToInvoiceId" integer, "fromPortal" boolean NOT NULL DEFAULT false, "fromClient" boolean NOT NULL DEFAULT false, "receiptNumber" character varying, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'draft', "deliveryStatus" "public"."orders_deliverystatus_enum", "pendingAt" TIMESTAMP, "assignedAt" TIMESTAMP, "confirmedAt" TIMESTAMP, "pickedUpAt" TIMESTAMP, "toDeliveryAt" TIMESTAMP, "inDeliveryAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "canceledAt" TIMESTAMP, CONSTRAINT "UQ_3e0f93349c0797c99b9a5789855" UNIQUE ("documentNumber"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1a1b9d21c8c68af3890586827" ON "orders" ("deliveryStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6dc3a53d92a338eb56dbc82cf5" ON "orders" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_37217f20f8c8b431ae720dd210" ON "orders" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5de51ca888d8b1f5ac25799dd" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e0f93349c0797c99b9a578985" ON "orders" ("documentNumber") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "productId" integer, "quantity" numeric(18,3) NOT NULL DEFAULT '0', "discount" numeric(18,2) NOT NULL DEFAULT '0', "discountType" integer NOT NULL DEFAULT '0', "total" numeric(18,2) NOT NULL DEFAULT '0', "description" character varying(255) NOT NULL, "unitPrice" numeric(18,2) NOT NULL DEFAULT '0', "tax" numeric(5,2) NOT NULL DEFAULT '0', "orderId" integer NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cdb99c05982d5191ac8465ac01" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "userId" integer, "type" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "data" jsonb, "priority" character varying(20) NOT NULL DEFAULT 'MEDIUM', "isRead" boolean NOT NULL DEFAULT false, "isArchived" boolean NOT NULL DEFAULT false, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_394cb9629118027d34274bb081" ON "notifications" ("dateCreated") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ba28344602d583583b9ea1a50" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."device_tokens_platform_enum" AS ENUM('web', 'android', 'ios')`);
        await queryRunner.query(`CREATE TYPE "public"."device_tokens_apptype_enum" AS ENUM('client', 'backoffice', 'delivery')`);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "token" text NOT NULL, "platform" "public"."device_tokens_platform_enum" NOT NULL DEFAULT 'web', "appType" "public"."device_tokens_apptype_enum" NOT NULL, "deviceName" character varying(255), "browserName" character varying(100), "osName" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_977e24c520c49436d08e5eeea8a" UNIQUE ("token"), CONSTRAINT "PK_84700be257607cfb1f9dc2e52c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_619d48b7cedf9a5e2397cbb13e" ON "device_tokens" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_d79f88d3f95f499de207e3d522" ON "device_tokens" ("appType") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a49ca04c463debb903d491301" ON "device_tokens" ("platform") `);
        await queryRunner.query(`CREATE INDEX "IDX_511957e3e8443429dc3fb00120" ON "device_tokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "stock_quants" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "warehouseId" integer NOT NULL, "quantity" numeric(18,4) NOT NULL DEFAULT '0', "reservedQuantity" numeric(18,4) NOT NULL DEFAULT '0', "availableQuantity" numeric(18,4) NOT NULL DEFAULT '0', "incomingQuantity" numeric(18,4) NOT NULL DEFAULT '0', "outgoingQuantity" numeric(18,4) NOT NULL DEFAULT '0', "unitOfMeasureId" integer, "lotNumber" character varying(100), "serialNumber" character varying(100), "expirationDate" TIMESTAMP, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94704f90ccf1389173d3f56cbd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76a939951fd52f5ecc7e9daea4" ON "stock_quants" ("warehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c4c38d0ad3c9d7202bc4518cd" ON "stock_quants" ("productId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6aadde98a9d5f26184ea03e528" ON "stock_quants" ("productId", "warehouseId") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_movementtype_enum" AS ENUM('receipt', 'delivery', 'internal', 'adjustment', 'production_in', 'production_out', 'return_in', 'return_out', 'scrap')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_status_enum" AS ENUM('draft', 'waiting', 'confirmed', 'assigned', 'done', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" SERIAL NOT NULL, "reference" character varying(50) NOT NULL, "movementType" "public"."stock_movements_movementtype_enum" NOT NULL DEFAULT 'internal', "productId" integer NOT NULL, "sourceWarehouseId" integer, "destWarehouseId" integer, "quantity" numeric(18,4) NOT NULL, "unitOfMeasureId" integer, "status" "public"."stock_movements_status_enum" NOT NULL DEFAULT 'draft', "dateScheduled" TIMESTAMP, "dateDone" TIMESTAMP, "origin" character varying(255), "lotNumber" character varying(100), "serialNumber" character varying(100), "notes" text, "createdByUserId" integer, "validatedByUserId" integer, "partnerName" character varying(255), "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_06f0c5a720f8750702edb44bf44" UNIQUE ("reference"), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a2bdf34bccb563df914210ce4" ON "stock_movements" ("dateScheduled") `);
        await queryRunner.query(`CREATE INDEX "IDX_06f0c5a720f8750702edb44bf4" ON "stock_movements" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_591aca148f00fd61c720c81424" ON "stock_movements" ("movementType") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9d62e3e30aa32d6d273509f81" ON "stock_movements" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d8c5ce4f5977802011b587b3a" ON "stock_movements" ("destWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcbe59d62b9ebe9a507c41f47b" ON "stock_movements" ("sourceWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3acb59db67e977be45e382fc5" ON "stock_movements" ("productId") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_adjustments_status_enum" AS ENUM('draft', 'in_progress', 'done', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "inventory_adjustments" ("id" SERIAL NOT NULL, "reference" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "warehouseId" integer NOT NULL, "status" "public"."inventory_adjustments_status_enum" NOT NULL DEFAULT 'draft', "adjustmentDate" TIMESTAMP, "userId" integer, "notes" text, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7e8748300907c68b4ac40b7cb1e" UNIQUE ("reference"), CONSTRAINT "PK_67a6cd67ec23f212ac3d124325e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b620366bf5523108d3d671f331" ON "inventory_adjustments" ("adjustmentDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c4bcb30ab95fcffdcf4a765be" ON "inventory_adjustments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_098288896b743608e8eb590ba8" ON "inventory_adjustments" ("warehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e8748300907c68b4ac40b7cb1" ON "inventory_adjustments" ("reference") `);
        await queryRunner.query(`CREATE TABLE "inventory_adjustment_lines" ("id" SERIAL NOT NULL, "adjustmentId" integer NOT NULL, "productId" integer NOT NULL, "theoreticalQuantity" numeric(18,4) NOT NULL DEFAULT '0', "countedQuantity" numeric(18,4) NOT NULL DEFAULT '0', "difference" numeric(18,4) NOT NULL DEFAULT '0', "lotNumber" character varying(100), "serialNumber" character varying(100), "notes" text, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54af94f1cd00c4bf959124da23a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4c13c8ed92ce8d081836b0170" ON "inventory_adjustment_lines" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e0019551838f1b1543a82f8a0" ON "inventory_adjustment_lines" ("adjustmentId") `);
        await queryRunner.query(`CREATE TYPE "public"."drive_shares_permission_enum" AS ENUM('viewer', 'editor', 'owner')`);
        await queryRunner.query(`CREATE TYPE "public"."drive_shares_target_type_enum" AS ENUM('user', 'everyone')`);
        await queryRunner.query(`CREATE TABLE "drive_shares" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "node_id" uuid NOT NULL, "permission" "public"."drive_shares_permission_enum" NOT NULL DEFAULT 'viewer', "target_type" "public"."drive_shares_target_type_enum" NOT NULL, "target_user_id" integer, "shared_by" integer NOT NULL, "message" text, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6f2f11c5a9fc6b696721f38112d" UNIQUE ("node_id", "target_type", "target_user_id"), CONSTRAINT "PK_99c7c194143660d969569b81e44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."drive_activity_action_enum" AS ENUM('upload', 'replace', 'download', 'delete', 'restore', 'create_folder', 'rename', 'move', 'copy', 'share', 'unshare', 'preview', 'version_restore', 'trash', 'permanent_delete')`);
        await queryRunner.query(`CREATE TABLE "drive_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."drive_activity_action_enum" NOT NULL, "node_id" uuid, "node_name" character varying(512) NOT NULL, "actor_id" integer NOT NULL, "target_user_id" integer, "version_id" uuid, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8498950ff51830d7095a1faae59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_826dd201fd3f10a2c94b738541" ON "drive_activity" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cd1d029c2938d5bd9377abacf" ON "drive_activity" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a7f6c6f9705a46a2a85eda0ab" ON "drive_activity" ("node_id") `);
        await queryRunner.query(`CREATE TABLE "drive_tags" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "color" character varying(7), "created_by" integer, CONSTRAINT "UQ_37ac176d2f38850e33786180a4a" UNIQUE ("name"), CONSTRAINT "PK_815d61b6b48131f65392b7e69c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drive_node_tags" ("node_id" uuid NOT NULL, "tag_id" integer NOT NULL, CONSTRAINT "PK_f767c4fa365c4e9ef1159922fb3" PRIMARY KEY ("node_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ce8e96371c46368962e59a3e5" ON "drive_node_tags" ("tag_id") `);
        await queryRunner.query(`CREATE TABLE "drive_nodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(6) NOT NULL, "name" character varying(512) NOT NULL, "parent_id" uuid, "owner_id" integer NOT NULL, "mime_type" character varying(255), "extension" character varying(50), "size_bytes" bigint, "storage_key" character varying(1024), "storage_bucket" character varying(255) NOT NULL DEFAULT 'orderium-drive', "active_version_id" uuid, "description" text, "is_starred" boolean NOT NULL DEFAULT false, "is_trashed" boolean NOT NULL DEFAULT false, "trashed_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_91068471facdce9ac40973f5282" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_750b3908f98a5f8928ebacce28" ON "drive_nodes" ("is_trashed") `);
        await queryRunner.query(`CREATE INDEX "IDX_67de9f3d57d74fd8e23c0dedc8" ON "drive_nodes" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_9afc22565f55df427a120db174" ON "drive_nodes" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0556348f698df46c155001fa58" ON "drive_nodes" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "drive_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "node_id" uuid NOT NULL, "version_number" integer NOT NULL, "storage_key" character varying(1024) NOT NULL, "storage_bucket" character varying(255) NOT NULL, "size_bytes" bigint NOT NULL, "mime_type" character varying(255) NOT NULL, "original_name" character varying(512) NOT NULL, "checksum_sha256" character varying(64), "uploaded_by" integer NOT NULL, "comment" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b5ac3fd7bf1a6bf0caae9dbd97e" UNIQUE ("node_id", "version_number"), CONSTRAINT "PK_a56c04f4f855dafb8130a3bda15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08441175076bb0e8a5850874db" ON "drive_versions" ("node_id") `);
        await queryRunner.query(`CREATE TABLE "delivery_persons" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255), "password" character varying(255) NOT NULL, "phoneNumber" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_29dd6f4506c39a32e73b4c2c8f0" UNIQUE ("email"), CONSTRAINT "PK_8bbe37e930e015fb30393075692" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8cc291687cdb44d42a208c9631" ON "delivery_persons" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_29dd6f4506c39a32e73b4c2c8f" ON "delivery_persons" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_delivery_status_enum" AS ENUM('pending', 'assigned', 'confirmed', 'picked_up', 'to_delivery', 'in_delivery', 'delivered', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "orders_delivery" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "deliveryPersonId" integer, "status" "public"."orders_delivery_status_enum" NOT NULL DEFAULT 'pending', "pendingAt" TIMESTAMP, "assignedAt" TIMESTAMP, "confirmedAt" TIMESTAMP, "pickedUpAt" TIMESTAMP, "toDeliveryAt" TIMESTAMP, "inDeliveryAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "canceledAt" TIMESTAMP, "notes" text, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_141cb5f1928caf8b0e77cb8bd66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a5c9fa770236835894f85316ac" ON "orders_delivery" ("status") `);
        await queryRunner.query(`CREATE TABLE "configurations" ("id" SERIAL NOT NULL, "entity" character varying(100) NOT NULL, "values" jsonb NOT NULL, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_083d801197d005a02e4b5fa589f" UNIQUE ("entity"), CONSTRAINT "PK_ef9fc29709cc5fc66610fc6a664" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_083d801197d005a02e4b5fa589" ON "configurations" ("entity") `);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "displayName" character varying(100) NOT NULL, "priceMonthly" numeric(10,2) NOT NULL DEFAULT '0', "priceYearly" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'MAD', "maxUsers" integer NOT NULL, "maxProducts" integer NOT NULL, "maxOrdersPerMonth" integer NOT NULL, "maxStorageMb" integer NOT NULL, "features" jsonb NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae18a0f6e0143f06474aa8cef1f" UNIQUE ("name"), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_d430a02aad006d8a70f3acd7d03" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "product_categories" ("productId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_e65c1adebf00d61f1c84a4f3950" PRIMARY KEY ("productId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6156a79599e274ee9d83b1de13" ON "product_categories" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdef3adba0c284fd103d0fd369" ON "product_categories" ("categoryId") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_98a04cdcbac4f6a2c55c7d1935"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "planName"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "billingCycle"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "periodStart"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "periodEnd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "validatedBy"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "validatedAt"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "rejectionReason"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "receiptUrl"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "tenantId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "currency" character varying(3) NOT NULL DEFAULT 'MAD'`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "paymentMethod" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "planName" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "billingCycle" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "periodStart" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "periodEnd" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "validatedBy" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "validatedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "rejectionReason" text`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "receiptUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "invoiceId" integer`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "orderId" integer`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "customerId" integer`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "supplierId" integer`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "paymentDate" date NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymenttype_enum" AS ENUM('cash', 'check', 'bank_transfer', 'credit_card', 'mobile_payment', 'other')`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "paymentType" "public"."payments_paymenttype_enum" NOT NULL DEFAULT 'cash'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "referenceNumber" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_98a04cdcbac4f6a2c55c7d1935" ON "payments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_98a04cdcbac4f6a2c55c7d19350" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_activity_log" ADD CONSTRAINT "FK_a0db175c3ceea97e92869ef3bd4" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_of_measures" ADD CONSTRAINT "FK_8c45c449f76da9948ded7159dab" FOREIGN KEY ("baseUnitId") REFERENCES "unit_of_measures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_93f14f453d597e4e015f3b5ad0a" FOREIGN KEY ("saleUnitId") REFERENCES "unit_of_measures"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9ac2ab69b92853c1c7a988aa79c" FOREIGN KEY ("purchaseUnitId") REFERENCES "unit_of_measures"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_2e593d5836b65fc8f8056b364fe" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_ccf1feb9e280240bb05dc0aed2a" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_bdc0e0c51bc015c5113e78136f4" FOREIGN KEY ("supplierId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_items" ADD CONSTRAINT "FK_ac5c52bd99a4569e49db986b825" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_items" ADD CONSTRAINT "FK_ef162674660b3ed9dc76de21160" FOREIGN KEY ("quoteId") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portal" ADD CONSTRAINT "FK_218766a99fd41fcf4424056ab4f" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portal" ADD CONSTRAINT "FK_c82396eada10c1a1ed5ebe58783" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_0cf9a7d463c3262c954f3300fe9" FOREIGN KEY ("supplierId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7bec360ed9928668b73dac2ec17" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_37217f20f8c8b431ae720dd210e" FOREIGN KEY ("supplierId") REFERENCES "partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_43d19956aeab008b49e0804c145" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_824be6feda5e655c49c4e0c534b" FOREIGN KEY ("customerId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_c93c5c654f9862a026c5249ac6a" FOREIGN KEY ("supplierId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "portal"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_quants" ADD CONSTRAINT "FK_9c4c38d0ad3c9d7202bc4518cdd" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_quants" ADD CONSTRAINT "FK_76a939951fd52f5ecc7e9daea47" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_quants" ADD CONSTRAINT "FK_cfe8c3d83e99b44e98be82c2087" FOREIGN KEY ("unitOfMeasureId") REFERENCES "unit_of_measures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_a3acb59db67e977be45e382fc56" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_fcbe59d62b9ebe9a507c41f47bd" FOREIGN KEY ("sourceWarehouseId") REFERENCES "warehouses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_5d8c5ce4f5977802011b587b3ae" FOREIGN KEY ("destWarehouseId") REFERENCES "warehouses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_42a32f383bdd9f4db9b6b6134c9" FOREIGN KEY ("unitOfMeasureId") REFERENCES "unit_of_measures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_adjustments" ADD CONSTRAINT "FK_098288896b743608e8eb590ba88" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_adjustment_lines" ADD CONSTRAINT "FK_2e0019551838f1b1543a82f8a0f" FOREIGN KEY ("adjustmentId") REFERENCES "inventory_adjustments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_adjustment_lines" ADD CONSTRAINT "FK_f4c13c8ed92ce8d081836b0170a" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drive_shares" ADD CONSTRAINT "FK_76b150cb57753f69c23d0c52d4a" FOREIGN KEY ("node_id") REFERENCES "drive_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drive_activity" ADD CONSTRAINT "FK_6a7f6c6f9705a46a2a85eda0ab3" FOREIGN KEY ("node_id") REFERENCES "drive_nodes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drive_node_tags" ADD CONSTRAINT "FK_e2bc86ce46029b477f57152c176" FOREIGN KEY ("node_id") REFERENCES "drive_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drive_node_tags" ADD CONSTRAINT "FK_3ce8e96371c46368962e59a3e58" FOREIGN KEY ("tag_id") REFERENCES "drive_tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drive_nodes" ADD CONSTRAINT "FK_0556348f698df46c155001fa58e" FOREIGN KEY ("parent_id") REFERENCES "drive_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drive_versions" ADD CONSTRAINT "FK_08441175076bb0e8a5850874db2" FOREIGN KEY ("node_id") REFERENCES "drive_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders_delivery" ADD CONSTRAINT "FK_f01dffdb2fd3c0f7e28b309bb39" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders_delivery" ADD CONSTRAINT "FK_500bc42c16ef014f0b14040d66d" FOREIGN KEY ("deliveryPersonId") REFERENCES "delivery_persons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_6156a79599e274ee9d83b1de139" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_fdef3adba0c284fd103d0fd3697" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_fdef3adba0c284fd103d0fd3697"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_6156a79599e274ee9d83b1de139"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "orders_delivery" DROP CONSTRAINT "FK_500bc42c16ef014f0b14040d66d"`);
        await queryRunner.query(`ALTER TABLE "orders_delivery" DROP CONSTRAINT "FK_f01dffdb2fd3c0f7e28b309bb39"`);
        await queryRunner.query(`ALTER TABLE "drive_versions" DROP CONSTRAINT "FK_08441175076bb0e8a5850874db2"`);
        await queryRunner.query(`ALTER TABLE "drive_nodes" DROP CONSTRAINT "FK_0556348f698df46c155001fa58e"`);
        await queryRunner.query(`ALTER TABLE "drive_node_tags" DROP CONSTRAINT "FK_3ce8e96371c46368962e59a3e58"`);
        await queryRunner.query(`ALTER TABLE "drive_node_tags" DROP CONSTRAINT "FK_e2bc86ce46029b477f57152c176"`);
        await queryRunner.query(`ALTER TABLE "drive_activity" DROP CONSTRAINT "FK_6a7f6c6f9705a46a2a85eda0ab3"`);
        await queryRunner.query(`ALTER TABLE "drive_shares" DROP CONSTRAINT "FK_76b150cb57753f69c23d0c52d4a"`);
        await queryRunner.query(`ALTER TABLE "inventory_adjustment_lines" DROP CONSTRAINT "FK_f4c13c8ed92ce8d081836b0170a"`);
        await queryRunner.query(`ALTER TABLE "inventory_adjustment_lines" DROP CONSTRAINT "FK_2e0019551838f1b1543a82f8a0f"`);
        await queryRunner.query(`ALTER TABLE "inventory_adjustments" DROP CONSTRAINT "FK_098288896b743608e8eb590ba88"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_42a32f383bdd9f4db9b6b6134c9"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_5d8c5ce4f5977802011b587b3ae"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_fcbe59d62b9ebe9a507c41f47bd"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_a3acb59db67e977be45e382fc56"`);
        await queryRunner.query(`ALTER TABLE "stock_quants" DROP CONSTRAINT "FK_cfe8c3d83e99b44e98be82c2087"`);
        await queryRunner.query(`ALTER TABLE "stock_quants" DROP CONSTRAINT "FK_76a939951fd52f5ecc7e9daea47"`);
        await queryRunner.query(`ALTER TABLE "stock_quants" DROP CONSTRAINT "FK_9c4c38d0ad3c9d7202bc4518cdd"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_c93c5c654f9862a026c5249ac6a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_824be6feda5e655c49c4e0c534b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_43d19956aeab008b49e0804c145"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_37217f20f8c8b431ae720dd210e"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7bec360ed9928668b73dac2ec17"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_0cf9a7d463c3262c954f3300fe9"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "portal" DROP CONSTRAINT "FK_c82396eada10c1a1ed5ebe58783"`);
        await queryRunner.query(`ALTER TABLE "portal" DROP CONSTRAINT "FK_218766a99fd41fcf4424056ab4f"`);
        await queryRunner.query(`ALTER TABLE "quote_items" DROP CONSTRAINT "FK_ef162674660b3ed9dc76de21160"`);
        await queryRunner.query(`ALTER TABLE "quote_items" DROP CONSTRAINT "FK_ac5c52bd99a4569e49db986b825"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_bdc0e0c51bc015c5113e78136f4"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_ccf1feb9e280240bb05dc0aed2a"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_2e593d5836b65fc8f8056b364fe"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9ac2ab69b92853c1c7a988aa79c"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_93f14f453d597e4e015f3b5ad0a"`);
        await queryRunner.query(`ALTER TABLE "unit_of_measures" DROP CONSTRAINT "FK_8c45c449f76da9948ded7159dab"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "tenant_activity_log" DROP CONSTRAINT "FK_a0db175c3ceea97e92869ef3bd4"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_98a04cdcbac4f6a2c55c7d19350"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98a04cdcbac4f6a2c55c7d1935"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "referenceNumber"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "referenceNumber" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "paymentType"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "paymentDate"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "supplierId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "invoiceId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "receiptUrl"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "rejectionReason"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "validatedAt"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "validatedBy"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "periodEnd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "periodStart"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "billingCycle"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "planName"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "receiptUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "rejectionReason" text`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "validatedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "validatedBy" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD "periodEnd" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "periodStart" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "billingCycle" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "planName" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "paymentMethod" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "currency" character varying(3) NOT NULL DEFAULT 'MAD'`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "tenantId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_98a04cdcbac4f6a2c55c7d1935" ON "payments" ("tenantId") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdef3adba0c284fd103d0fd369"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6156a79599e274ee9d83b1de13"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_083d801197d005a02e4b5fa589"`);
        await queryRunner.query(`DROP TABLE "configurations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5c9fa770236835894f85316ac"`);
        await queryRunner.query(`DROP TABLE "orders_delivery"`);
        await queryRunner.query(`DROP TYPE "public"."orders_delivery_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29dd6f4506c39a32e73b4c2c8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cc291687cdb44d42a208c9631"`);
        await queryRunner.query(`DROP TABLE "delivery_persons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08441175076bb0e8a5850874db"`);
        await queryRunner.query(`DROP TABLE "drive_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0556348f698df46c155001fa58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9afc22565f55df427a120db174"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67de9f3d57d74fd8e23c0dedc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_750b3908f98a5f8928ebacce28"`);
        await queryRunner.query(`DROP TABLE "drive_nodes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ce8e96371c46368962e59a3e5"`);
        await queryRunner.query(`DROP TABLE "drive_node_tags"`);
        await queryRunner.query(`DROP TABLE "drive_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a7f6c6f9705a46a2a85eda0ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cd1d029c2938d5bd9377abacf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_826dd201fd3f10a2c94b738541"`);
        await queryRunner.query(`DROP TABLE "drive_activity"`);
        await queryRunner.query(`DROP TYPE "public"."drive_activity_action_enum"`);
        await queryRunner.query(`DROP TABLE "drive_shares"`);
        await queryRunner.query(`DROP TYPE "public"."drive_shares_target_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."drive_shares_permission_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e0019551838f1b1543a82f8a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4c13c8ed92ce8d081836b0170"`);
        await queryRunner.query(`DROP TABLE "inventory_adjustment_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e8748300907c68b4ac40b7cb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_098288896b743608e8eb590ba8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c4bcb30ab95fcffdcf4a765be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b620366bf5523108d3d671f331"`);
        await queryRunner.query(`DROP TABLE "inventory_adjustments"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_adjustments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3acb59db67e977be45e382fc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcbe59d62b9ebe9a507c41f47b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d8c5ce4f5977802011b587b3a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9d62e3e30aa32d6d273509f81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_591aca148f00fd61c720c81424"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06f0c5a720f8750702edb44bf4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a2bdf34bccb563df914210ce4"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_movementtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6aadde98a9d5f26184ea03e528"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c4c38d0ad3c9d7202bc4518cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76a939951fd52f5ecc7e9daea4"`);
        await queryRunner.query(`DROP TABLE "stock_quants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_511957e3e8443429dc3fb00120"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a49ca04c463debb903d491301"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d79f88d3f95f499de207e3d522"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_619d48b7cedf9a5e2397cbb13e"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."device_tokens_apptype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."device_tokens_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ba28344602d583583b9ea1a50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_394cb9629118027d34274bb081"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdb99c05982d5191ac8465ac01"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e0f93349c0797c99b9a578985"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5de51ca888d8b1f5ac25799dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37217f20f8c8b431ae720dd210"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6dc3a53d92a338eb56dbc82cf5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1a1b9d21c8c68af3890586827"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_deliverystatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fb6895fc8fad9f5200e91abb5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bec360ed9928668b73dac2ec1"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c95a02856a1acb54a4168be9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df049f8943c6be0c1115541ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cf9a7d463c3262c954f3300fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df62845187eb4c31c0dcda454e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d80146508aa51bbc72f995189"`);
        await queryRunner.query(`DROP TABLE "portal"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef162674660b3ed9dc76de2116"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac5c52bd99a4569e49db986b82"`);
        await queryRunner.query(`DROP TABLE "quote_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed719dddc8817c7088b921d022"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccf1feb9e280240bb05dc0aed2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdc0e0c51bc015c5113e78136f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5576bb64e37d0c192294627687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93a085c3005dcd0d949a40b909"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1fc1db17214b25db2adc52ffd"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cfc24d6c24f0ec91294003d6b"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ad0970ca0247cec3c63a2c0dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba507c058dae49c0bb3c0277dd"`);
        await queryRunner.query(`DROP TABLE "unit_of_measures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b0be371d28245da6e4f4b6187"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc591a3520526561b639a2432e"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be9dd3cc2931f11f7440f2eeb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8b96d60ff9a288f5ed862280d"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e9597dd1009c60cc359ef9452"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b39bc13ab676e74eada2e744d"`);
        await queryRunner.query(`DROP TABLE "partners"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017943867ed5ceef9c03edd974"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b634526cdd01f2adba6c7ac07"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeda3fbdae9b3fbd23a3ba2dc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c59559e7872bc9726adef4669f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2310ecc5cb8be427097154b18f"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0db175c3ceea97e92869ef3bd"`);
        await queryRunner.query(`DROP TABLE "tenant_activity_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98a04cdcbac4f6a2c55c7d1935"`);
        await queryRunner.query(`DROP TABLE "payments"`);
    }

}
